# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class AdrTunnelRestrictionCodeEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The ADR tunnel restriction code. ADR is a European agreement concerning the international
    carriage of dangerous goods by road. The ADR tunnel restriction code is used to determine
    whether a vehicle is allowed to pass through a tunnel with restrictions on the carriage of
    dangerous goods.
    """

    B = "B"
    """Vehicles with code B are restricted from roads with ADR tunnel categories B, C, D, and E."""
    C = "C"
    """Vehicles with code C are restricted from roads with ADR tunnel categories C, D, and E."""
    D = "D"
    """Vehicles with code D are restricted from roads with ADR tunnel categories D and E."""
    E = "E"
    """Vehicles with code E are restricted from roads with ADR tunnel category E."""


class AvoidEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies restrictions that the route calculation should honor when determining the route.
    Avoid supports multiple values in a request and is only supported for the driving and truck
    travelMode.\\n\\nExample: \\"avoid\\": [\\"limitedAccessHighways\\", \\"tollRoads\\"].
    """

    LIMITED_ACCESS_HIGHWAYS = "limitedAccessHighways"
    """Avoids the use of limited access highways in the route."""
    TOLL_ROADS = "tollRoads"
    """Avoids the use of toll roads in the route."""
    FERRIES = "ferries"
    """Avoids the use of ferries in the route."""
    TUNNELS = "tunnels"
    """Avoids the use of tunnels in the route."""
    BORDER_CROSSINGS = "borderCrossings"
    """Avoids crossing country borders in the route."""
    LOW_EMISSION_ZONES = "lowEmissionZones"
    """Avoids low-emission zones in the route."""
    UNPAVED_ROADS = "unpavedRoads"
    """Avoids unpaved roads in the route."""


class DrivingSideEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Indicates left-hand vs. right-hand side driving at the point of the maneuver."""

    LEFT = "Left"
    """Left-hand side driving."""
    RIGHT = "Right"
    """Right-hand side driving."""


class FeaturesItemTypeEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies the ``GeoJSON`` type. The only supported object type is Feature. For more
    information, see `RFC 7946 <https://www.rfc-editor.org/rfc/rfc7946>`_.
    """

    FEATURE = "Feature"
    """Specifies the ``GeoJSON`` Feature object type."""


class FeatureTypeEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies the ``GeoJSON`` type. The only supported object type is ``FeatureCollection``. For
    more information, see `RFC 7946 <https://www.rfc-editor.org/rfc/rfc7946>`_.
    """

    FEATURE_COLLECTION = "FeatureCollection"
    """Specifies the ``GeoJSON`` ``FeatureCollection`` object type."""


class GeoJsonObjectType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies the ``GeoJSON`` type. Must be one of the nine valid GeoJSON object types - Point,
    MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection, Feature and
    FeatureCollection.
    """

    GEO_JSON_POINT = "Point"
    """``GeoJSON Point`` geometry."""
    GEO_JSON_MULTI_POINT = "MultiPoint"
    """``GeoJSON MultiPoint`` geometry."""
    GEO_JSON_LINE_STRING = "LineString"
    """``GeoJSON LineString`` geometry."""
    GEO_JSON_MULTI_LINE_STRING = "MultiLineString"
    """``GeoJSON MultiLineString`` geometry."""
    GEO_JSON_POLYGON = "Polygon"
    """``GeoJSON Polygon`` geometry."""
    GEO_JSON_MULTI_POLYGON = "MultiPolygon"
    """``GeoJSON MultiPolygon`` geometry."""
    GEO_JSON_GEOMETRY_COLLECTION = "GeometryCollection"
    """``GeoJSON GeometryCollection`` geometry."""
    GEO_JSON_FEATURE = "Feature"
    """``GeoJSON Feature`` object."""
    GEO_JSON_FEATURE_COLLECTION = "FeatureCollection"
    """``GeoJSON FeatureCollection`` object."""


class InputWaypointTypeEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Waypoint type on the route. It can be a stop or an intermediate location that the route must
    pass through.
    """

    WAYPOINT = "waypoint"
    """A waypoint is a specific location or point along a route or trip that serves as a reference or
    stopping point."""
    VIA_WAYPOINT = "viaWaypoint"
    """A viaWaypoint is a specific waypoint that must be passed through or visited along a route or
    trip."""


class ManeuverTypeEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The type of maneuver described in this detailed collection. The ManeuverType provides
    information for a portion of the maneuver specified by the corresponding instruction. For
    example, the maneuverType of an instruction may specify TurnLeftThenTurnRight, while the
    associated detail items may provide specifics about the TurnLeft and TurnRight maneuvers.
    """

    ARRIVE_FINISH = "ArriveFinish"
    """Arrive at the final destination."""
    ARRIVE_INTERMEDIATE = "ArriveIntermediate"
    """Arrive at an intermediate waypoint."""
    BEAR_LEFT = "BearLeft"
    """Bear left."""
    BEAR_LEFT_THEN_BEAR_LEFT = "BearLeftThenBearLeft"
    """Bear left and then bear left again."""
    BEAR_LEFT_THEN_BEAR_RIGHT = "BearLeftThenBearRight"
    """Bear left and then bear right."""
    BEAR_LEFT_THEN_TURN_LEFT = "BearLeftThenTurnLeft"
    """Bear left and then turn left."""
    BEAR_LEFT_THEN_TURN_RIGHT = "BearLeftThenTurnRight"
    """Bear left and then turn right."""
    BEAR_RIGHT = "BearRight"
    """Bear right."""
    BEAR_RIGHT_THEN_BEAR_LEFT = "BearRightThenBearLeft"
    """Bear right and then bear left."""
    BEAR_RIGHT_THEN_BEAR_RIGHT = "BearRightThenBearRight"
    """Bear right and then bear right again."""
    BEAR_RIGHT_THEN_TURN_LEFT = "BearRightThenTurnLeft"
    """Bear right and then turn left."""
    BEAR_RIGHT_THEN_TURN_RIGHT = "BearRightThenTurnRight"
    """Bear right and then turn right."""
    BEAR_THEN_KEEP = "BearThenKeep"
    """Bear instruction and then a keep instruction."""
    DEPART_START = "DepartStart"
    """Leave the starting point."""
    BEAR_THEN_MERGE = "BearThenMerge"
    """Bear instruction and then a merge instruction."""
    CONTINUEEnum = "Continue"
    """Continue on the current road."""
    DEPART_INTERMEDIATE_STOP = "DepartIntermediateStop"
    """Leave an intermediate waypoint in a different direction and road than you arrived on."""
    DEPART_INTERMEDIATE_STOP_RETURNING = "DepartIntermediateStopReturning"
    """Leave an intermediate waypoint in the same direction and on the same road that you arrived on."""
    ENTER_ROUNDABOUT = "EnterRoundabout"
    """Enter a roundabout."""
    EXIT_ROUNDABOUT = "ExitRoundabout"
    """Exit a roundabout."""
    ENTER_THEN_EXIT_ROUNDABOUT = "EnterThenExitRoundabout"
    """Enter and exit a roundabout."""
    EXIT_ROUNDABOUT_RIGHT = "ExitRoundaboutRight"
    """At the roundabout take the exit on the right."""
    EXIT_ROUNDABOUT_LEFT = "ExitRoundaboutLeft"
    """At the roundabout take the exit on the left."""
    FOLLOW = "Follow"
    """Follow."""
    GO_AROUND_ROUNDABOUT = "GoAroundRoundabout"
    """Go around the roundabout."""
    KEEP_LEFT = "KeepLeft"
    """Keep left onto a different road."""
    KEEP_ON_RAMP_LEFT = "KeepOnRampLeft"
    """Keep left and continue onto ramp."""
    KEEP_ON_RAMP_RIGHT = "KeepOnRampRight"
    """Keep right and continue onto ramp."""
    KEEP_ON_RAMP_STRAIGHT = "KeepOnRampStraight"
    """Keep straight and continue onto ramp."""
    KEEP_RIGHT = "KeepRight"
    """Keep right onto a different road."""
    KEEP_STRAIGHT = "KeepStraight"
    """Keep straight onto a different road."""
    KEEP_TO_STAY_LEFT = "KeepToStayLeft"
    """Keep left to stay on the same road."""
    KEEP_TO_STAY_RIGHT = "KeepToStayRight"
    """Keep right to stay on the same road."""
    KEEP_TO_STAY_STRAIGHT = "KeepToStayStraight"
    """Keep straight to stay on the same road."""
    MERGE_FREEWAY = "MergeFreeway"
    """Merge onto a freeway."""
    MERGE_HIGHWAY = "MergeHighway"
    """Merge onto a highway."""
    MERGE_MOTORWAY = "MergeMotorway"
    """Merge onto a motorway."""
    MOTORWAY_EXIT_LEFT = "MotorwayExitLeft"
    """Take the left exit."""
    MOTORWAY_EXIT_RIGHT = "MotorwayExitRight"
    """Take the right exit."""
    NONE = "None"
    """No instruction."""
    RAMP_THEN_HIGHWAY_LEFT = "RampThenHighwayLeft"
    """Take left ramp onto highway. This is part of a combined instruction."""
    RAMP_THEN_HIGHWAY_RIGHT = "RampThenHighwayRight"
    """Take right ramp onto highway. This is part of a combined instruction."""
    RAMP_THEN_HIGHWAY_STRAIGHT = "RampThenHighwayStraight"
    """Stay straight to take ramp onto highway. This is part of a combined instruction."""
    ROAD_NAME_CHANGE = "RoadNameChange"
    """Road name changes."""
    SWITCH_TO_PARALLEL_ROAD = "SwitchToParallelRoad"
    """Switch to the parallel road."""
    SWITCH_TO_MAIN_ROAD = "SwitchToMainRoad"
    """Switch to the main road."""
    TAKE = "Take"
    """Take the road. This instruction is used when you are entering or exiting a ferry."""
    TAKE_FERRY = "TakeFerry"
    """Take the ferry."""
    TAKE_EXIT = "TakeExit"
    """Take the exit."""
    TAKE_RAMP = "TakeRamp"
    """Take ramp."""
    TAKE_RAMP_LEFT = "TakeRampLeft"
    """Take ramp to the left."""
    TAKE_RAMP_RIGHT = "TakeRampRight"
    """Take ramp to the right."""
    TAKE_RAMP_STRAIGHT = "TakeRampStraight"
    """Stay straight to take ramp."""
    TURN_BACK = "TurnBack"
    """Turn back sharply."""
    TURN_LEFT = "TurnLeft"
    """Turn left."""
    TURN_LEFT_SHARP = "TurnLeftSharp"
    """Take a sharp left turn."""
    TURN_LEFT_THEN_BEAR_LEFT = "TurnLeftThenBearLeft"
    """Turn left and then bear left."""
    TURN_LEFT_THEN_BEAR_RIGHT = "TurnLeftThenBearRight"
    """Turn left and then bear right."""
    TURN_LEFT_THEN_TURN_LEFT = "TurnLeftThenTurnLeft"
    """Turn left and then turn left again."""
    TURN_LEFT_THEN_TURN_RIGHT = "TurnLeftThenTurnRight"
    """Turn left and then turn right."""
    TURN_RIGHT = "TurnRight"
    """Turn right."""
    TURN_RIGHT_SHARP = "TurnRightSharp"
    """Take a sharp right turn."""
    TURN_RIGHT_THEN_BEAR_LEFT = "TurnRightThenBearLeft"
    """Turn right and then bear left."""
    TURN_RIGHT_THEN_BEAR_RIGHT = "TurnRightThenBearRight"
    """Turn right and then bear right."""
    TURN_RIGHT_THEN_TURN_LEFT = "TurnRightThenTurnLeft"
    """Turn right and then turn left."""
    TURN_RIGHT_THEN_TURN_RIGHT = "TurnRightThenTurnRight"
    """Turn right and then turn right again."""
    TURN_THEN_MERGE = "TurnThenMerge"
    """Turn instruction followed by a merge instruction."""
    TURN_TO_STAY_LEFT = "TurnToStayLeft"
    """Turn left to stay on the same road."""
    TURN_TO_STAY_RIGHT = "TurnToStayRight"
    """Turn right to stay on the same road."""
    UNKNOWN = "Unknown"
    """The instruction is unknown."""
    U_TURN = "UTurn"
    """Make a u-turn to go in the opposite direction."""
    WAIT = "Wait"
    """Wait."""
    WALK = "Walk"
    """Walk."""


class PropertiesTypeEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Output type."""

    MANEUVER_POINT = "ManeuverPoint"
    """A maneuverPoint is a specific point on a route or trip where a change in direction or mode of
    transportation is required or recommended."""
    WAYPOINT = "Waypoint"
    """A waypoint is a specific location or point along a route or trip that serves as a reference or
    stopping point."""
    ROUTE_PATH = "RoutePath"
    """A routePath is a line that represents the path of a route or trip."""


class RouteDirectionOptimizeRouteEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies the parameter to use to optimize the route. If not defined, the
    default is "fastestWithoutTraffic" which returns the route to minimize the
    travel time without using current traffic information.

    Example: "optimizeRoute":"shortest".
    """

    SHORT = "short"
    """The route is calculated to balance fast travel time and short distance, rather than
    prioritizing just one. It's optimized for both speed and efficiency. Traffic information is not
    used."""
    SHORTEST = "shortest"
    """The route is calculated to minimize the distance. Traffic information is not used."""
    FASTEST_WITHOUT_TRAFFIC = "fastestWithoutTraffic"
    """Finds the fastest route, without factoring in traffic information."""
    FASTEST_WITH_TRAFFIC = "fastestWithTraffic"
    """The route is calculated to minimize the time using current traffic information. ``Note``: Only
    supported for driving and truck travelMode."""


class RouteMatrixAsyncOptimizeRouteEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies the parameter to use to optimize the route. If not defined, the
    default is "fastest" which returns the route to minimize the travel time.

    Example: "optimizeRoute":"shortest".
    """

    SHORTEST = "shortest"
    """Finds the shortest route to optimize route by travel distance."""
    FASTEST = "fastest"
    """Finds the fastest route to optimize route by travel time."""


class RouteMatrixAvoidEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies restrictions that the route calculation should honor when determining the route.
    Avoid supports multiple values in a request and is only supported for the driving and truck
    travelMode.
    """

    TOLL_ROADS = "tollRoads"
    """Avoids the use of toll roads in the route."""
    UNPAVED_ROADS = "unpavedRoads"
    """Avoids unpaved roads in the route."""


class RouteMatrixOptimizeRouteEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies the parameter to use to optimize the route. If not defined, the
    default is "fastest" which returns the route to minimize the travel time.

    Example: "optimizeRoute":"fastest ".
    """

    FASTEST = "fastest"
    """Finds the fastest route to optimize route by travel time.
    
    Only ``fastest`` is supported for the Route Matrix sync API. To use the other
    types, check the Route Matrix async API."""


class RouteMatrixTrafficEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies how traffic is considered for computing routes.

    Default value: ``historical``.
    """

    HISTORICAL = "historical"
    """Route calculation considers historical travel times and long term closures. Traffic jams and
    short-term closures during the travel time window do not influence routing or travel time."""
    LIVE = "live"
    """In addition to historical travel times, route calculation considers traffic
    jams and short- and long-term closures during the travel time window.
    
    ``Note``: ``traffic=live`` may not be used in conjunction with ``arriveAt=any`` and
    ``departAt=any``."""


class RouteMatrixTravelModeEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies the travel profile to consider when calculating the matrix. If not
    specified, the default value is "driving".

    Example: "travelMode":"driving".
    """

    DRIVING = "driving"
    """Routing profile suitable for cars are used for route matrix calculation."""
    TRUCK = "truck"
    """Routing profile suitable for commercial vehicles like trucks are used for route matrix
    calculation."""
    WALKING = "walking"
    """The returned routes are optimized for pedestrians, including the use of sidewalks."""


class RouteMatrixTypeEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies the origin MultiPoint type and destination MultiPoint type for the input matrix."""

    ORIGINS = "origins"
    """MultiPoint features that define the origin locations in the input matrix."""
    DESTINATIONS = "destinations"
    """MultiPoint features that define the destination locations in the input matrix."""


class RouteOperationKindEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Type of asynchronous operation."""

    ROUTE_MATRIX = "RouteMatrix"
    """Route matrix asynchronous job."""


class RouteOutputOptionEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The desired route information from the response."""

    ROUTE_SUMMARY = "routeSummary"
    """Include only travel time and distance for the route, and do not provide other information."""
    ROUTE_PATH = "routePath"
    """Include a GeoJSON MultiLineString `RFC 7946, section 3.1.5
    <https://www.rfc-editor.org/rfc/rfc7946#section-3.1.5>`_ that describe the route's path in the
    response."""
    ITINERARY = "itinerary"
    """Include detailed directions in the response. Detailed directions are provided as
    "ManeuverPoints" and contain details such as turn-by-turn instructions."""


class RoutePathTravelModeEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The mode of travel for the route path in the response."""

    DRIVING = "driving"
    """Routes optimized for cars."""
    TRUCK = "truck"
    """Routes optimized for large size trucks based on the vehicle specification."""
    WALKING = "walking"
    """Routes optimized for pedestrians."""
    OTHER = "other"
    """RouteTravelMode is returned as "other" for the truck travelMode when the truck route is not
    available for a particular section of a route."""


class RouteRangeAvoidEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies restrictions that the route calculation should honor when determining the reachable
    locations. Avoid supports multiple values in a request. \\n\\nExample: \\"avoid\\":
    [\\"limitedAccessHighways\\", \\"tollRoads\\"].
    """

    LIMITED_ACCESS_HIGHWAYS = "limitedAccessHighways"
    """Avoids the use of limited access highways in the route."""
    TOLL_ROADS = "tollRoads"
    """Avoids the use of toll roads in the route."""
    FERRIES = "ferries"
    """Avoids the use of ferries in the route."""
    TUNNELS = "tunnels"
    """Avoids the use of tunnels in the route."""
    BORDER_CROSSINGS = "borderCrossings"
    """Avoids crossing country borders in the route."""
    LOW_EMISSION_ZONES = "lowEmissionZones"
    """Avoids low-emission zones in the route."""
    UNPAVED_ROADS = "unpavedRoads"
    """Avoids unpaved roads in the route."""
    CARPOOLS = "carpools"
    """Avoids routes that require use of carpool."""
    CAR_TRAINS = "carTrains"
    """Avoids car trains."""


class RouteRangeOptimizeRouteEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies the parameter to use to optimize the route. If not defined, the
    default is "fastestWithoutTraffic" which returns the route to minimize the
    travel time without using current traffic information.

    Example: "optimizeRoute":"shortest".
    """

    SHORTEST = "shortest"
    """The route is calculated to minimize the distance. Traffic information is not used."""
    FASTEST_WITHOUT_TRAFFIC = "fastestWithoutTraffic"
    """Finds the fastest route, without factoring in traffic information."""
    FASTEST_WITH_TRAFFIC = "fastestWithTraffic"
    """The route is calculated to minimize the time using current traffic information. ``Note``: Only
    supported for driving and truck travelMode."""


class RouteRangeTravelModeEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies the travel profile to consider when calculating the range polygon. If
    not specified, the default value is "driving".

    Example: "travelMode":"driving".
    """

    DRIVING = "driving"
    """Routing profile suitable for cars are used for range polygon calculation."""
    TRUCK = "truck"
    """Routing profile suitable for commercial vehicles like trucks are used for range polygon
    calculation."""


class RouteRangeTypeEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The feature types for the feature objects returned in the response."""

    CENTER = "center"
    """The center point feature type represents the point used for the range polygon calculation."""
    BOUNDARY = "boundary"
    """The boundary feature type represents the range polygon."""


class SideOfStreetEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The side of the street where the destination is found based on the arrival direction. This
    field applies to the last maneuverPoint only.
    """

    LEFT = "Left"
    """Left."""
    RIGHT = "Right"
    """Right."""
    UNKNOWN = "Unknown"
    """Unknown."""


class SnapToRoadsTravelModeEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies the routing profile for snapping the points. If unspecified, the default mode is
    "driving", which optimizes the snapped points for driving routes.
    """

    DRIVING = "driving"
    """The points are snapped to the road suitable for cars."""
    TRUCK = "truck"
    """The points are snapped to the road suitable for truck."""


class StatusEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Current status of the async operation."""

    NOT_STARTED = "NotStarted"
    """The operation has not started yet."""
    RUNNING = "Running"
    """The operation is running."""
    COMPLETED = "Completed"
    """The operation has completed successfully."""
    FAILED = "Failed"
    """The operation has failed."""


class TrafficCongestionEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The level of traffic congestion along the route. ``Note``: Only supported for driving
    travelMode.
    """

    UNKNOWN = "Unknown"
    """Unknown."""
    NONE = "None"
    """None."""
    MILD = "Mild"
    """Mild."""
    MEDIUM = "Medium"
    """Medium."""
    HEAVY = "Heavy"
    """Heavy."""


class TravelModeEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The mode of travel for the requested route. If not defined, the default value
    is "driving" that returns the route optimized for cars.

    ``Note``: For truck travelMode, the requested truck route may not be available
    for the entire route. Where the truck route is not available for a particular
    section, the travelMode element of the response for that section will be
    "other".

    Example: "travelMode":"driving".
    """

    DRIVING = "driving"
    """The returned routes are optimized for cars."""
    TRUCK = "truck"
    """The returned routes are optimized for large size trucks based on the vehicle specification."""
    WALKING = "walking"
    """The returned routes are optimized for pedestrians, including the use of sidewalks."""


class VehicleLoadTypeEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Types of cargo that may be classified as hazardous materials and restricted from some roads."""

    US_HAZMAT_CLASS1 = "USHazmatClass1"
    """Explosives."""
    US_HAZMAT_CLASS2 = "USHazmatClass2"
    """Compressed gas."""
    US_HAZMAT_CLASS3 = "USHazmatClass3"
    """Flammable liquids."""
    US_HAZMAT_CLASS4 = "USHazmatClass4"
    """Flammable solids."""
    US_HAZMAT_CLASS5 = "USHazmatClass5"
    """Oxidizers."""
    US_HAZMAT_CLASS6 = "USHazmatClass6"
    """Poisons."""
    US_HAZMAT_CLASS7 = "USHazmatClass7"
    """Radioactive."""
    US_HAZMAT_CLASS8 = "USHazmatClass8"
    """Corrosives."""
    US_HAZMAT_CLASS9 = "USHazmatClass9"
    """Miscellaneous."""
    OTHER_HAZMAT_EXPLOSIVE = "otherHazmatExplosive"
    """Explosives."""
    OTHER_HAZMAT_GENERAL = "otherHazmatGeneral"
    """Miscellaneous."""
    OTHER_HAZMAT_HARMFUL_TO_WATER = "otherHazmatHarmfulToWater"
    """Harmful to water."""
