# pylint: disable=line-too-long,useless-suppression,too-many-lines
# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
from collections.abc import MutableMapping
from io import IOBase
import json
from typing import Any, Callable, IO, Optional, TypeVar, Union, overload

from azure.core import PipelineClient
from azure.core.exceptions import (
    ClientAuthenticationError,
    HttpResponseError,
    ResourceExistsError,
    ResourceNotFoundError,
    ResourceNotModifiedError,
    StreamClosedError,
    StreamConsumedError,
    map_error,
)
from azure.core.pipeline import PipelineResponse
from azure.core.rest import HttpRequest, HttpResponse
from azure.core.tracing.decorator import distributed_trace
from azure.core.utils import case_insensitive_dict

from .. import models as _models
from .._configuration import MapsSearchClientConfiguration
from .._utils.model_base import SdkJSONEncoder, _deserialize
from .._utils.serialization import Serializer
from .._utils.utils import ClientMixinABC
from .._validation import api_version_validation

JSON = MutableMapping[str, Any]
T = TypeVar("T")
ClsType = Optional[Callable[[PipelineResponse[HttpRequest, HttpResponse], T, dict[str, Any]], Any]]

_SERIALIZER = Serializer()
_SERIALIZER.client_side_validation = False


def build_maps_search_get_geocoding_request(
    *,
    accept_language: Optional[str] = None,
    top: Optional[int] = None,
    query: Optional[str] = None,
    address_line: Optional[str] = None,
    country_region: Optional[str] = None,
    bbox: Optional[list[float]] = None,
    view: Optional[str] = None,
    coordinates: Optional[list[float]] = None,
    admin_district: Optional[str] = None,
    admin_district2: Optional[str] = None,
    admin_district3: Optional[str] = None,
    locality: Optional[str] = None,
    postal_code: Optional[str] = None,
    client_id: Optional[str] = None,
    **kwargs: Any
) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "2025-06-01-preview"))
    accept = _headers.pop("Accept", "application/geo+json")

    # Construct URL
    _url = "/geocode"

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")
    if top is not None:
        _params["top"] = _SERIALIZER.query("top", top, "int")
    if query is not None:
        _params["query"] = _SERIALIZER.query("query", query, "str")
    if address_line is not None:
        _params["addressLine"] = _SERIALIZER.query("address_line", address_line, "str")
    if country_region is not None:
        _params["countryRegion"] = _SERIALIZER.query("country_region", country_region, "str")
    if bbox is not None:
        _params["bbox"] = _SERIALIZER.query("bbox", bbox, "[float]", div=",")
    if view is not None:
        _params["view"] = _SERIALIZER.query("view", view, "str")
    if coordinates is not None:
        _params["coordinates"] = _SERIALIZER.query("coordinates", coordinates, "[float]", div=",")
    if admin_district is not None:
        _params["adminDistrict"] = _SERIALIZER.query("admin_district", admin_district, "str")
    if admin_district2 is not None:
        _params["adminDistrict2"] = _SERIALIZER.query("admin_district2", admin_district2, "str")
    if admin_district3 is not None:
        _params["adminDistrict3"] = _SERIALIZER.query("admin_district3", admin_district3, "str")
    if locality is not None:
        _params["locality"] = _SERIALIZER.query("locality", locality, "str")
    if postal_code is not None:
        _params["postalCode"] = _SERIALIZER.query("postal_code", postal_code, "str")

    # Construct headers
    if accept_language is not None:
        _headers["accept-language"] = _SERIALIZER.header("accept_language", accept_language, "str")
    if client_id is not None:
        _headers["client-id"] = _SERIALIZER.header("client_id", client_id, "str")
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="GET", url=_url, params=_params, headers=_headers, **kwargs)


def build_maps_search_get_geocoding_batch_request(  # pylint: disable=name-too-long
    *, client_id: Optional[str] = None, accept_language: Optional[str] = None, **kwargs: Any
) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "2025-06-01-preview"))
    accept = _headers.pop("Accept", "application/json")

    # Construct URL
    _url = "/geocode:batch"

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")

    # Construct headers
    if client_id is not None:
        _headers["client-id"] = _SERIALIZER.header("client_id", client_id, "str")
    if accept_language is not None:
        _headers["accept-language"] = _SERIALIZER.header("accept_language", accept_language, "str")
    if content_type is not None:
        _headers["Content-Type"] = _SERIALIZER.header("content_type", content_type, "str")
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="POST", url=_url, params=_params, headers=_headers, **kwargs)


def build_maps_search_get_polygon_request(
    *,
    coordinates: list[float],
    client_id: Optional[str] = None,
    accept_language: Optional[str] = None,
    view: Optional[str] = None,
    result_type: Optional[Union[str, _models.BoundaryResultType]] = None,
    resolution: Optional[Union[str, _models.Resolution]] = None,
    **kwargs: Any
) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "2025-06-01-preview"))
    accept = _headers.pop("Accept", "application/geo+json")

    # Construct URL
    _url = "/search/polygon"

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")
    _params["coordinates"] = _SERIALIZER.query("coordinates", coordinates, "[float]", div=",")
    if view is not None:
        _params["view"] = _SERIALIZER.query("view", view, "str")
    if result_type is not None:
        _params["resultType"] = _SERIALIZER.query("result_type", result_type, "str")
    if resolution is not None:
        _params["resolution"] = _SERIALIZER.query("resolution", resolution, "str")

    # Construct headers
    if client_id is not None:
        _headers["client-id"] = _SERIALIZER.header("client_id", client_id, "str")
    if accept_language is not None:
        _headers["accept-language"] = _SERIALIZER.header("accept_language", accept_language, "str")
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="GET", url=_url, params=_params, headers=_headers, **kwargs)


def build_maps_search_get_reverse_geocoding_request(  # pylint: disable=name-too-long
    *,
    coordinates: list[float],
    client_id: Optional[str] = None,
    accept_language: Optional[str] = None,
    result_types: Optional[list[Union[str, _models.ReverseGeocodingResultType]]] = None,
    view: Optional[str] = None,
    **kwargs: Any
) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "2025-06-01-preview"))
    accept = _headers.pop("Accept", "application/geo+json")

    # Construct URL
    _url = "/reverseGeocode"

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")
    _params["coordinates"] = _SERIALIZER.query("coordinates", coordinates, "[float]", div=",")
    if result_types is not None:
        _params["resultTypes"] = _SERIALIZER.query("result_types", result_types, "[str]", div=",")
    if view is not None:
        _params["view"] = _SERIALIZER.query("view", view, "str")

    # Construct headers
    if client_id is not None:
        _headers["client-id"] = _SERIALIZER.header("client_id", client_id, "str")
    if accept_language is not None:
        _headers["accept-language"] = _SERIALIZER.header("accept_language", accept_language, "str")
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="GET", url=_url, params=_params, headers=_headers, **kwargs)


def build_maps_search_get_reverse_geocoding_batch_request(  # pylint: disable=name-too-long
    *, client_id: Optional[str] = None, accept_language: Optional[str] = None, **kwargs: Any
) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "2025-06-01-preview"))
    accept = _headers.pop("Accept", "application/json")

    # Construct URL
    _url = "/reverseGeocode:batch"

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")

    # Construct headers
    if client_id is not None:
        _headers["client-id"] = _SERIALIZER.header("client_id", client_id, "str")
    if accept_language is not None:
        _headers["accept-language"] = _SERIALIZER.header("accept_language", accept_language, "str")
    if content_type is not None:
        _headers["Content-Type"] = _SERIALIZER.header("content_type", content_type, "str")
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="POST", url=_url, params=_params, headers=_headers, **kwargs)


def build_maps_search_get_geocode_autocomplete_request(  # pylint: disable=name-too-long
    *,
    query: str,
    client_id: Optional[str] = None,
    accept_language: Optional[str] = None,
    coordinates: Optional[list[float]] = None,
    bbox: Optional[list[float]] = None,
    top: Optional[int] = None,
    result_type_groups: Optional[list[Union[str, _models.AutocompleteResultTypeGroups]]] = None,
    result_types: Optional[list[Union[str, _models.AutocompleteResultType]]] = None,
    view: Optional[str] = None,
    country_region: Optional[str] = None,
    **kwargs: Any
) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "2025-06-01-preview"))
    accept = _headers.pop("Accept", "application/geo+json")

    # Construct URL
    _url = "/geocode:autocomplete"

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")
    _params["query"] = _SERIALIZER.query("query", query, "str")
    if coordinates is not None:
        _params["coordinates"] = _SERIALIZER.query("coordinates", coordinates, "[float]", div=",")
    if bbox is not None:
        _params["bbox"] = _SERIALIZER.query("bbox", bbox, "[float]", div=",")
    if top is not None:
        _params["top"] = _SERIALIZER.query("top", top, "int")
    if result_type_groups is not None:
        _params["resultTypeGroups"] = _SERIALIZER.query("result_type_groups", result_type_groups, "[str]", div=",")
    if result_types is not None:
        _params["resultTypes"] = _SERIALIZER.query("result_types", result_types, "[str]", div=",")
    if view is not None:
        _params["view"] = _SERIALIZER.query("view", view, "str")
    if country_region is not None:
        _params["countryRegion"] = _SERIALIZER.query("country_region", country_region, "str")

    # Construct headers
    if client_id is not None:
        _headers["client-id"] = _SERIALIZER.header("client_id", client_id, "str")
    if accept_language is not None:
        _headers["accept-language"] = _SERIALIZER.header("accept_language", accept_language, "str")
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="GET", url=_url, params=_params, headers=_headers, **kwargs)


class _MapsSearchClientOperationsMixin(
    ClientMixinABC[PipelineClient[HttpRequest, HttpResponse], MapsSearchClientConfiguration]
):

    @distributed_trace
    def get_geocoding(  # pylint: disable=too-many-locals
        self,
        *,
        accept_language: Optional[str] = None,
        top: Optional[int] = None,
        query: Optional[str] = None,
        address_line: Optional[str] = None,
        country_region: Optional[str] = None,
        bbox: Optional[list[float]] = None,
        view: Optional[str] = None,
        coordinates: Optional[list[float]] = None,
        admin_district: Optional[str] = None,
        admin_district2: Optional[str] = None,
        admin_district3: Optional[str] = None,
        locality: Optional[str] = None,
        postal_code: Optional[str] = None,
        client_id: Optional[str] = None,
        **kwargs: Any
    ) -> _models.GeocodingResponse:
        """Use to get longitude and latitude coordinates of a street address or name of a place.

        The ``Get Geocoding`` API is an HTTP ``GET`` request that returns the longitude and
        latitude coordinates of the location being searched.

        In many cases, the complete search service might be too much, for instance if
        you are only interested in traditional geocoding. Search can also be accessed
        for address look up exclusively. The geocoding is performed by hitting the
        geocoding endpoint with just the address or partial address in question. The
        geocoding search index will be queried for everything above the street level
        data. No Point of Interest (POIs) will be returned. Note that the geocoder is
        very tolerant of typos and incomplete addresses. It will also handle everything
        from exact street addresses or street or intersections as well as higher level
        geographies such as city centers, counties and states. The response also
        returns detailed address properties such as street, postal code, municipality,
        and country/region information.

        [!Important]
        By using this feature, you agree to the preview legal terms. For more
        information, see [Preview Supplemental
        Terms](https://azure.microsoft.com/en-us/support/legal/preview-supplemental-terms/).

        .

        :keyword accept_language: Language in which search results should be returned.

         Please refer to `Supported
         Languages </azure/azure-maps/supported-languages?pivots=service-latest>`_ for
         details. Default value is None.
        :paramtype accept_language: str
        :keyword top: Maximum number of responses that will be returned. Default: 5, minimum: 1 and
         maximum: 20. Default value is None.
        :paramtype top: int
        :keyword query: A string that contains information about a location, such as an address or
         landmark name. Default value is None.
        :paramtype query: str
        :keyword address_line: The official street line of an address relative to the area, as
         specified by
         the locality, or postalCode, properties. Typical use of this element would be
         to provide a street address or any official address.

         This parameter should not be used when the ``query`` parameter is included in the
         request. Default value is None.
        :paramtype address_line: str
        :keyword country_region: Signal for the geocoding result to an `ISO 3166-1 Alpha-2
         region/country
         code <https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2>`_ that is specified e.g.
         FR.

         This parameter should not be used when the ``query`` parameter is included in the
         request. Default value is None.
        :paramtype country_region: str
        :keyword bbox: A rectangular area on the earth defined as a bounding box object. The sides of
         the rectangle are defined by longitude and latitude values. When you specify
         this parameter, the geographical area is taken into account when computing the
         results of a location query.

         Example: lon1,lat1,lon2,lat2.

         Minimum size: approximately 0.00001 degrees (~0.01 meters).

         Maximum size: up to the full global extent (-180,-90 to 180,90). Default value is None.
        :paramtype bbox: list[float]
        :keyword view: A string that represents an `ISO 3166-1 Alpha-2 region/country
         code <https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2>`_. This will alter
         Geopolitical disputed borders and labels to align with the specified user
         region. By default, the View parameter is set to “Auto” even if you haven’t
         defined it in the request.

         Please refer to `Supported Views <https://aka.ms/AzureMapsLocalizationViews>`_
         for details and to see the available Views. Default value is None.
        :paramtype view: str
        :keyword coordinates: A point on the earth specified as a longitude and latitude. When you
         specify
         this parameter, the user’s location is taken into account and the results
         returned may be more relevant to the user. Example: &coordinates=lon,lat. Default value is
         None.
        :paramtype coordinates: list[float]
        :keyword admin_district: The country subdivision portion of an address, such as WA.

         This parameter should not be used when the ``query`` parameter is included in the
         request. Default value is None.
        :paramtype admin_district: str
        :keyword admin_district2: The county for the structured address, such as King.

         This parameter should not be used when the ``query`` parameter is included in the
         request. Default value is None.
        :paramtype admin_district2: str
        :keyword admin_district3: The named area for the structured address.

         This parameter should not be used when the ``query`` parameter is included in the
         request. Default value is None.
        :paramtype admin_district3: str
        :keyword locality: The locality portion of an address, such as Seattle.

         This parameter should not be used when the ``query`` parameter is included in the
         request. Default value is None.
        :paramtype locality: str
        :keyword postal_code: The postal code portion of an address.

         This parameter should not be used when the ``query`` parameter is included in the
         request. Default value is None.
        :paramtype postal_code: str
        :keyword client_id: Specifies which account is intended for usage in conjunction with the Azure
         AD
         security model.  It represents a unique ID for the Azure Maps account and can
         be retrieved from the Azure Maps management plane Account API. For more
         information on using Microsoft Entra ID security in Azure Maps, see `Manage
         authentication in Azure Maps </azure/azure-maps/how-to-manage-authentication>`_. Default value
         is None.
        :paramtype client_id: str
        :return: GeocodingResponse. The GeocodingResponse is compatible with MutableMapping
        :rtype: ~azure.maps.search.models.GeocodingResponse
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls: ClsType[_models.GeocodingResponse] = kwargs.pop("cls", None)

        _request = build_maps_search_get_geocoding_request(
            accept_language=accept_language,
            top=top,
            query=query,
            address_line=address_line,
            country_region=country_region,
            bbox=bbox,
            view=view,
            coordinates=coordinates,
            admin_district=admin_district,
            admin_district2=admin_district2,
            admin_district3=admin_district3,
            locality=locality,
            postal_code=postal_code,
            client_id=client_id,
            api_version=self._config.api_version,
            headers=_headers,
            params=_params,
        )
        path_format_arguments = {
            "endpoint": self._serialize.url("self._config.endpoint", self._config.endpoint, "str", skip_quote=True),
        }
        _request.url = self._client.format_url(_request.url, **path_format_arguments)

        _decompress = kwargs.pop("decompress", True)
        _stream = kwargs.pop("stream", False)
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            if _stream:
                try:
                    response.read()  # Load the body in memory and close the socket
                except (StreamConsumedError, StreamClosedError):
                    pass
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        response_headers = {}
        response_headers["content-type"] = self._deserialize("str", response.headers.get("content-type"))

        if _stream:
            deserialized = response.iter_bytes() if _decompress else response.iter_raw()
        else:
            deserialized = _deserialize(_models.GeocodingResponse, response.json())

        if cls:
            return cls(pipeline_response, deserialized, response_headers)  # type: ignore

        return deserialized  # type: ignore

    @overload
    def get_geocoding_batch(
        self,
        geocoding_batch_request_body: _models.GeocodingBatchRequestBody,
        *,
        client_id: Optional[str] = None,
        accept_language: Optional[str] = None,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> _models.GeocodingBatchResponse:
        """Use to send a batch of queries to the `Geocoding </rest/api/maps/search/get-geocoding>`_ API in
        a single request.

        The ``Get Geocoding Batch`` API is an HTTP ``POST`` request that sends batches of
        up to **100** queries to the `Geocoding </rest/api/maps/search/get-geocoding>`_
        API in a single request.

        [!Important]
        By using this feature, you agree to the preview legal terms. For more
        information, see [Preview Supplemental
        Terms](https://azure.microsoft.com/en-us/support/legal/preview-supplemental-terms/).




        ================================
        Submit Synchronous Batch Request
        ================================

        The Synchronous API is recommended for lightweight batch requests. When the
        service receives a request, it will respond as soon as the batch items are
        calculated and there will be no possibility to retrieve the results later. The
        Synchronous API will return a timeout error (a 408 response) if the request
        takes longer than 60 seconds. The number of batch items is limited to **100**
        for this API.

        .. code-block::

           POST
        https://atlas.microsoft.com/geocode:batch?api-version=2023-06-01===========================
        POST Body for Batch Request
        ===========================

        To send the *geocoding* queries you will use a ``POST`` request where the request
        body will contain the ``batchItems`` array in ``json`` format and the
        ``Content-Type`` header will be set to ``application/json``. Here's a sample
        request body containing 2 *geocoding* queries:




        .. code-block::

           {
             "batchItems": [
               {
                 "addressLine": "One, Microsoft Way, Redmond, WA 98052",
                 "top": 2
               },
               {
                 "addressLine": "Pike Pl",
                 "adminDistrict": "WA",
                 "locality": "Seattle",
                 "top": 3
               }
             ]
           }

        A *geocoding* batchItem object can accept any of the supported *geocoding* `URI
        parameters </rest/api/maps/search/get-geocoding#uri-parameters>`_.


        The batch should contain at least **1** query.


        ====================
        Batch Response Model
        ====================

        The batch response contains a ``summary`` component that indicates the
        ``totalRequests`` that were part of the original batch request and
        ``successfulRequests`` i.e. queries which were executed successfully. The batch
        response also includes a ``batchItems`` array which contains a response for each
        and every query in the batch request. The ``batchItems`` will contain the results
        in the exact same order the original queries were sent in the batch request.
        Each item is of one of the following types:



        * ``GeocodingResponse` </rest/api/maps/search/get-geocoding#geocodingresponse>`_ -
        If the query completed successfully.



        * `Error` - If the query failed. The response will contain a `code` and a
        `message` in this case.

        :param geocoding_batch_request_body: The list of address geocoding queries/requests to process.
         The list can contain
         a max of 100 queries and must contain at least 1 query. Required.
        :type geocoding_batch_request_body: ~azure.maps.search.models.GeocodingBatchRequestBody
        :keyword client_id: Specifies which account is intended for usage in conjunction with the Azure
         AD
         security model.  It represents a unique ID for the Azure Maps account and can
         be retrieved from the Azure Maps management plane Account API. For more
         information on using Microsoft Entra ID security in Azure Maps, see `Manage
         authentication in Azure Maps </azure/azure-maps/how-to-manage-authentication>`_. Default value
         is None.
        :paramtype client_id: str
        :keyword accept_language: Language in which search results should be returned.

         Please refer to `Supported
         Languages </azure/azure-maps/supported-languages?pivots=service-latest>`_ for
         details. Default value is None.
        :paramtype accept_language: str
        :keyword content_type: Body Parameter content-type. Content type parameter for JSON body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: GeocodingBatchResponse. The GeocodingBatchResponse is compatible with MutableMapping
        :rtype: ~azure.maps.search.models.GeocodingBatchResponse
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @overload
    def get_geocoding_batch(
        self,
        geocoding_batch_request_body: JSON,
        *,
        client_id: Optional[str] = None,
        accept_language: Optional[str] = None,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> _models.GeocodingBatchResponse:
        """Use to send a batch of queries to the `Geocoding </rest/api/maps/search/get-geocoding>`_ API in
        a single request.

        The ``Get Geocoding Batch`` API is an HTTP ``POST`` request that sends batches of
        up to **100** queries to the `Geocoding </rest/api/maps/search/get-geocoding>`_
        API in a single request.

        [!Important]
        By using this feature, you agree to the preview legal terms. For more
        information, see [Preview Supplemental
        Terms](https://azure.microsoft.com/en-us/support/legal/preview-supplemental-terms/).




        ================================
        Submit Synchronous Batch Request
        ================================

        The Synchronous API is recommended for lightweight batch requests. When the
        service receives a request, it will respond as soon as the batch items are
        calculated and there will be no possibility to retrieve the results later. The
        Synchronous API will return a timeout error (a 408 response) if the request
        takes longer than 60 seconds. The number of batch items is limited to **100**
        for this API.

        .. code-block::

           POST
        https://atlas.microsoft.com/geocode:batch?api-version=2023-06-01===========================
        POST Body for Batch Request
        ===========================

        To send the *geocoding* queries you will use a ``POST`` request where the request
        body will contain the ``batchItems`` array in ``json`` format and the
        ``Content-Type`` header will be set to ``application/json``. Here's a sample
        request body containing 2 *geocoding* queries:




        .. code-block::

           {
             "batchItems": [
               {
                 "addressLine": "One, Microsoft Way, Redmond, WA 98052",
                 "top": 2
               },
               {
                 "addressLine": "Pike Pl",
                 "adminDistrict": "WA",
                 "locality": "Seattle",
                 "top": 3
               }
             ]
           }

        A *geocoding* batchItem object can accept any of the supported *geocoding* `URI
        parameters </rest/api/maps/search/get-geocoding#uri-parameters>`_.


        The batch should contain at least **1** query.


        ====================
        Batch Response Model
        ====================

        The batch response contains a ``summary`` component that indicates the
        ``totalRequests`` that were part of the original batch request and
        ``successfulRequests`` i.e. queries which were executed successfully. The batch
        response also includes a ``batchItems`` array which contains a response for each
        and every query in the batch request. The ``batchItems`` will contain the results
        in the exact same order the original queries were sent in the batch request.
        Each item is of one of the following types:



        * ``GeocodingResponse` </rest/api/maps/search/get-geocoding#geocodingresponse>`_ -
        If the query completed successfully.



        * `Error` - If the query failed. The response will contain a `code` and a
        `message` in this case.

        :param geocoding_batch_request_body: The list of address geocoding queries/requests to process.
         The list can contain
         a max of 100 queries and must contain at least 1 query. Required.
        :type geocoding_batch_request_body: JSON
        :keyword client_id: Specifies which account is intended for usage in conjunction with the Azure
         AD
         security model.  It represents a unique ID for the Azure Maps account and can
         be retrieved from the Azure Maps management plane Account API. For more
         information on using Microsoft Entra ID security in Azure Maps, see `Manage
         authentication in Azure Maps </azure/azure-maps/how-to-manage-authentication>`_. Default value
         is None.
        :paramtype client_id: str
        :keyword accept_language: Language in which search results should be returned.

         Please refer to `Supported
         Languages </azure/azure-maps/supported-languages?pivots=service-latest>`_ for
         details. Default value is None.
        :paramtype accept_language: str
        :keyword content_type: Body Parameter content-type. Content type parameter for JSON body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: GeocodingBatchResponse. The GeocodingBatchResponse is compatible with MutableMapping
        :rtype: ~azure.maps.search.models.GeocodingBatchResponse
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @overload
    def get_geocoding_batch(
        self,
        geocoding_batch_request_body: IO[bytes],
        *,
        client_id: Optional[str] = None,
        accept_language: Optional[str] = None,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> _models.GeocodingBatchResponse:
        """Use to send a batch of queries to the `Geocoding </rest/api/maps/search/get-geocoding>`_ API in
        a single request.

        The ``Get Geocoding Batch`` API is an HTTP ``POST`` request that sends batches of
        up to **100** queries to the `Geocoding </rest/api/maps/search/get-geocoding>`_
        API in a single request.

        [!Important]
        By using this feature, you agree to the preview legal terms. For more
        information, see [Preview Supplemental
        Terms](https://azure.microsoft.com/en-us/support/legal/preview-supplemental-terms/).




        ================================
        Submit Synchronous Batch Request
        ================================

        The Synchronous API is recommended for lightweight batch requests. When the
        service receives a request, it will respond as soon as the batch items are
        calculated and there will be no possibility to retrieve the results later. The
        Synchronous API will return a timeout error (a 408 response) if the request
        takes longer than 60 seconds. The number of batch items is limited to **100**
        for this API.

        .. code-block::

           POST
        https://atlas.microsoft.com/geocode:batch?api-version=2023-06-01===========================
        POST Body for Batch Request
        ===========================

        To send the *geocoding* queries you will use a ``POST`` request where the request
        body will contain the ``batchItems`` array in ``json`` format and the
        ``Content-Type`` header will be set to ``application/json``. Here's a sample
        request body containing 2 *geocoding* queries:




        .. code-block::

           {
             "batchItems": [
               {
                 "addressLine": "One, Microsoft Way, Redmond, WA 98052",
                 "top": 2
               },
               {
                 "addressLine": "Pike Pl",
                 "adminDistrict": "WA",
                 "locality": "Seattle",
                 "top": 3
               }
             ]
           }

        A *geocoding* batchItem object can accept any of the supported *geocoding* `URI
        parameters </rest/api/maps/search/get-geocoding#uri-parameters>`_.


        The batch should contain at least **1** query.


        ====================
        Batch Response Model
        ====================

        The batch response contains a ``summary`` component that indicates the
        ``totalRequests`` that were part of the original batch request and
        ``successfulRequests`` i.e. queries which were executed successfully. The batch
        response also includes a ``batchItems`` array which contains a response for each
        and every query in the batch request. The ``batchItems`` will contain the results
        in the exact same order the original queries were sent in the batch request.
        Each item is of one of the following types:



        * ``GeocodingResponse` </rest/api/maps/search/get-geocoding#geocodingresponse>`_ -
        If the query completed successfully.



        * `Error` - If the query failed. The response will contain a `code` and a
        `message` in this case.

        :param geocoding_batch_request_body: The list of address geocoding queries/requests to process.
         The list can contain
         a max of 100 queries and must contain at least 1 query. Required.
        :type geocoding_batch_request_body: IO[bytes]
        :keyword client_id: Specifies which account is intended for usage in conjunction with the Azure
         AD
         security model.  It represents a unique ID for the Azure Maps account and can
         be retrieved from the Azure Maps management plane Account API. For more
         information on using Microsoft Entra ID security in Azure Maps, see `Manage
         authentication in Azure Maps </azure/azure-maps/how-to-manage-authentication>`_. Default value
         is None.
        :paramtype client_id: str
        :keyword accept_language: Language in which search results should be returned.

         Please refer to `Supported
         Languages </azure/azure-maps/supported-languages?pivots=service-latest>`_ for
         details. Default value is None.
        :paramtype accept_language: str
        :keyword content_type: Body Parameter content-type. Content type parameter for binary body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: GeocodingBatchResponse. The GeocodingBatchResponse is compatible with MutableMapping
        :rtype: ~azure.maps.search.models.GeocodingBatchResponse
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @distributed_trace
    def get_geocoding_batch(
        self,
        geocoding_batch_request_body: Union[_models.GeocodingBatchRequestBody, JSON, IO[bytes]],
        *,
        client_id: Optional[str] = None,
        accept_language: Optional[str] = None,
        **kwargs: Any
    ) -> _models.GeocodingBatchResponse:
        """Use to send a batch of queries to the `Geocoding </rest/api/maps/search/get-geocoding>`_ API in
        a single request.

        The ``Get Geocoding Batch`` API is an HTTP ``POST`` request that sends batches of
        up to **100** queries to the `Geocoding </rest/api/maps/search/get-geocoding>`_
        API in a single request.

        [!Important]
        By using this feature, you agree to the preview legal terms. For more
        information, see [Preview Supplemental
        Terms](https://azure.microsoft.com/en-us/support/legal/preview-supplemental-terms/).




        ================================
        Submit Synchronous Batch Request
        ================================

        The Synchronous API is recommended for lightweight batch requests. When the
        service receives a request, it will respond as soon as the batch items are
        calculated and there will be no possibility to retrieve the results later. The
        Synchronous API will return a timeout error (a 408 response) if the request
        takes longer than 60 seconds. The number of batch items is limited to **100**
        for this API.

        .. code-block::

           POST
        https://atlas.microsoft.com/geocode:batch?api-version=2023-06-01===========================
        POST Body for Batch Request
        ===========================

        To send the *geocoding* queries you will use a ``POST`` request where the request
        body will contain the ``batchItems`` array in ``json`` format and the
        ``Content-Type`` header will be set to ``application/json``. Here's a sample
        request body containing 2 *geocoding* queries:




        .. code-block::

           {
             "batchItems": [
               {
                 "addressLine": "One, Microsoft Way, Redmond, WA 98052",
                 "top": 2
               },
               {
                 "addressLine": "Pike Pl",
                 "adminDistrict": "WA",
                 "locality": "Seattle",
                 "top": 3
               }
             ]
           }

        A *geocoding* batchItem object can accept any of the supported *geocoding* `URI
        parameters </rest/api/maps/search/get-geocoding#uri-parameters>`_.


        The batch should contain at least **1** query.


        ====================
        Batch Response Model
        ====================

        The batch response contains a ``summary`` component that indicates the
        ``totalRequests`` that were part of the original batch request and
        ``successfulRequests`` i.e. queries which were executed successfully. The batch
        response also includes a ``batchItems`` array which contains a response for each
        and every query in the batch request. The ``batchItems`` will contain the results
        in the exact same order the original queries were sent in the batch request.
        Each item is of one of the following types:



        * ``GeocodingResponse` </rest/api/maps/search/get-geocoding#geocodingresponse>`_ -
        If the query completed successfully.



        * `Error` - If the query failed. The response will contain a `code` and a
        `message` in this case.

        :param geocoding_batch_request_body: The list of address geocoding queries/requests to process.
         The list can contain
         a max of 100 queries and must contain at least 1 query. Is one of the following types:
         GeocodingBatchRequestBody, JSON, IO[bytes] Required.
        :type geocoding_batch_request_body: ~azure.maps.search.models.GeocodingBatchRequestBody or JSON
         or IO[bytes]
        :keyword client_id: Specifies which account is intended for usage in conjunction with the Azure
         AD
         security model.  It represents a unique ID for the Azure Maps account and can
         be retrieved from the Azure Maps management plane Account API. For more
         information on using Microsoft Entra ID security in Azure Maps, see `Manage
         authentication in Azure Maps </azure/azure-maps/how-to-manage-authentication>`_. Default value
         is None.
        :paramtype client_id: str
        :keyword accept_language: Language in which search results should be returned.

         Please refer to `Supported
         Languages </azure/azure-maps/supported-languages?pivots=service-latest>`_ for
         details. Default value is None.
        :paramtype accept_language: str
        :return: GeocodingBatchResponse. The GeocodingBatchResponse is compatible with MutableMapping
        :rtype: ~azure.maps.search.models.GeocodingBatchResponse
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = kwargs.pop("params", {}) or {}

        content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
        cls: ClsType[_models.GeocodingBatchResponse] = kwargs.pop("cls", None)

        content_type = content_type or "application/json"
        _content = None
        if isinstance(geocoding_batch_request_body, (IOBase, bytes)):
            _content = geocoding_batch_request_body
        else:
            _content = json.dumps(geocoding_batch_request_body, cls=SdkJSONEncoder, exclude_readonly=True)  # type: ignore

        _request = build_maps_search_get_geocoding_batch_request(
            client_id=client_id,
            accept_language=accept_language,
            content_type=content_type,
            api_version=self._config.api_version,
            content=_content,
            headers=_headers,
            params=_params,
        )
        path_format_arguments = {
            "endpoint": self._serialize.url("self._config.endpoint", self._config.endpoint, "str", skip_quote=True),
        }
        _request.url = self._client.format_url(_request.url, **path_format_arguments)

        _decompress = kwargs.pop("decompress", True)
        _stream = kwargs.pop("stream", False)
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            if _stream:
                try:
                    response.read()  # Load the body in memory and close the socket
                except (StreamConsumedError, StreamClosedError):
                    pass
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        if _stream:
            deserialized = response.iter_bytes() if _decompress else response.iter_raw()
        else:
            deserialized = _deserialize(_models.GeocodingBatchResponse, response.json())

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore

    @distributed_trace
    def get_polygon(
        self,
        *,
        coordinates: list[float],
        client_id: Optional[str] = None,
        accept_language: Optional[str] = None,
        view: Optional[str] = None,
        result_type: Optional[Union[str, _models.BoundaryResultType]] = None,
        resolution: Optional[Union[str, _models.Resolution]] = None,
        **kwargs: Any
    ) -> _models.Boundary:
        """Use to get polygon data of a geographical area shape such as a city or a country region.

        The ``Get Polygon`` API is an HTTP ``GET`` request that supplies polygon data of a
        geographical area outline such as a city or a country region.

        [!Important]
        By using this feature, you agree to the preview legal terms. For more
        information, see [Preview Supplemental
        Terms](https://azure.microsoft.com/en-us/support/legal/preview-supplemental-terms/).

        .

        :keyword coordinates: A point on the earth specified as a longitude and latitude. Example:
         &coordinates=lon,lat. Required.
        :paramtype coordinates: list[float]
        :keyword client_id: Specifies which account is intended for usage in conjunction with the Azure
         AD
         security model.  It represents a unique ID for the Azure Maps account and can
         be retrieved from the Azure Maps management plane Account API. For more
         information on using Microsoft Entra ID security in Azure Maps, see `Manage
         authentication in Azure Maps </azure/azure-maps/how-to-manage-authentication>`_. Default value
         is None.
        :paramtype client_id: str
        :keyword accept_language: Language in which search results should be returned.

         Please refer to `Supported
         Languages </azure/azure-maps/supported-languages?pivots=service-latest>`_ for
         details. Default value is None.
        :paramtype accept_language: str
        :keyword view: A string that represents an `ISO 3166-1 Alpha-2 region/country
         code <https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2>`_. This will alter
         Geopolitical disputed borders and labels to align with the specified user
         region. By default, the View parameter is set to “Auto” even if you haven’t
         defined it in the request.

         Please refer to `Supported Views <https://aka.ms/AzureMapsLocalizationViews>`_
         for details and to see the available Views. Default value is None.
        :paramtype view: str
        :keyword result_type: The geopolitical concept to return a boundary for. If not specified, the
         default is ``countryRegion`` result type. Known values are: "countryRegion", "adminDistrict",
         "adminDistrict2", "postalCode", "postalCode2", "postalCode3", "postalCode4", "neighborhood",
         and "locality". Default value is None.
        :paramtype result_type: str or ~azure.maps.search.models.BoundaryResultType
        :keyword resolution: Resolution determines the amount of points to send back. If not specified,
         the
         default is medium resolution. Known values are: "small", "medium", "large", and "huge".
         Default value is None.
        :paramtype resolution: str or ~azure.maps.search.models.Resolution
        :return: Boundary. The Boundary is compatible with MutableMapping
        :rtype: ~azure.maps.search.models.Boundary
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls: ClsType[_models.Boundary] = kwargs.pop("cls", None)

        _request = build_maps_search_get_polygon_request(
            coordinates=coordinates,
            client_id=client_id,
            accept_language=accept_language,
            view=view,
            result_type=result_type,
            resolution=resolution,
            api_version=self._config.api_version,
            headers=_headers,
            params=_params,
        )
        path_format_arguments = {
            "endpoint": self._serialize.url("self._config.endpoint", self._config.endpoint, "str", skip_quote=True),
        }
        _request.url = self._client.format_url(_request.url, **path_format_arguments)

        _decompress = kwargs.pop("decompress", True)
        _stream = kwargs.pop("stream", False)
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            if _stream:
                try:
                    response.read()  # Load the body in memory and close the socket
                except (StreamConsumedError, StreamClosedError):
                    pass
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        response_headers = {}
        response_headers["content-type"] = self._deserialize("str", response.headers.get("content-type"))

        if _stream:
            deserialized = response.iter_bytes() if _decompress else response.iter_raw()
        else:
            deserialized = _deserialize(_models.Boundary, response.json())

        if cls:
            return cls(pipeline_response, deserialized, response_headers)  # type: ignore

        return deserialized  # type: ignore

    @distributed_trace
    def get_reverse_geocoding(
        self,
        *,
        coordinates: list[float],
        client_id: Optional[str] = None,
        accept_language: Optional[str] = None,
        result_types: Optional[list[Union[str, _models.ReverseGeocodingResultType]]] = None,
        view: Optional[str] = None,
        **kwargs: Any
    ) -> _models.GeocodingResponse:
        """Use to get a street address and location info from longitude and latitude coordinates.

        The ``Get Reverse Geocoding`` API is an HTTP ``GET`` request used to translate a
        coordinate (example: 37.786505, -122.3862) into a human understandable street
        address. Useful in tracking applications where you receive a GPS feed from the
        device or asset and wish to know the address associated with the coordinates.
        This endpoint will return address information for a given coordinate.

        [!Important]
        By using this feature, you agree to the preview legal terms. For more
        information, see [Preview Supplemental
        Terms](https://azure.microsoft.com/en-us/support/legal/preview-supplemental-terms/).

        .

        :keyword coordinates: The coordinates of the location that you want to reverse geocode.
         Example:
         &coordinates=lon,lat. Required.
        :paramtype coordinates: list[float]
        :keyword client_id: Specifies which account is intended for usage in conjunction with the Azure
         AD
         security model.  It represents a unique ID for the Azure Maps account and can
         be retrieved from the Azure Maps management plane Account API. For more
         information on using Microsoft Entra ID security in Azure Maps, see `Manage
         authentication in Azure Maps </azure/azure-maps/how-to-manage-authentication>`_. Default value
         is None.
        :paramtype client_id: str
        :keyword accept_language: Language in which search results should be returned.

         Please refer to `Supported
         Languages </azure/azure-maps/supported-languages?pivots=service-latest>`_ for
         details. Default value is None.
        :paramtype accept_language: str
        :keyword result_types: Specify entity types that you want in the response. Only the types you
         specify
         will be returned. If the point cannot be mapped to the entity types you
         specify, no location information is returned in the response.
         Default value is all possible entities.
         A comma separated list of entity types selected from the following options.



         * Address
         * Neighborhood
         * PopulatedPlace
         * Postcode1
         * AdminDivision1
         * AdminDivision2
         * CountryRegion

         These entity types are ordered from the most specific entity to the least
         specific entity. When entities of more than one entity type are found, only the
         most specific entity is returned. For example, if you specify Address and
         AdminDistrict1 as entity types and entities were found for both types, only the
         Address entity information is returned in the response. Default value is None.
        :paramtype result_types: list[str or ~azure.maps.search.models.ReverseGeocodingResultType]
        :keyword view: A string that represents an `ISO 3166-1 Alpha-2 region/country
         code <https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2>`_. This will alter
         Geopolitical disputed borders and labels to align with the specified user
         region. By default, the View parameter is set to “Auto” even if you haven’t
         defined it in the request.

         Please refer to `Supported Views <https://aka.ms/AzureMapsLocalizationViews>`_
         for details and to see the available Views. Default value is None.
        :paramtype view: str
        :return: GeocodingResponse. The GeocodingResponse is compatible with MutableMapping
        :rtype: ~azure.maps.search.models.GeocodingResponse
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls: ClsType[_models.GeocodingResponse] = kwargs.pop("cls", None)

        _request = build_maps_search_get_reverse_geocoding_request(
            coordinates=coordinates,
            client_id=client_id,
            accept_language=accept_language,
            result_types=result_types,
            view=view,
            api_version=self._config.api_version,
            headers=_headers,
            params=_params,
        )
        path_format_arguments = {
            "endpoint": self._serialize.url("self._config.endpoint", self._config.endpoint, "str", skip_quote=True),
        }
        _request.url = self._client.format_url(_request.url, **path_format_arguments)

        _decompress = kwargs.pop("decompress", True)
        _stream = kwargs.pop("stream", False)
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            if _stream:
                try:
                    response.read()  # Load the body in memory and close the socket
                except (StreamConsumedError, StreamClosedError):
                    pass
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        response_headers = {}
        response_headers["content-type"] = self._deserialize("str", response.headers.get("content-type"))

        if _stream:
            deserialized = response.iter_bytes() if _decompress else response.iter_raw()
        else:
            deserialized = _deserialize(_models.GeocodingResponse, response.json())

        if cls:
            return cls(pipeline_response, deserialized, response_headers)  # type: ignore

        return deserialized  # type: ignore

    @overload
    def get_reverse_geocoding_batch(
        self,
        reverse_geocoding_batch_request_body: _models.ReverseGeocodingBatchRequestBody,
        *,
        client_id: Optional[str] = None,
        accept_language: Optional[str] = None,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> _models.GeocodingBatchResponse:
        """Use to send a batch of queries to the `Reverse Geocoding
        </rest/api/maps/search/get-reverse-geocoding>`_ API in a single request.

        The ``Get Reverse Geocoding Batch`` API is an HTTP ``POST`` request that sends
        batches of up to **100** queries to `Reverse
        Geocoding </rest/api/maps/search/get-reverse-geocoding>`_ API using a single
        request.

        [!Important]
        By using this feature, you agree to the preview legal terms. For more
        information, see [Preview Supplemental
        Terms](https://azure.microsoft.com/en-us/support/legal/preview-supplemental-terms/).




        ================================
        Submit Synchronous Batch Request
        ================================

        The Synchronous API is recommended for lightweight batch requests. When the
        service receives a request, it will respond as soon as the batch items are
        calculated and there will be no possibility to retrieve the results later. The
        Synchronous API will return a timeout error (a 408 response) if the request
        takes longer than 60 seconds. The number of batch items is limited to **100**
        for this API.

        .. code-block::

           POST
        https://atlas.microsoft.com/reverseGeocode:batch?api-version=2023-06-01===========================
        POST Body for Batch Request
        ===========================

        To send the *reverse geocoding* queries you will use a ``POST`` request where the
        request body will contain the ``batchItems`` array in ``json`` format and the
        ``Content-Type`` header will be set to ``application/json``. Here's a sample
        request body containing 2 *reverse geocoding* queries:




        .. code-block::

           {
             "batchItems": [
               {
                 "coordinates": [-122.128275, 47.639429],
                 "resultTypes": ["Address", "PopulatedPlace"]
               },
               {
                 "coordinates": [-122.341979399674, 47.6095253501216]
               }
             ]
           }

        A *reverse geocoding* batchItem object can accept any of the supported *reverse
        geocoding* `URI
        parameters </rest/api/maps/search/get-reverse-geocoding#uri-parameters>`_.


        The batch should contain at least **1** query.


        ====================
        Batch Response Model
        ====================

        The batch response contains a ``summary`` component that indicates the
        ``totalRequests`` that were part of the original batch request and
        ``successfulRequests`` i.e. queries which were executed successfully. The batch
        response also includes a ``batchItems`` array which contains a response for each
        and every query in the batch request. The ``batchItems`` will contain the results
        in the exact same order the original queries were sent in the batch request.
        Each item is of one of the following types:



        * ``GeocodingResponse` </rest/api/maps/search/get-reverse-geocoding#geocodingresponse>`_

        * If the query completed successfully.

        * `Error` - If the query failed. The response will contain a `code` and a
        `message` in this case.

        :param reverse_geocoding_batch_request_body: The list of reverse geocoding queries/requests to
         process. The list can contain
         a max of 100 queries and must contain at least 1 query. Required.
        :type reverse_geocoding_batch_request_body:
         ~azure.maps.search.models.ReverseGeocodingBatchRequestBody
        :keyword client_id: Specifies which account is intended for usage in conjunction with the Azure
         AD
         security model.  It represents a unique ID for the Azure Maps account and can
         be retrieved from the Azure Maps management plane Account API. For more
         information on using Microsoft Entra ID security in Azure Maps, see `Manage
         authentication in Azure Maps </azure/azure-maps/how-to-manage-authentication>`_. Default value
         is None.
        :paramtype client_id: str
        :keyword accept_language: Language in which search results should be returned.

         Please refer to `Supported
         Languages </azure/azure-maps/supported-languages?pivots=service-latest>`_ for
         details. Default value is None.
        :paramtype accept_language: str
        :keyword content_type: Body Parameter content-type. Content type parameter for JSON body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: GeocodingBatchResponse. The GeocodingBatchResponse is compatible with MutableMapping
        :rtype: ~azure.maps.search.models.GeocodingBatchResponse
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @overload
    def get_reverse_geocoding_batch(
        self,
        reverse_geocoding_batch_request_body: JSON,
        *,
        client_id: Optional[str] = None,
        accept_language: Optional[str] = None,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> _models.GeocodingBatchResponse:
        """Use to send a batch of queries to the `Reverse Geocoding
        </rest/api/maps/search/get-reverse-geocoding>`_ API in a single request.

        The ``Get Reverse Geocoding Batch`` API is an HTTP ``POST`` request that sends
        batches of up to **100** queries to `Reverse
        Geocoding </rest/api/maps/search/get-reverse-geocoding>`_ API using a single
        request.

        [!Important]
        By using this feature, you agree to the preview legal terms. For more
        information, see [Preview Supplemental
        Terms](https://azure.microsoft.com/en-us/support/legal/preview-supplemental-terms/).




        ================================
        Submit Synchronous Batch Request
        ================================

        The Synchronous API is recommended for lightweight batch requests. When the
        service receives a request, it will respond as soon as the batch items are
        calculated and there will be no possibility to retrieve the results later. The
        Synchronous API will return a timeout error (a 408 response) if the request
        takes longer than 60 seconds. The number of batch items is limited to **100**
        for this API.

        .. code-block::

           POST
        https://atlas.microsoft.com/reverseGeocode:batch?api-version=2023-06-01===========================
        POST Body for Batch Request
        ===========================

        To send the *reverse geocoding* queries you will use a ``POST`` request where the
        request body will contain the ``batchItems`` array in ``json`` format and the
        ``Content-Type`` header will be set to ``application/json``. Here's a sample
        request body containing 2 *reverse geocoding* queries:




        .. code-block::

           {
             "batchItems": [
               {
                 "coordinates": [-122.128275, 47.639429],
                 "resultTypes": ["Address", "PopulatedPlace"]
               },
               {
                 "coordinates": [-122.341979399674, 47.6095253501216]
               }
             ]
           }

        A *reverse geocoding* batchItem object can accept any of the supported *reverse
        geocoding* `URI
        parameters </rest/api/maps/search/get-reverse-geocoding#uri-parameters>`_.


        The batch should contain at least **1** query.


        ====================
        Batch Response Model
        ====================

        The batch response contains a ``summary`` component that indicates the
        ``totalRequests`` that were part of the original batch request and
        ``successfulRequests`` i.e. queries which were executed successfully. The batch
        response also includes a ``batchItems`` array which contains a response for each
        and every query in the batch request. The ``batchItems`` will contain the results
        in the exact same order the original queries were sent in the batch request.
        Each item is of one of the following types:



        * ``GeocodingResponse` </rest/api/maps/search/get-reverse-geocoding#geocodingresponse>`_

        * If the query completed successfully.

        * `Error` - If the query failed. The response will contain a `code` and a
        `message` in this case.

        :param reverse_geocoding_batch_request_body: The list of reverse geocoding queries/requests to
         process. The list can contain
         a max of 100 queries and must contain at least 1 query. Required.
        :type reverse_geocoding_batch_request_body: JSON
        :keyword client_id: Specifies which account is intended for usage in conjunction with the Azure
         AD
         security model.  It represents a unique ID for the Azure Maps account and can
         be retrieved from the Azure Maps management plane Account API. For more
         information on using Microsoft Entra ID security in Azure Maps, see `Manage
         authentication in Azure Maps </azure/azure-maps/how-to-manage-authentication>`_. Default value
         is None.
        :paramtype client_id: str
        :keyword accept_language: Language in which search results should be returned.

         Please refer to `Supported
         Languages </azure/azure-maps/supported-languages?pivots=service-latest>`_ for
         details. Default value is None.
        :paramtype accept_language: str
        :keyword content_type: Body Parameter content-type. Content type parameter for JSON body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: GeocodingBatchResponse. The GeocodingBatchResponse is compatible with MutableMapping
        :rtype: ~azure.maps.search.models.GeocodingBatchResponse
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @overload
    def get_reverse_geocoding_batch(
        self,
        reverse_geocoding_batch_request_body: IO[bytes],
        *,
        client_id: Optional[str] = None,
        accept_language: Optional[str] = None,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> _models.GeocodingBatchResponse:
        """Use to send a batch of queries to the `Reverse Geocoding
        </rest/api/maps/search/get-reverse-geocoding>`_ API in a single request.

        The ``Get Reverse Geocoding Batch`` API is an HTTP ``POST`` request that sends
        batches of up to **100** queries to `Reverse
        Geocoding </rest/api/maps/search/get-reverse-geocoding>`_ API using a single
        request.

        [!Important]
        By using this feature, you agree to the preview legal terms. For more
        information, see [Preview Supplemental
        Terms](https://azure.microsoft.com/en-us/support/legal/preview-supplemental-terms/).




        ================================
        Submit Synchronous Batch Request
        ================================

        The Synchronous API is recommended for lightweight batch requests. When the
        service receives a request, it will respond as soon as the batch items are
        calculated and there will be no possibility to retrieve the results later. The
        Synchronous API will return a timeout error (a 408 response) if the request
        takes longer than 60 seconds. The number of batch items is limited to **100**
        for this API.

        .. code-block::

           POST
        https://atlas.microsoft.com/reverseGeocode:batch?api-version=2023-06-01===========================
        POST Body for Batch Request
        ===========================

        To send the *reverse geocoding* queries you will use a ``POST`` request where the
        request body will contain the ``batchItems`` array in ``json`` format and the
        ``Content-Type`` header will be set to ``application/json``. Here's a sample
        request body containing 2 *reverse geocoding* queries:




        .. code-block::

           {
             "batchItems": [
               {
                 "coordinates": [-122.128275, 47.639429],
                 "resultTypes": ["Address", "PopulatedPlace"]
               },
               {
                 "coordinates": [-122.341979399674, 47.6095253501216]
               }
             ]
           }

        A *reverse geocoding* batchItem object can accept any of the supported *reverse
        geocoding* `URI
        parameters </rest/api/maps/search/get-reverse-geocoding#uri-parameters>`_.


        The batch should contain at least **1** query.


        ====================
        Batch Response Model
        ====================

        The batch response contains a ``summary`` component that indicates the
        ``totalRequests`` that were part of the original batch request and
        ``successfulRequests`` i.e. queries which were executed successfully. The batch
        response also includes a ``batchItems`` array which contains a response for each
        and every query in the batch request. The ``batchItems`` will contain the results
        in the exact same order the original queries were sent in the batch request.
        Each item is of one of the following types:



        * ``GeocodingResponse` </rest/api/maps/search/get-reverse-geocoding#geocodingresponse>`_

        * If the query completed successfully.

        * `Error` - If the query failed. The response will contain a `code` and a
        `message` in this case.

        :param reverse_geocoding_batch_request_body: The list of reverse geocoding queries/requests to
         process. The list can contain
         a max of 100 queries and must contain at least 1 query. Required.
        :type reverse_geocoding_batch_request_body: IO[bytes]
        :keyword client_id: Specifies which account is intended for usage in conjunction with the Azure
         AD
         security model.  It represents a unique ID for the Azure Maps account and can
         be retrieved from the Azure Maps management plane Account API. For more
         information on using Microsoft Entra ID security in Azure Maps, see `Manage
         authentication in Azure Maps </azure/azure-maps/how-to-manage-authentication>`_. Default value
         is None.
        :paramtype client_id: str
        :keyword accept_language: Language in which search results should be returned.

         Please refer to `Supported
         Languages </azure/azure-maps/supported-languages?pivots=service-latest>`_ for
         details. Default value is None.
        :paramtype accept_language: str
        :keyword content_type: Body Parameter content-type. Content type parameter for binary body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: GeocodingBatchResponse. The GeocodingBatchResponse is compatible with MutableMapping
        :rtype: ~azure.maps.search.models.GeocodingBatchResponse
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @distributed_trace
    def get_reverse_geocoding_batch(
        self,
        reverse_geocoding_batch_request_body: Union[_models.ReverseGeocodingBatchRequestBody, JSON, IO[bytes]],
        *,
        client_id: Optional[str] = None,
        accept_language: Optional[str] = None,
        **kwargs: Any
    ) -> _models.GeocodingBatchResponse:
        """Use to send a batch of queries to the `Reverse Geocoding
        </rest/api/maps/search/get-reverse-geocoding>`_ API in a single request.

        The ``Get Reverse Geocoding Batch`` API is an HTTP ``POST`` request that sends
        batches of up to **100** queries to `Reverse
        Geocoding </rest/api/maps/search/get-reverse-geocoding>`_ API using a single
        request.

        [!Important]
        By using this feature, you agree to the preview legal terms. For more
        information, see [Preview Supplemental
        Terms](https://azure.microsoft.com/en-us/support/legal/preview-supplemental-terms/).




        ================================
        Submit Synchronous Batch Request
        ================================

        The Synchronous API is recommended for lightweight batch requests. When the
        service receives a request, it will respond as soon as the batch items are
        calculated and there will be no possibility to retrieve the results later. The
        Synchronous API will return a timeout error (a 408 response) if the request
        takes longer than 60 seconds. The number of batch items is limited to **100**
        for this API.

        .. code-block::

           POST
        https://atlas.microsoft.com/reverseGeocode:batch?api-version=2023-06-01===========================
        POST Body for Batch Request
        ===========================

        To send the *reverse geocoding* queries you will use a ``POST`` request where the
        request body will contain the ``batchItems`` array in ``json`` format and the
        ``Content-Type`` header will be set to ``application/json``. Here's a sample
        request body containing 2 *reverse geocoding* queries:




        .. code-block::

           {
             "batchItems": [
               {
                 "coordinates": [-122.128275, 47.639429],
                 "resultTypes": ["Address", "PopulatedPlace"]
               },
               {
                 "coordinates": [-122.341979399674, 47.6095253501216]
               }
             ]
           }

        A *reverse geocoding* batchItem object can accept any of the supported *reverse
        geocoding* `URI
        parameters </rest/api/maps/search/get-reverse-geocoding#uri-parameters>`_.


        The batch should contain at least **1** query.


        ====================
        Batch Response Model
        ====================

        The batch response contains a ``summary`` component that indicates the
        ``totalRequests`` that were part of the original batch request and
        ``successfulRequests`` i.e. queries which were executed successfully. The batch
        response also includes a ``batchItems`` array which contains a response for each
        and every query in the batch request. The ``batchItems`` will contain the results
        in the exact same order the original queries were sent in the batch request.
        Each item is of one of the following types:



        * ``GeocodingResponse` </rest/api/maps/search/get-reverse-geocoding#geocodingresponse>`_

        * If the query completed successfully.

        * `Error` - If the query failed. The response will contain a `code` and a
        `message` in this case.

        :param reverse_geocoding_batch_request_body: The list of reverse geocoding queries/requests to
         process. The list can contain
         a max of 100 queries and must contain at least 1 query. Is one of the following types:
         ReverseGeocodingBatchRequestBody, JSON, IO[bytes] Required.
        :type reverse_geocoding_batch_request_body:
         ~azure.maps.search.models.ReverseGeocodingBatchRequestBody or JSON or IO[bytes]
        :keyword client_id: Specifies which account is intended for usage in conjunction with the Azure
         AD
         security model.  It represents a unique ID for the Azure Maps account and can
         be retrieved from the Azure Maps management plane Account API. For more
         information on using Microsoft Entra ID security in Azure Maps, see `Manage
         authentication in Azure Maps </azure/azure-maps/how-to-manage-authentication>`_. Default value
         is None.
        :paramtype client_id: str
        :keyword accept_language: Language in which search results should be returned.

         Please refer to `Supported
         Languages </azure/azure-maps/supported-languages?pivots=service-latest>`_ for
         details. Default value is None.
        :paramtype accept_language: str
        :return: GeocodingBatchResponse. The GeocodingBatchResponse is compatible with MutableMapping
        :rtype: ~azure.maps.search.models.GeocodingBatchResponse
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = kwargs.pop("params", {}) or {}

        content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
        cls: ClsType[_models.GeocodingBatchResponse] = kwargs.pop("cls", None)

        content_type = content_type or "application/json"
        _content = None
        if isinstance(reverse_geocoding_batch_request_body, (IOBase, bytes)):
            _content = reverse_geocoding_batch_request_body
        else:
            _content = json.dumps(reverse_geocoding_batch_request_body, cls=SdkJSONEncoder, exclude_readonly=True)  # type: ignore

        _request = build_maps_search_get_reverse_geocoding_batch_request(
            client_id=client_id,
            accept_language=accept_language,
            content_type=content_type,
            api_version=self._config.api_version,
            content=_content,
            headers=_headers,
            params=_params,
        )
        path_format_arguments = {
            "endpoint": self._serialize.url("self._config.endpoint", self._config.endpoint, "str", skip_quote=True),
        }
        _request.url = self._client.format_url(_request.url, **path_format_arguments)

        _decompress = kwargs.pop("decompress", True)
        _stream = kwargs.pop("stream", False)
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            if _stream:
                try:
                    response.read()  # Load the body in memory and close the socket
                except (StreamConsumedError, StreamClosedError):
                    pass
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        if _stream:
            deserialized = response.iter_bytes() if _decompress else response.iter_raw()
        else:
            deserialized = _deserialize(_models.GeocodingBatchResponse, response.json())

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore

    @distributed_trace
    @api_version_validation(
        method_added_on="2025-06-01-preview",
        params_added_on={
            "2025-06-01-preview": [
                "api_version",
                "client_id",
                "accept_language",
                "query",
                "coordinates",
                "bbox",
                "top",
                "result_type_groups",
                "result_types",
                "view",
                "country_region",
                "accept",
            ]
        },
        api_versions_list=["2025-06-01-preview"],
    )
    def get_geocode_autocomplete(
        self,
        *,
        query: str,
        client_id: Optional[str] = None,
        accept_language: Optional[str] = None,
        coordinates: Optional[list[float]] = None,
        bbox: Optional[list[float]] = None,
        top: Optional[int] = None,
        result_type_groups: Optional[list[Union[str, _models.AutocompleteResultTypeGroups]]] = None,
        result_types: Optional[list[Union[str, _models.AutocompleteResultType]]] = None,
        view: Optional[str] = None,
        country_region: Optional[str] = None,
        **kwargs: Any
    ) -> _models.AutocompleteResponse:
        """Use to get ranked list of suggested entities based on a user's location and a partial query.

        Given a request with a user’s location and a partial query that serves as the
        prefix of a full query string (referred to as a query prefix), the Azure Maps
        Autocomplete API returns a list of suggested entities that the user is most
        likely searching for. These entities are ranked from most to least likely.

        [!Important]
        By using this feature, you agree to the preview legal terms. For more
        information, see [Preview Supplemental
        Terms](https://azure.microsoft.com/en-us/support/legal/preview-supplemental-terms/).

        .

        :keyword query: Required. The user's query prefix.

         Example: "1 Micro" or "Muir Woods". Required.
        :paramtype query: str
        :keyword client_id: Specifies which account is intended for usage in conjunction with the Azure
         AD
         security model.  It represents a unique ID for the Azure Maps account and can
         be retrieved from the Azure Maps management plane Account API. For more
         information on using Microsoft Entra ID security in Azure Maps, see `Manage
         authentication in Azure Maps </azure/azure-maps/how-to-manage-authentication>`_. Default value
         is None.
        :paramtype client_id: str
        :keyword accept_language: Language in which search results should be returned.

         Please refer to `Supported
         Languages </azure/azure-maps/supported-languages?pivots=service-latest>`_ for
         details. Default value is None.
        :paramtype accept_language: str
        :keyword coordinates: Required when ``bbox`` is not provided. A point on the earth specified as
         a
         longitude and latitude. When you specify this parameter, the user’s location is
         taken into account and the results returned may be more relevant to the user.
         Example: &coordinates=lon,lat

         **Note:** ``coordinates`` becomes a secondary signal if ``bbox`` is provided. Default value is
         None.
        :paramtype coordinates: list[float]
        :keyword bbox: Required when ``coordinates`` is not provided. A rectangular area on the earth
         defined as a bounding box object. The sides of the rectangle are defined by
         longitude and latitude values. When you specify this parameter, the
         geographical area is taken into account when computing the results of a
         location query.

         Example: lon1,lat1,lon2,lat2.

         Minimum size: approximately 0.00001 degrees (~0.01 meters).

         Maximum size: up to the full global extent (-180,-90 to 180,90). Default value is None.
        :paramtype bbox: list[float]
        :keyword top: Maximum number of responses that will be returned. Default: 5, minimum: 1 and
         maximum: 20. Default value is None.
        :paramtype top: int
        :keyword result_type_groups: A comma separated list of returned entity type groups. The
         possible values are



         * Address
         * Place. Default value is None.
        :paramtype result_type_groups: list[str or
         ~azure.maps.search.models.AutocompleteResultTypeGroups]
        :keyword result_types: A comma separated list of returned entity types.
         When type group is set to Address, the supported types are:



         * Address
         * RoadBlock

         All other types belong to the Place type group. These may include entities such
         as AdminDivision1, Neighborhood, PopulatedPlace, and more.
         Default value is all possible entity types. Default value is None.
        :paramtype result_types: list[str or ~azure.maps.search.models.AutocompleteResultType]
        :keyword view: A string that represents an `ISO 3166-1 Alpha-2 region/country
         code <https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2>`_. This will alter
         Geopolitical disputed borders and labels to align with the specified user
         region. By default, the View parameter is set to “Auto” even if you haven’t
         defined it in the request.

         Please refer to `Supported Views <https://aka.ms/AzureMapsLocalizationViews>`_
         for details and to see the available Views. Default value is None.
        :paramtype view: str
        :keyword country_region: Signal for the autocomplete result to an `ISO 3166-1 Alpha-2
         region/country
         code <https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2>`_ that is specified e.g.
         FR. Only results in the specified country/region will be returned. Default value is None.
        :paramtype country_region: str
        :return: AutocompleteResponse. The AutocompleteResponse is compatible with MutableMapping
        :rtype: ~azure.maps.search.models.AutocompleteResponse
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls: ClsType[_models.AutocompleteResponse] = kwargs.pop("cls", None)

        _request = build_maps_search_get_geocode_autocomplete_request(
            query=query,
            client_id=client_id,
            accept_language=accept_language,
            coordinates=coordinates,
            bbox=bbox,
            top=top,
            result_type_groups=result_type_groups,
            result_types=result_types,
            view=view,
            country_region=country_region,
            api_version=self._config.api_version,
            headers=_headers,
            params=_params,
        )
        path_format_arguments = {
            "endpoint": self._serialize.url("self._config.endpoint", self._config.endpoint, "str", skip_quote=True),
        }
        _request.url = self._client.format_url(_request.url, **path_format_arguments)

        _decompress = kwargs.pop("decompress", True)
        _stream = kwargs.pop("stream", False)
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            if _stream:
                try:
                    response.read()  # Load the body in memory and close the socket
                except (StreamConsumedError, StreamClosedError):
                    pass
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        response_headers = {}
        response_headers["content-type"] = self._deserialize("str", response.headers.get("content-type"))

        if _stream:
            deserialized = response.iter_bytes() if _decompress else response.iter_raw()
        else:
            deserialized = _deserialize(_models.AutocompleteResponse, response.json())

        if cls:
            return cls(pipeline_response, deserialized, response_headers)  # type: ignore

        return deserialized  # type: ignore
