# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class BasinId(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Basin identifier for tropical storms."""

    AL = "AL"
    """**The Atlantic Ocean**. Crucial for tracking hurricanes that affect the Americas and the
    Caribbean. It is one of the most active regions for tropical storms."""
    CP = "CP"
    """**The Central Pacific Ocean**. This basin is used for storms affecting Hawaii and surrounding
    areas."""
    EP = "EP"
    """**The Eastern Pacific Ocean**. This basin tracks storms impacting the western coast of the
    Americas, including Mexico and Central America. It is adjacent to the Central Pacific basin."""
    NI = "NI"
    """**The North Indian Ocean**. This basin covers storms impacting South Asia, including countries
    like India and Bangladesh, which are frequently affected by cyclones."""
    NP = "NP"
    """**The Northwest Pacific Ocean**. This basin is important for tracking typhoons that affect East
    Asia, including countries like China, Japan, and the Philippines. It is the most active
    tropical storm regions globally."""
    SI = "SI"
    """**The South Indian Ocean**. This basin, positioned south of the equator, covers cyclones
    impacting Madagascar, Africa, and surrounding regions."""
    SP = "SP"
    """**The South Pacific Ocean**. This basin, positioned south of the equator, is relevant for
    cyclones affecting Australia and the South Pacific islands."""


class DailyDuration(int, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Duration in days for which the forecast is requested."""

    ONE_DAY = 1
    """1 day."""
    TWO_DAYS = 2
    """2 days."""
    THREE_DAYS = 3
    """3 days."""
    FOUR_DAYS = 4
    """4 days."""
    FIVE_DAYS = 5
    """5 days."""
    SIX_DAYS = 6
    """6 days."""
    SEVEN_DAYS = 7
    """7 days."""


class DayQuarter(int, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Divides the day into four 6-hour quarters. Valid values are 0-3:<ul><li>0: Morning (7am -
    1pm)</li><li>1: Afternoon (1pm - 7pm)</li><li>2: Evening (7pm - 1am)</li><li>3: Overnight (1am
    - 7am)</li></ul>.
    """

    FIRST_QUARTER = 0
    """7:00 am - 1:00 pm / 7:00- 13:00."""
    SECOND_QUARTER = 1
    """1:00 pm - 7:00 pm/ 13:00- 19:00."""
    THIRD_QUARTER = 2
    """7:00 pm - 1:00 am/ 19:00 - 01:00."""
    FORTH_QUARTER = 3
    """1:00 am - 7:00 am/ 01:00 - 07:00."""


class DominantPollutant(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Identifies the pollutant with the highest concentration."""

    CARBON_MONOXIDE = "Carbon Monoxide"
    """Carbon monoxide (CO) is a colorless, odorless, and tasteless but highly toxic gas produced by
    the incomplete combustion of carbon-containing fuels. Common sources include vehicle exhaust,
    gas stoves, furnaces, and wood fires."""
    NITROGEN_DIOXIDE = "Nitrogen Dioxide"
    """Nitrogen dioxide (NO2) is a significant atmospheric pollutant. It is regulated and subject to
    recommended limit guidelines set by the World Health Organization (WHO)."""
    OZONE = "Ozone"
    """Ozone (O3) is a key component of photochemical smog, the brown, harmful haze that envelops many
    large cities, resulting from a photochemical reaction between sunlight and certain specific
    pollutants."""
    PARTICULATE_MATTER2_5 = "Particulate Matter 2.5"
    """Particulate matter 2.5 (PM2.5) refers to fine particles with diameters that are generally 2.5
    micrometers and smaller. These particles are more than 100 times thinner than a human hair and
    can remain suspended in the air for extended periods."""
    PARTICULATE_MATTER10 = "Particulate Matter 10"
    """Particulate matter 10 (PM10) refers to particles with diameters that are generally 10
    micrometers and smaller. These particles can include dust, pollen, soot, smoke, and liquid
    droplets."""
    SULFUR_DIOXIDE = "Sulfur Dioxide"
    """Sulfur dioxide (SO2) is a heavy, colorless inorganic gas with a pungent, irritating odor. It is
    mainly produced by burning fossil fuels at power plants and industrial facilities, but it can
    also be emitted from natural sources such as volcanoes."""


class GeoJsonObjectType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies the ``GeoJSON`` type. Must be one of the nine valid GeoJSON object types - Point,
    MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection, Feature and
    FeatureCollection.
    """

    GEO_JSON_POINT = "Point"
    """``GeoJSON Point`` geometry."""
    GEO_JSON_MULTI_POINT = "MultiPoint"
    """``GeoJSON MultiPoint`` geometry."""
    GEO_JSON_LINE_STRING = "LineString"
    """``GeoJSON LineString`` geometry."""
    GEO_JSON_MULTI_LINE_STRING = "MultiLineString"
    """``GeoJSON MultiLineString`` geometry."""
    GEO_JSON_POLYGON = "Polygon"
    """``GeoJSON Polygon`` geometry."""
    GEO_JSON_MULTI_POLYGON = "MultiPolygon"
    """``GeoJSON MultiPolygon`` geometry."""
    GEO_JSON_GEOMETRY_COLLECTION = "GeometryCollection"
    """``GeoJSON GeometryCollection`` geometry."""
    GEO_JSON_FEATURE = "Feature"
    """``GeoJSON Feature`` object."""
    GEO_JSON_FEATURE_COLLECTION = "FeatureCollection"
    """``GeoJSON FeatureCollection`` object."""


class HazardIndex(int, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The aggregated severity/hazard index for each waypoint, which can be used to
    color-code route segments to indicate driver safety.

    * `0` - No hazard.
    * `1` - Be informed, be aware.
    * `2` - Pay attention, be prepared.
    * `3` - Take action.
    * `4` - Life threatening, emergency.
    """

    NO_HAZARD = 0
    """No hazard."""
    INFORMED = 1
    """Be informed."""
    PAY_ATTENTION = 2
    """Pay attention."""
    TAKE_ACTION = 3
    """Take action."""
    EMERGENCY = 4
    """Emergency."""


class HourlyDuration(int, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Duration in hours for which the forecast is requested."""

    ONE_HOUR = 1
    """1 Hours."""
    TWELVE_HOURS = 12
    """12 Hours."""
    TWENTY_FOUR_HOURS = 24
    """24 Hours."""
    FORTY_EIGHT_HOURS = 48
    """48 Hours."""
    SEVENTY_TWO_HOURS = 72
    """72 Hours."""
    NINETY_SIX_HOURS = 96
    """96 Hours."""


class IconCode(int, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Numeric value representing an image that corresponds to the current weather condition described
    by the ``Phrase`` property. For more information, see `Weather services in Azure Maps
    </azure/azure-maps/weather-services-concepts#weather-icons>`_. May be NULL.
    """

    SUNNY = 1
    """Sunny."""
    MOSTLY_SUNNY = 2
    """Mostly Sunny."""
    PARTLY_SUNNY = 3
    """Partly Sunny."""
    INTERMITTENT_CLOUDS = 4
    """Intermittent Clouds."""
    HAZY_SUNSHINE = 5
    """Hazy Sunshine."""
    MOSTLY_CLOUDY = 6
    """Mostly Cloudy."""
    CLOUDY = 7
    """Cloudy."""
    DREARY = 8
    """Dreary (Overcast)."""
    FOG = 11
    """Fog."""
    SHOWERS = 12
    """Showers."""
    MOSTLY_CLOUDY_WITH_SHOWERS = 13
    """Mostly Cloudy with Showers."""
    PARTLY_SUNNY_WITH_SHOWERS = 14
    """Partly Sunny with Showers."""
    THUNDERSTORMS = 15
    """Thunderstorms."""
    MOSTLY_CLOUDY_WITH_THUNDERSTORMS = 16
    """Mostly Cloudy with Thunderstorms."""
    PARTLY_SUNNY_WITH_THUNDERSTORMS = 17
    """Partly Sunny with Thunderstorms."""
    RAIN = 18
    """Rain."""
    FLURRIES = 19
    """Flurries."""
    MOSTLY_CLOUDY_WITH_FLURRIES = 20
    """Mostly Cloudy with Flurries."""
    PARTLY_SUNNY_WITH_FLURRIES = 21
    """Partly Sunny with Flurries."""
    SNOW = 22
    """Snow."""
    MOSTLY_CLOUDY_WITH_SNOW = 23
    """Mostly Cloudy with Snow."""
    ICE = 24
    """Ice."""
    SLEET = 25
    """Sleet."""
    FREEZING_RAIN = 26
    """Freezing Rain."""
    RAIN_AND_SNOW = 29
    """Rain and Snow."""
    HOT = 30
    """Hot."""
    COLD = 31
    """Cold."""
    WINDY = 32
    """Windy."""
    CLEAR = 33
    """Clear."""
    MOSTLY_CLEAR = 34
    """Mostly Clear."""
    PARTLY_CLOUDY = 35
    """Partly Cloudy."""
    INTERMITTENT_CLOUDS_NIGHT = 36
    """Intermittent Clouds (Night)."""
    HAZY_MOONLIGHT = 37
    """Hazy Moonlight."""
    MOSTLY_CLOUDY_NIGHT = 38
    """Mostly Cloudy (Night)."""
    PARTLY_CLOUDY_WITH_SHOWERS = 39
    """Partly Cloudy with Showers."""
    MOSTLY_CLOUDY_WITH_SHOWERS_NIGHT = 40
    """Mostly Cloudy with Showers (Night)."""
    PARTLY_CLOUDY_WITH_THUNDERSTORMS = 41
    """Partly Cloudy with Thunderstorms."""
    MOSTLY_CLOUDY_WITH_THUNDERSTORMS_NIGHT = 42
    """Mostly Cloudy with Thunderstorms (Night)."""
    MOSTLY_CLOUDY_WITH_FLURRIES_NIGHT = 43
    """Mostly Cloudy with Flurries (Night)."""
    MOSTLY_CLOUDY_WITH_SNOW_NIGHT = 44
    """Mostly Cloudy with Snow (Night)."""


class JsonFormat(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Desired response format."""

    JSON = "json"
    """`The JavaScript Object Notation Data Interchange Format
    <https://tools.ietf.org/html/rfc8259>`_."""


class LatestStatusKeyword(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """A predefined list of eight keywords used to describe the current status of a severe weather
    alert.
    """

    CANCEL = "Cancel"
    """Indicates that the alert has been canceled before its originally scheduled expiration time."""
    CONTINUE = "Continue"
    """Indicates that the alert has been updated since its initial issuance, but no changes were made
    to ``alertDetails``, ``startTime``, ``endTime``, or ``class``."""
    CORRECT = "Correct"
    """Indicates that the alert has been modified to correct a previous error."""
    EXPIRE = "Expire"
    """Indicates that the alert has expired and is no longer active."""
    EXTEND = "Extend"
    """Indicates that the alert has been extended in duration, area, or both since its initial
    issuance."""
    NEW = "New"
    """The status of an alert when first issued."""
    UPDATE = "Update"
    """Indicates that the alert has been modified since its initial issuance."""
    UPGRADE = "Upgrade"
    """Indicates that the alert has been elevated to a higher class or category since first issued."""


class PollutantType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies the six types of pollutants tracked by the Azure Maps Weather service."""

    CO = "CO"
    """Carbon monoxide."""
    NO2 = "NO2"
    """Nitrogen dioxide."""
    O3 = "O3"
    """Ozone."""
    PM2_5 = "PM2.5"
    """Particulate matter 2.5."""
    PM10 = "PM10"
    """Particulate matter 10."""
    SO2 = "SO2"
    """Sulfur dioxide."""


class PrecipitationType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies the type of precipitation. Valid values are Rain, Snow, Ice, or Mix. This property is
    included in the response when dBZ is greater than zero.
    """

    ICE = "Ice"
    """Ice."""
    MIX = "Mix"
    """Mix."""
    RAIN = "Rain"
    """Rain."""
    SNOW = "Snow"
    """Snow."""


class UnitType(int, Enum, metaclass=CaseInsensitiveEnumMeta):
    """An integer representing the unit type.  For example, 17 for Celsius, 18 for Fahrenheit. Can be
    used for unit translation. For a complete list, see `Weather services in Azure Maps
    </azure/azure-maps/weather-services-concepts#unit-types>`_.
    """

    FEET = 0
    """feet."""
    INCHES = 1
    """inches."""
    MILES = 2
    """miles."""
    MILLIMETER = 3
    """millimeter."""
    CENTIMETER = 4
    """centimeter."""
    METER = 5
    """meter."""
    KILOMETER = 6
    """kilometer."""
    KILOMETERS_PER_HOUR = 7
    """kilometersPerHour."""
    KNOTS = 8
    """knots."""
    MILES_PER_HOUR = 9
    """milesPerHour."""
    METERS_PER_SECOND = 10
    """metersPerSecond."""
    HECTO_PASCALS = 11
    """hectoPascals."""
    INCHES_OF_MERCURY = 12
    """inchesOfMercury."""
    KILO_PASCALS = 13
    """kiloPascals."""
    MILLIBARS = 14
    """millibars."""
    MILLIMETERS_OF_MERCURY = 15
    """millimetersOfMercury."""
    POUNDS_PER_SQUARE_INCH = 16
    """poundsPerSquareInch."""
    CELSIUS = 17
    """Celsius."""
    FAHRENHEIT = 18
    """Fahrenheit."""
    KELVIN = 19
    """kelvin."""
    PERCENT = 20
    """percent."""
    FLOAT = 21
    """float."""
    INTEGER = 22
    """integer."""
    MICROGRAMS_PER_CUBIC_METER_OF_AIR = 31
    """MicrogramsPerCubicMeterOfAir."""


class WeatherDataUnit(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Unit of measurement for weather data."""

    IMPERIAL = "imperial"
    """Return data using imperial units such as Fahrenheit (F) for temperature and mile (mi) for
    distance."""
    METRIC = "metric"
    """Return data using metric units such as Celsius (C) for temperature and kilometer (km) for
    distance."""
