# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
from collections.abc import MutableMapping
import datetime
from typing import Any, Callable, Optional, TypeVar, Union

from azure.core import PipelineClient
from azure.core.exceptions import (
    ClientAuthenticationError,
    HttpResponseError,
    ResourceExistsError,
    ResourceNotFoundError,
    ResourceNotModifiedError,
    StreamClosedError,
    StreamConsumedError,
    map_error,
)
from azure.core.pipeline import PipelineResponse
from azure.core.rest import HttpRequest, HttpResponse
from azure.core.tracing.decorator import distributed_trace
from azure.core.utils import case_insensitive_dict

from .. import models as _models
from .._configuration import MapsTimezoneClientConfiguration
from .._utils.model_base import _deserialize, _failsafe_deserialize
from .._utils.serialization import Serializer
from .._utils.utils import ClientMixinABC

T = TypeVar("T")
ClsType = Optional[Callable[[PipelineResponse[HttpRequest, HttpResponse], T, dict[str, Any]], Any]]

_SERIALIZER = Serializer()
_SERIALIZER.client_side_validation = False


def build_maps_timezone_get_timezone_by_id_request(  # pylint: disable=name-too-long
    format: Union[str, _models.JsonFormat] = "json",
    *,
    timezone_id: str,
    client_id: Optional[str] = None,
    accept_language: Optional[str] = None,
    options: Optional[Union[str, _models.TimezoneOptions]] = None,
    time_stamp: Optional[datetime.datetime] = None,
    daylight_savings_time_from: Optional[datetime.datetime] = None,
    daylight_savings_time_lasting_years: Optional[int] = None,
    **kwargs: Any
) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "1.0"))
    accept = _headers.pop("Accept", "application/json")

    # Construct URL
    _url = "/timezone/byId/{format}"
    path_format_arguments = {
        "format": _SERIALIZER.url("format", format, "str"),
    }

    _url: str = _url.format(**path_format_arguments)  # type: ignore

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")
    if options is not None:
        _params["options"] = _SERIALIZER.query("options", options, "str")
    if time_stamp is not None:
        _params["timeStamp"] = _SERIALIZER.query("time_stamp", time_stamp, "iso-8601")
    if daylight_savings_time_from is not None:
        _params["transitionsFrom"] = _SERIALIZER.query(
            "daylight_savings_time_from", daylight_savings_time_from, "iso-8601"
        )
    if daylight_savings_time_lasting_years is not None:
        _params["transitionsYears"] = _SERIALIZER.query(
            "daylight_savings_time_lasting_years", daylight_savings_time_lasting_years, "int"
        )
    _params["query"] = _SERIALIZER.query("timezone_id", timezone_id, "str")

    # Construct headers
    if client_id is not None:
        _headers["x-ms-client-id"] = _SERIALIZER.header("client_id", client_id, "str")
    if accept_language is not None:
        _headers["Accept-Language"] = _SERIALIZER.header("accept_language", accept_language, "str")
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="GET", url=_url, params=_params, headers=_headers, **kwargs)


def build_maps_timezone_get_timezone_by_coordinates_request(  # pylint: disable=name-too-long
    format: Union[str, _models.JsonFormat] = "json",
    *,
    coordinates: list[float],
    client_id: Optional[str] = None,
    accept_language: Optional[str] = None,
    options: Optional[Union[str, _models.TimezoneOptions]] = None,
    time_stamp: Optional[datetime.datetime] = None,
    daylight_savings_time_from: Optional[datetime.datetime] = None,
    daylight_savings_time_lasting_years: Optional[int] = None,
    **kwargs: Any
) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "1.0"))
    accept = _headers.pop("Accept", "application/json")

    # Construct URL
    _url = "/timezone/byCoordinates/{format}"
    path_format_arguments = {
        "format": _SERIALIZER.url("format", format, "str"),
    }

    _url: str = _url.format(**path_format_arguments)  # type: ignore

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")
    if options is not None:
        _params["options"] = _SERIALIZER.query("options", options, "str")
    if time_stamp is not None:
        _params["timeStamp"] = _SERIALIZER.query("time_stamp", time_stamp, "iso-8601")
    if daylight_savings_time_from is not None:
        _params["transitionsFrom"] = _SERIALIZER.query(
            "daylight_savings_time_from", daylight_savings_time_from, "iso-8601"
        )
    if daylight_savings_time_lasting_years is not None:
        _params["transitionsYears"] = _SERIALIZER.query(
            "daylight_savings_time_lasting_years", daylight_savings_time_lasting_years, "int"
        )
    _params["query"] = _SERIALIZER.query("coordinates", coordinates, "[float]", div=",")

    # Construct headers
    if client_id is not None:
        _headers["x-ms-client-id"] = _SERIALIZER.header("client_id", client_id, "str")
    if accept_language is not None:
        _headers["Accept-Language"] = _SERIALIZER.header("accept_language", accept_language, "str")
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="GET", url=_url, params=_params, headers=_headers, **kwargs)


def build_maps_timezone_get_windows_timezone_ids_request(  # pylint: disable=name-too-long
    format: Union[str, _models.JsonFormat] = "json", *, client_id: Optional[str] = None, **kwargs: Any
) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "1.0"))
    accept = _headers.pop("Accept", "application/json")

    # Construct URL
    _url = "/timezone/enumWindows/{format}"
    path_format_arguments = {
        "format": _SERIALIZER.url("format", format, "str"),
    }

    _url: str = _url.format(**path_format_arguments)  # type: ignore

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")

    # Construct headers
    if client_id is not None:
        _headers["x-ms-client-id"] = _SERIALIZER.header("client_id", client_id, "str")
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="GET", url=_url, params=_params, headers=_headers, **kwargs)


def build_maps_timezone_get_iana_timezone_ids_request(  # pylint: disable=name-too-long
    format: Union[str, _models.JsonFormat] = "json", *, client_id: Optional[str] = None, **kwargs: Any
) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "1.0"))
    accept = _headers.pop("Accept", "application/json")

    # Construct URL
    _url = "/timezone/enumIana/{format}"
    path_format_arguments = {
        "format": _SERIALIZER.url("format", format, "str"),
    }

    _url: str = _url.format(**path_format_arguments)  # type: ignore

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")

    # Construct headers
    if client_id is not None:
        _headers["x-ms-client-id"] = _SERIALIZER.header("client_id", client_id, "str")
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="GET", url=_url, params=_params, headers=_headers, **kwargs)


def build_maps_timezone_get_iana_version_request(  # pylint: disable=name-too-long
    format: Union[str, _models.JsonFormat] = "json", *, client_id: Optional[str] = None, **kwargs: Any
) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "1.0"))
    accept = _headers.pop("Accept", "application/json")

    # Construct URL
    _url = "/timezone/ianaVersion/{format}"
    path_format_arguments = {
        "format": _SERIALIZER.url("format", format, "str"),
    }

    _url: str = _url.format(**path_format_arguments)  # type: ignore

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")

    # Construct headers
    if client_id is not None:
        _headers["x-ms-client-id"] = _SERIALIZER.header("client_id", client_id, "str")
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="GET", url=_url, params=_params, headers=_headers, **kwargs)


def build_maps_timezone_convert_windows_timezone_to_iana_request(  # pylint: disable=name-too-long
    format: Union[str, _models.JsonFormat] = "json",
    *,
    windows_timezone_id: str,
    client_id: Optional[str] = None,
    windows_territory_code: Optional[str] = None,
    **kwargs: Any
) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "1.0"))
    accept = _headers.pop("Accept", "application/json")

    # Construct URL
    _url = "/timezone/windowsToIana/{format}"
    path_format_arguments = {
        "format": _SERIALIZER.url("format", format, "str"),
    }

    _url: str = _url.format(**path_format_arguments)  # type: ignore

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")
    _params["query"] = _SERIALIZER.query("windows_timezone_id", windows_timezone_id, "str")
    if windows_territory_code is not None:
        _params["territory"] = _SERIALIZER.query("windows_territory_code", windows_territory_code, "str")

    # Construct headers
    if client_id is not None:
        _headers["x-ms-client-id"] = _SERIALIZER.header("client_id", client_id, "str")
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="GET", url=_url, params=_params, headers=_headers, **kwargs)


class _MapsTimezoneClientOperationsMixin(
    ClientMixinABC[PipelineClient[HttpRequest, HttpResponse], MapsTimezoneClientConfiguration]
):

    @distributed_trace
    def get_timezone_by_id(
        self,
        format: Union[str, _models.JsonFormat] = "json",
        *,
        timezone_id: str,
        client_id: Optional[str] = None,
        accept_language: Optional[str] = None,
        options: Optional[Union[str, _models.TimezoneOptions]] = None,
        time_stamp: Optional[datetime.datetime] = None,
        daylight_savings_time_from: Optional[datetime.datetime] = None,
        daylight_savings_time_lasting_years: Optional[int] = None,
        **kwargs: Any
    ) -> _models.TimezoneResult:
        """Use to get the current, historical, and future time zone information for the specified IANA
        time zone ID.

        The ``Get Timezone By ID`` API is an HTTP ``GET`` request that returns current, historical, and
        future time zone information for the specified IANA time zone ID.

        :param format: Desired format of the response. Only ``json`` format is supported. "json"
         Default value is "json".
        :type format: str or ~azure.maps.timezone.models.JsonFormat
        :keyword timezone_id: The IANA time zone ID. Required.
        :paramtype timezone_id: str
        :keyword client_id: Indicates the account intended for use with the Microsoft Entra ID security
         model. This unique ID for the Azure Maps account can be obtained from the
         `Azure Maps management plane Account API </rest/api/maps-management/accounts>`_.
         For more information on using Microsoft Entra ID security in Azure Maps, see
         `Manage authentication in Azure
         Maps </azure/azure-maps/how-to-manage-authentication>`_. Default value is None.
        :paramtype client_id: str
        :keyword accept_language: Specifies the language code in which the timezone names should be
         returned. If
         no language code is provided, the response will be in "EN". Please refer to
         `Supported
         Languages <https://docs.microsoft.com/azure/azure-maps/supported-languages>`_ for
         details. Default value is None.
        :paramtype accept_language: str
        :keyword options: Alternatively, use alias "o". Options available for types of information
         returned in the result. Known values are: "none", "zoneInfo", "transitions", and "all".
         Default value is None.
        :paramtype options: str or ~azure.maps.timezone.models.TimezoneOptions
        :keyword time_stamp: Alternatively, use alias "stamp", or "s". Reference time, if omitted, the
         API
         will use the machine time serving the request. Default value is None.
        :paramtype time_stamp: ~datetime.datetime
        :keyword daylight_savings_time_from: Alternatively, use alias "tf". The start date from which
         daylight savings time
         (DST) transitions are requested, only applies when "options" = all or "options"
         = transitions. Default value is None.
        :paramtype daylight_savings_time_from: ~datetime.datetime
        :keyword daylight_savings_time_lasting_years: Alternatively, use alias "ty". The number of
         years from "transitionsFrom" for
         which DST transitions are requested, only applies when "options" = all or
         "options" = transitions. Default value is None.
        :paramtype daylight_savings_time_lasting_years: int
        :return: TimezoneResult. The TimezoneResult is compatible with MutableMapping
        :rtype: ~azure.maps.timezone.models.TimezoneResult
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls: ClsType[_models.TimezoneResult] = kwargs.pop("cls", None)

        _request = build_maps_timezone_get_timezone_by_id_request(
            format=format,
            timezone_id=timezone_id,
            client_id=client_id,
            accept_language=accept_language,
            options=options,
            time_stamp=time_stamp,
            daylight_savings_time_from=daylight_savings_time_from,
            daylight_savings_time_lasting_years=daylight_savings_time_lasting_years,
            api_version=self._config.api_version,
            headers=_headers,
            params=_params,
        )
        path_format_arguments = {
            "endpoint": self._serialize.url("self._config.endpoint", self._config.endpoint, "str", skip_quote=True),
        }
        _request.url = self._client.format_url(_request.url, **path_format_arguments)

        _decompress = kwargs.pop("decompress", True)
        _stream = kwargs.pop("stream", False)
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            if _stream:
                try:
                    response.read()  # Load the body in memory and close the socket
                except (StreamConsumedError, StreamClosedError):
                    pass
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            error = _failsafe_deserialize(
                _models.ErrorResponse,
                response,
            )
            raise HttpResponseError(response=response, model=error)

        if _stream:
            deserialized = response.iter_bytes() if _decompress else response.iter_raw()
        else:
            deserialized = _deserialize(_models.TimezoneResult, response.json())

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore

    @distributed_trace
    def get_timezone_by_coordinates(
        self,
        format: Union[str, _models.JsonFormat] = "json",
        *,
        coordinates: list[float],
        client_id: Optional[str] = None,
        accept_language: Optional[str] = None,
        options: Optional[Union[str, _models.TimezoneOptions]] = None,
        time_stamp: Optional[datetime.datetime] = None,
        daylight_savings_time_from: Optional[datetime.datetime] = None,
        daylight_savings_time_lasting_years: Optional[int] = None,
        **kwargs: Any
    ) -> _models.TimezoneResult:
        """Use to get the current, historical, and future time zone information for the specified
        latitude-longitude pair.

        The ``Get Timezone By Coordinates`` API is an HTTP ``GET`` request that returns current,
        historical, and future time zone information for a specified latitude-longitude pair. In
        addition, the API provides sunset and sunrise times for a given location, with the exception of
        regions that observe solar days.

        :param format: Desired format of the response. Only ``json`` format is supported. "json"
         Default value is "json".
        :type format: str or ~azure.maps.timezone.models.JsonFormat
        :keyword coordinates: Coordinates of the point for which time zone information is requested.
         This
         parameter is a list of coordinates, containing a pair of coordinate(lat, long).
         When this endpoint is called directly, coordinates are passed in as a single
         string containing coordinates, separated by commas. Required.
        :paramtype coordinates: list[float]
        :keyword client_id: Indicates the account intended for use with the Microsoft Entra ID security
         model. This unique ID for the Azure Maps account can be obtained from the
         `Azure Maps management plane Account API </rest/api/maps-management/accounts>`_.
         For more information on using Microsoft Entra ID security in Azure Maps, see
         `Manage authentication in Azure
         Maps </azure/azure-maps/how-to-manage-authentication>`_. Default value is None.
        :paramtype client_id: str
        :keyword accept_language: Specifies the language code in which the timezone names should be
         returned. If
         no language code is provided, the response will be in "EN". Please refer to
         `Supported
         Languages <https://docs.microsoft.com/azure/azure-maps/supported-languages>`_ for
         details. Default value is None.
        :paramtype accept_language: str
        :keyword options: Alternatively, use alias "o". Options available for types of information
         returned in the result. Known values are: "none", "zoneInfo", "transitions", and "all".
         Default value is None.
        :paramtype options: str or ~azure.maps.timezone.models.TimezoneOptions
        :keyword time_stamp: Alternatively, use alias "stamp", or "s". Reference time, if omitted, the
         API
         will use the machine time serving the request. Default value is None.
        :paramtype time_stamp: ~datetime.datetime
        :keyword daylight_savings_time_from: Alternatively, use alias "tf". The start date from which
         daylight savings time
         (DST) transitions are requested, only applies when "options" = all or "options"
         = transitions. Default value is None.
        :paramtype daylight_savings_time_from: ~datetime.datetime
        :keyword daylight_savings_time_lasting_years: Alternatively, use alias "ty". The number of
         years from "transitionsFrom" for
         which DST transitions are requested, only applies when "options" = all or
         "options" = transitions. Default value is None.
        :paramtype daylight_savings_time_lasting_years: int
        :return: TimezoneResult. The TimezoneResult is compatible with MutableMapping
        :rtype: ~azure.maps.timezone.models.TimezoneResult
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls: ClsType[_models.TimezoneResult] = kwargs.pop("cls", None)

        _request = build_maps_timezone_get_timezone_by_coordinates_request(
            format=format,
            coordinates=coordinates,
            client_id=client_id,
            accept_language=accept_language,
            options=options,
            time_stamp=time_stamp,
            daylight_savings_time_from=daylight_savings_time_from,
            daylight_savings_time_lasting_years=daylight_savings_time_lasting_years,
            api_version=self._config.api_version,
            headers=_headers,
            params=_params,
        )
        path_format_arguments = {
            "endpoint": self._serialize.url("self._config.endpoint", self._config.endpoint, "str", skip_quote=True),
        }
        _request.url = self._client.format_url(_request.url, **path_format_arguments)

        _decompress = kwargs.pop("decompress", True)
        _stream = kwargs.pop("stream", False)
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            if _stream:
                try:
                    response.read()  # Load the body in memory and close the socket
                except (StreamConsumedError, StreamClosedError):
                    pass
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            error = _failsafe_deserialize(
                _models.ErrorResponse,
                response,
            )
            raise HttpResponseError(response=response, model=error)

        if _stream:
            deserialized = response.iter_bytes() if _decompress else response.iter_raw()
        else:
            deserialized = _deserialize(_models.TimezoneResult, response.json())

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore

    @distributed_trace
    def get_windows_timezone_ids(
        self, format: Union[str, _models.JsonFormat] = "json", *, client_id: Optional[str] = None, **kwargs: Any
    ) -> list[_models.TimezoneWindows]:
        """Use to get the list of Windows Time Zone IDs.

        The ``Get Windows Time Zones`` API is an HTTP ``GET`` request that returns a full list of
        Windows Time Zone IDs.

        :param format: Desired format of the response. Only ``json`` format is supported. "json"
         Default value is "json".
        :type format: str or ~azure.maps.timezone.models.JsonFormat
        :keyword client_id: Indicates the account intended for use with the Microsoft Entra ID security
         model. This unique ID for the Azure Maps account can be obtained from the
         `Azure Maps management plane Account API </rest/api/maps-management/accounts>`_.
         For more information on using Microsoft Entra ID security in Azure Maps, see
         `Manage authentication in Azure
         Maps </azure/azure-maps/how-to-manage-authentication>`_. Default value is None.
        :paramtype client_id: str
        :return: list of TimezoneWindows
        :rtype: list[~azure.maps.timezone.models.TimezoneWindows]
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls: ClsType[list[_models.TimezoneWindows]] = kwargs.pop("cls", None)

        _request = build_maps_timezone_get_windows_timezone_ids_request(
            format=format,
            client_id=client_id,
            api_version=self._config.api_version,
            headers=_headers,
            params=_params,
        )
        path_format_arguments = {
            "endpoint": self._serialize.url("self._config.endpoint", self._config.endpoint, "str", skip_quote=True),
        }
        _request.url = self._client.format_url(_request.url, **path_format_arguments)

        _decompress = kwargs.pop("decompress", True)
        _stream = kwargs.pop("stream", False)
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            if _stream:
                try:
                    response.read()  # Load the body in memory and close the socket
                except (StreamConsumedError, StreamClosedError):
                    pass
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            error = _failsafe_deserialize(
                _models.ErrorResponse,
                response,
            )
            raise HttpResponseError(response=response, model=error)

        if _stream:
            deserialized = response.iter_bytes() if _decompress else response.iter_raw()
        else:
            deserialized = _deserialize(list[_models.TimezoneWindows], response.json())

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore

    @distributed_trace
    def get_iana_timezone_ids(
        self, format: Union[str, _models.JsonFormat] = "json", *, client_id: Optional[str] = None, **kwargs: Any
    ) -> list[_models.IanaId]:
        """Use to get the list of IANA time zone IDs.

        The ``Get IANA Time Zones`` API is an HTTP ``GET`` request that returns a full list of Internet
        Assigned Numbers Authority (IANA) time zone IDs. Updates to the IANA service are reflected in
        the system within one day.

        :param format: Desired format of the response. Only ``json`` format is supported. "json"
         Default value is "json".
        :type format: str or ~azure.maps.timezone.models.JsonFormat
        :keyword client_id: Indicates the account intended for use with the Microsoft Entra ID security
         model. This unique ID for the Azure Maps account can be obtained from the
         `Azure Maps management plane Account API </rest/api/maps-management/accounts>`_.
         For more information on using Microsoft Entra ID security in Azure Maps, see
         `Manage authentication in Azure
         Maps </azure/azure-maps/how-to-manage-authentication>`_. Default value is None.
        :paramtype client_id: str
        :return: list of IanaId
        :rtype: list[~azure.maps.timezone.models.IanaId]
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls: ClsType[list[_models.IanaId]] = kwargs.pop("cls", None)

        _request = build_maps_timezone_get_iana_timezone_ids_request(
            format=format,
            client_id=client_id,
            api_version=self._config.api_version,
            headers=_headers,
            params=_params,
        )
        path_format_arguments = {
            "endpoint": self._serialize.url("self._config.endpoint", self._config.endpoint, "str", skip_quote=True),
        }
        _request.url = self._client.format_url(_request.url, **path_format_arguments)

        _decompress = kwargs.pop("decompress", True)
        _stream = kwargs.pop("stream", False)
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            if _stream:
                try:
                    response.read()  # Load the body in memory and close the socket
                except (StreamConsumedError, StreamClosedError):
                    pass
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            error = _failsafe_deserialize(
                _models.ErrorResponse,
                response,
            )
            raise HttpResponseError(response=response, model=error)

        if _stream:
            deserialized = response.iter_bytes() if _decompress else response.iter_raw()
        else:
            deserialized = _deserialize(list[_models.IanaId], response.json())

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore

    @distributed_trace
    def get_iana_version(
        self, format: Union[str, _models.JsonFormat] = "json", *, client_id: Optional[str] = None, **kwargs: Any
    ) -> _models.TimezoneIanaVersionResult:
        """Use to get the current IANA version number.

        The ``Get Time Zone IANA Version`` API is an HTTP ``GET`` request that returns the current
        Internet Assigned Numbers Authority (IANA) version number as Metadata.

        :param format: Desired format of the response. Only ``json`` format is supported. "json"
         Default value is "json".
        :type format: str or ~azure.maps.timezone.models.JsonFormat
        :keyword client_id: Indicates the account intended for use with the Microsoft Entra ID security
         model. This unique ID for the Azure Maps account can be obtained from the
         `Azure Maps management plane Account API </rest/api/maps-management/accounts>`_.
         For more information on using Microsoft Entra ID security in Azure Maps, see
         `Manage authentication in Azure
         Maps </azure/azure-maps/how-to-manage-authentication>`_. Default value is None.
        :paramtype client_id: str
        :return: TimezoneIanaVersionResult. The TimezoneIanaVersionResult is compatible with
         MutableMapping
        :rtype: ~azure.maps.timezone.models.TimezoneIanaVersionResult
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls: ClsType[_models.TimezoneIanaVersionResult] = kwargs.pop("cls", None)

        _request = build_maps_timezone_get_iana_version_request(
            format=format,
            client_id=client_id,
            api_version=self._config.api_version,
            headers=_headers,
            params=_params,
        )
        path_format_arguments = {
            "endpoint": self._serialize.url("self._config.endpoint", self._config.endpoint, "str", skip_quote=True),
        }
        _request.url = self._client.format_url(_request.url, **path_format_arguments)

        _decompress = kwargs.pop("decompress", True)
        _stream = kwargs.pop("stream", False)
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            if _stream:
                try:
                    response.read()  # Load the body in memory and close the socket
                except (StreamConsumedError, StreamClosedError):
                    pass
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            error = _failsafe_deserialize(
                _models.ErrorResponse,
                response,
            )
            raise HttpResponseError(response=response, model=error)

        if _stream:
            deserialized = response.iter_bytes() if _decompress else response.iter_raw()
        else:
            deserialized = _deserialize(_models.TimezoneIanaVersionResult, response.json())

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore

    @distributed_trace
    def convert_windows_timezone_to_iana(
        self,
        format: Union[str, _models.JsonFormat] = "json",
        *,
        windows_timezone_id: str,
        client_id: Optional[str] = None,
        windows_territory_code: Optional[str] = None,
        **kwargs: Any
    ) -> list[_models.IanaId]:
        """Use to get the IANA ID.

        The ``Get Windows to IANA Time Zone`` API is an HTTP ``GET`` request that returns a
        corresponding Internet Assigned Numbers Authority (IANA) ID, given a valid Windows Time Zone
        ID. Multiple IANA IDs may be returned for a single Windows ID. It is possible to narrow these
        results by adding an optional territory parameter.

        :param format: Desired format of the response. Only ``json`` format is supported. "json"
         Default value is "json".
        :type format: str or ~azure.maps.timezone.models.JsonFormat
        :keyword windows_timezone_id: The Windows time zone ID. Required.
        :paramtype windows_timezone_id: str
        :keyword client_id: Indicates the account intended for use with the Microsoft Entra ID security
         model. This unique ID for the Azure Maps account can be obtained from the
         `Azure Maps management plane Account API </rest/api/maps-management/accounts>`_.
         For more information on using Microsoft Entra ID security in Azure Maps, see
         `Manage authentication in Azure
         Maps </azure/azure-maps/how-to-manage-authentication>`_. Default value is None.
        :paramtype client_id: str
        :keyword windows_territory_code: Windows Time Zone territory code. Default value is None.
        :paramtype windows_territory_code: str
        :return: list of IanaId
        :rtype: list[~azure.maps.timezone.models.IanaId]
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls: ClsType[list[_models.IanaId]] = kwargs.pop("cls", None)

        _request = build_maps_timezone_convert_windows_timezone_to_iana_request(
            format=format,
            windows_timezone_id=windows_timezone_id,
            client_id=client_id,
            windows_territory_code=windows_territory_code,
            api_version=self._config.api_version,
            headers=_headers,
            params=_params,
        )
        path_format_arguments = {
            "endpoint": self._serialize.url("self._config.endpoint", self._config.endpoint, "str", skip_quote=True),
        }
        _request.url = self._client.format_url(_request.url, **path_format_arguments)

        _decompress = kwargs.pop("decompress", True)
        _stream = kwargs.pop("stream", False)
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            if _stream:
                try:
                    response.read()  # Load the body in memory and close the socket
                except (StreamConsumedError, StreamClosedError):
                    pass
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            error = _failsafe_deserialize(
                _models.ErrorResponse,
                response,
            )
            raise HttpResponseError(response=response, model=error)

        if _stream:
            deserialized = response.iter_bytes() if _decompress else response.iter_raw()
        else:
            deserialized = _deserialize(list[_models.IanaId], response.json())

        if cls:
            return cls(pipeline_response, deserialized, {})  # type: ignore

        return deserialized  # type: ignore
