# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
# pylint: disable=useless-super-delegation

import datetime
from typing import Any, Mapping, Optional, TYPE_CHECKING, overload

from .._utils.model_base import Model as _Model, rest_field

if TYPE_CHECKING:
    from .. import models as _models


class CountryRecord(_Model):
    """A country/region record.

    :ivar name: country/region Name.
    :vartype name: str
    :ivar code: ISO-3166 2-letter country/region code for the country/region.
    :vartype code: str
    """

    name: Optional[str] = rest_field(name="Name", visibility=["read"])
    """country/region Name."""
    code: Optional[str] = rest_field(name="Code", visibility=["read"])
    """ISO-3166 2-letter country/region code for the country/region."""


class ErrorAdditionalInfo(_Model):
    """The resource management error additional info.

    :ivar type: The additional info type.
    :vartype type: str
    :ivar info: The additional info.
    :vartype info: dict[str, any]
    """

    type: Optional[str] = rest_field(visibility=["read"])
    """The additional info type."""
    info: Optional[dict[str, Any]] = rest_field(visibility=["read"])
    """The additional info."""


class ErrorDetail(_Model):
    """The error detail.

    :ivar code: The error code.
    :vartype code: str
    :ivar message: The error message.
    :vartype message: str
    :ivar target: The error target.
    :vartype target: str
    :ivar details: The error details.
    :vartype details: list[~azure.maps.timezone.models.ErrorDetail]
    :ivar additional_info: The error additional info.
    :vartype additional_info: list[~azure.maps.timezone.models.ErrorAdditionalInfo]
    """

    code: Optional[str] = rest_field(visibility=["read"])
    """The error code."""
    message: Optional[str] = rest_field(visibility=["read"])
    """The error message."""
    target: Optional[str] = rest_field(visibility=["read"])
    """The error target."""
    details: Optional[list["_models.ErrorDetail"]] = rest_field(visibility=["read"])
    """The error details."""
    additional_info: Optional[list["_models.ErrorAdditionalInfo"]] = rest_field(
        name="additionalInfo", visibility=["read"]
    )
    """The error additional info."""


class ErrorResponse(_Model):
    """Common error response for all Azure Resource Manager APIs to return error details for failed
    operations. (This also follows the OData error response format.).

    :ivar error: The error object.
    :vartype error: ~azure.maps.timezone.models.ErrorDetail
    """

    error: Optional["_models.ErrorDetail"] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """The error object."""

    @overload
    def __init__(
        self,
        *,
        error: Optional["_models.ErrorDetail"] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class IanaId(_Model):
    """IANA time zone ID information.

    :ivar id: Id property.
    :vartype id: str
    :ivar is_alias: IsAlias property.
    :vartype is_alias: bool
    :ivar alias_of: AliasOf property.
    :vartype alias_of: str
    :ivar has_zone1970_location: This attribute returns ``True`` if the IanaId has any country/zone
     associated with it.
    :vartype has_zone1970_location: bool
    """

    id: Optional[str] = rest_field(name="Id", visibility=["read"])
    """Id property."""
    is_alias: Optional[bool] = rest_field(name="IsAlias", visibility=["read"])
    """IsAlias property."""
    alias_of: Optional[str] = rest_field(name="AliasOf", visibility=["read"])
    """AliasOf property."""
    has_zone1970_location: Optional[bool] = rest_field(name="HasZone1970Location", visibility=["read"])
    """This attribute returns ``True`` if the IanaId has any country/zone associated with it."""


class ReferenceTime(_Model):
    """Details in effect at the local time.

    :ivar tag: Time zone name in effect at the reference timestamp (i.e. PST or PDT depending
     whether Daylight Savings Time is in effect).
    :vartype tag: str
    :ivar standard_offset: UTC offset in effect at the ``ReferenceUTCTimestamp``.
    :vartype standard_offset: str
    :ivar daylight_savings: Time saving in minutes in effect at the ``ReferenceUTCTimestamp``.
    :vartype daylight_savings: str
    :ivar wall_time: Current wall time at the given time zone as shown in the ``Tag`` property.
    :vartype wall_time: str
    :ivar posix_tz_valid_year: The year this POSIX string is valid for. Note: A POSIX string will
     only be valid in the given year.
    :vartype posix_tz_valid_year: int
    :ivar posix_tz: POSIX string used to set the time zone environment variable.
    :vartype posix_tz: str
    :ivar sunrise: Sunrise at the given time zone as shown in the ``Tag`` property, populated only
     when the call is ``byCoordinates``. The sunrise is described in the `ISO 8601
     <https://www.iso.org/iso-8601-date-and-time-format.html>`_ format. Note that the Timezone API
     does not return sunrise and sunset times when solar day is observed in the requested region.
    :vartype sunrise: ~datetime.datetime
    :ivar sunset: Sunset at the given time zone as shown in the ``Tag`` property, populated only
     when the call is ``byCoordinates``. The sunset is described in the `ISO 8601
     <https://www.iso.org/iso-8601-date-and-time-format.html>`_ format. Note that the Timezone API
     does not return sunrise and sunset times when solar day is observed in the requested region.
    :vartype sunset: ~datetime.datetime
    """

    tag: Optional[str] = rest_field(name="Tag", visibility=["read"])
    """Time zone name in effect at the reference timestamp (i.e. PST or PDT depending whether Daylight
     Savings Time is in effect)."""
    standard_offset: Optional[str] = rest_field(name="StandardOffset", visibility=["read"])
    """UTC offset in effect at the ``ReferenceUTCTimestamp``."""
    daylight_savings: Optional[str] = rest_field(name="DaylightSavings", visibility=["read"])
    """Time saving in minutes in effect at the ``ReferenceUTCTimestamp``."""
    wall_time: Optional[str] = rest_field(name="WallTime", visibility=["read"])
    """Current wall time at the given time zone as shown in the ``Tag`` property."""
    posix_tz_valid_year: Optional[int] = rest_field(name="PosixTzValidYear", visibility=["read"])
    """The year this POSIX string is valid for. Note: A POSIX string will only be valid in the given
     year."""
    posix_tz: Optional[str] = rest_field(name="PosixTz", visibility=["read"])
    """POSIX string used to set the time zone environment variable."""
    sunrise: Optional[datetime.datetime] = rest_field(name="Sunrise", visibility=["read"], format="rfc3339")
    """Sunrise at the given time zone as shown in the ``Tag`` property, populated only when the call
     is ``byCoordinates``. The sunrise is described in the `ISO 8601
     <https://www.iso.org/iso-8601-date-and-time-format.html>`_ format. Note that the Timezone API
     does not return sunrise and sunset times when solar day is observed in the requested region."""
    sunset: Optional[datetime.datetime] = rest_field(name="Sunset", visibility=["read"], format="rfc3339")
    """Sunset at the given time zone as shown in the ``Tag`` property, populated only when the call is
     ``byCoordinates``. The sunset is described in the `ISO 8601
     <https://www.iso.org/iso-8601-date-and-time-format.html>`_ format. Note that the Timezone API
     does not return sunrise and sunset times when solar day is observed in the requested region."""


class RepresentativePoint(_Model):
    """Representative point property.

    :ivar latitude: Latitude property.
    :vartype latitude: float
    :ivar longitude: Longitude property.
    :vartype longitude: float
    """

    latitude: Optional[float] = rest_field(name="Latitude", visibility=["read"])
    """Latitude property."""
    longitude: Optional[float] = rest_field(name="Longitude", visibility=["read"])
    """Longitude property."""


class TimeTransition(_Model):
    """Represents a time zone transition.

    :ivar tag: Tag property.
    :vartype tag: str
    :ivar standard_offset: StandardOffset property.
    :vartype standard_offset: str
    :ivar daylight_savings: DaylightSavings property.
    :vartype daylight_savings: str
    :ivar utc_start: Start date, start time for this transition period.
    :vartype utc_start: ~datetime.datetime
    :ivar utc_end: End date, end time for this transition period.
    :vartype utc_end: ~datetime.datetime
    """

    tag: Optional[str] = rest_field(name="Tag", visibility=["read"])
    """Tag property."""
    standard_offset: Optional[str] = rest_field(name="StandardOffset", visibility=["read"])
    """StandardOffset property."""
    daylight_savings: Optional[str] = rest_field(name="DaylightSavings", visibility=["read"])
    """DaylightSavings property."""
    utc_start: Optional[datetime.datetime] = rest_field(name="UtcStart", visibility=["read"], format="rfc3339")
    """Start date, start time for this transition period."""
    utc_end: Optional[datetime.datetime] = rest_field(name="UtcEnd", visibility=["read"], format="rfc3339")
    """End date, end time for this transition period."""


class TimezoneIanaVersionResult(_Model):
    """This object is returned from a successful Timezone IANA Version call.

    :ivar version: Version property.
    :vartype version: str
    """

    version: Optional[str] = rest_field(name="Version", visibility=["read"])
    """Version property."""


class TimezoneId(_Model):
    """Timezone ID information.

    :ivar id: Id property.
    :vartype id: str
    :ivar aliases: An array of time zone ID aliases. Only returned when [options]=*zoneinfo* or
     *all*.

     Note: may be null.
    :vartype aliases: list[str]
    :ivar countries: An array of country/region records. Only returned when [options]=*zoneinfo* or
     *all*.
    :vartype countries: list[~azure.maps.timezone.models.CountryRecord]
    :ivar names: Timezone names object.
    :vartype names: ~azure.maps.timezone.models.TimezoneNames
    :ivar reference_time: Details in effect at the local time.
    :vartype reference_time: ~azure.maps.timezone.models.ReferenceTime
    :ivar representative_point: Representative point property.
    :vartype representative_point: ~azure.maps.timezone.models.RepresentativePoint
    :ivar time_transitions: Time zone DST transitions from [transitionsFrom] until timestamp + 1
     year.
    :vartype time_transitions: list[~azure.maps.timezone.models.TimeTransition]
    """

    id: Optional[str] = rest_field(name="Id", visibility=["read"])
    """Id property."""
    aliases: Optional[list[str]] = rest_field(name="Aliases", visibility=["read"])
    """An array of time zone ID aliases. Only returned when [options]=*zoneinfo* or
     *all*.
     
     Note: may be null."""
    countries: Optional[list["_models.CountryRecord"]] = rest_field(name="Countries", visibility=["read"])
    """An array of country/region records. Only returned when [options]=*zoneinfo* or *all*."""
    names: Optional["_models.TimezoneNames"] = rest_field(
        name="Names", visibility=["read", "create", "update", "delete", "query"]
    )
    """Timezone names object."""
    reference_time: Optional["_models.ReferenceTime"] = rest_field(name="ReferenceTime", visibility=["read"])
    """Details in effect at the local time."""
    representative_point: Optional["_models.RepresentativePoint"] = rest_field(
        name="RepresentativePoint", visibility=["read"]
    )
    """Representative point property."""
    time_transitions: Optional[list["_models.TimeTransition"]] = rest_field(name="TimeTransitions", visibility=["read"])
    """Time zone DST transitions from [transitionsFrom] until timestamp + 1 year."""

    @overload
    def __init__(
        self,
        *,
        names: Optional["_models.TimezoneNames"] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class TimezoneNames(_Model):
    """Timezone names object.

    :ivar iso6391_language_code: The ISO 639-1 language code of the Names.
    :vartype iso6391_language_code: str
    :ivar generic: Generic Name.
    :vartype generic: str
    :ivar standard: Standard Name.
    :vartype standard: str
    :ivar daylight: Daylight Name.
    :vartype daylight: str
    """

    iso6391_language_code: Optional[str] = rest_field(name="ISO6391LanguageCode", visibility=["read"])
    """The ISO 639-1 language code of the Names."""
    generic: Optional[str] = rest_field(name="Generic", visibility=["read"])
    """Generic Name."""
    standard: Optional[str] = rest_field(name="Standard", visibility=["read"])
    """Standard Name."""
    daylight: Optional[str] = rest_field(name="Daylight", visibility=["read"])
    """Daylight Name."""


class TimezoneResult(_Model):
    """This object is returned from a successful Timezone By ID call or By Coordinates call.

    :ivar version: Version property.
    :vartype version: str
    :ivar reference_utc_timestamp: Reference Utc Timestamp property.
    :vartype reference_utc_timestamp: ~datetime.datetime
    :ivar time_zones: TimeZoneId array.
    :vartype time_zones: list[~azure.maps.timezone.models.TimezoneId]
    """

    version: Optional[str] = rest_field(name="Version", visibility=["read"])
    """Version property."""
    reference_utc_timestamp: Optional[datetime.datetime] = rest_field(
        name="ReferenceUtcTimestamp", visibility=["read"], format="rfc3339"
    )
    """Reference Utc Timestamp property."""
    time_zones: Optional[list["_models.TimezoneId"]] = rest_field(name="TimeZones", visibility=["read"])
    """TimeZoneId array."""


class TimezoneWindows(_Model):
    """Windows timezone information with IANA mappings.

    :ivar windows_id: Windows Id property.
    :vartype windows_id: str
    :ivar territory: Territory property.
    :vartype territory: str
    :ivar iana_ids: IanaIds array.
    :vartype iana_ids: list[str]
    """

    windows_id: Optional[str] = rest_field(name="WindowsId", visibility=["read"])
    """Windows Id property."""
    territory: Optional[str] = rest_field(name="Territory", visibility=["read"])
    """Territory property."""
    iana_ids: Optional[list[str]] = rest_field(
        name="IanaIds", visibility=["read", "create", "update", "delete", "query"]
    )
    """IanaIds array."""

    @overload
    def __init__(
        self,
        *,
        iana_ids: Optional[list[str]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
