# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class IncludeText(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Include textual data in response."""

    YES = "yes"
    """Include all textual data in response."""
    NO = "no"
    """Exclude textual data from response. Only images and country/region names will be in response."""


class LocalizedMapView(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The View parameter (also called the \\"user region\\" parameter) allows you to show the correct
    maps for a certain country/region for geopolitically disputed regions. Different
    countries/regions have different views of such regions, and the View parameter allows your
    application to comply with the view required by the country/region your application will be
    serving. By default, the View parameter is set to “Unified” even if you haven’t defined it in
    the request. It is your responsibility to determine the location of your users, and then set
    the View parameter correctly for that location. Alternatively, you have the option to set
    ‘View=Auto’, which will return the map data based on the IP  address of the request. The View
    parameter in Azure Maps must be used in compliance with applicable laws, including those
    regarding mapping, of the country/region where maps, images and other data and third party
    content that you are authorized to  access via Azure Maps is made available. Example:
    view=IN.\\n\\nPlease refer to `Supported Views <https://aka.ms/AzureMapsLocalizationViews>`_
    for details and to see the available Views.
    """

    AE = "AE"
    """United Arab Emirates (Arabic View)."""
    AR = "AR"
    """Argentina (Argentinian View)."""
    BH = "BH"
    """Bahrain (Arabic View)."""
    IN = "IN"
    """India (Indian View)."""
    IQ = "IQ"
    """Iraq (Arabic View)."""
    JO = "JO"
    """Jordan (Arabic View)."""
    KW = "KW"
    """Kuwait (Arabic View)."""
    LB = "LB"
    """Lebanon (Arabic View)."""
    MA = "MA"
    """Morocco (Moroccan View)."""
    OM = "OM"
    """Oman (Arabic View)."""
    PK = "PK"
    """Pakistan (Pakistani View)."""
    PS = "PS"
    """Palestinian Authority (Arabic View)."""
    QA = "QA"
    """Qatar (Arabic View)."""
    SA = "SA"
    """Saudi Arabia (Arabic View)."""
    SY = "SY"
    """Syria (Arabic View)."""
    US = "US"
    """United States of America."""
    YE = "YE"
    """Yemen (Arabic View)."""
    AUTO = "Auto"
    """Return the map data based on the IP address of the request."""
    UNIFIED = "Unified"
    """Unified View (Others)."""


class MapTileSize(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The size of the returned map tile in pixels."""

    SIZE256 = "256"
    """Return a 256 by 256 pixel tile."""
    SIZE512 = "512"
    """Return a 512 by 512 pixel tile."""


class MediaType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The desired media type of the response."""

    IMAGE_PNG = "image/png"
    """Return image in png format."""
    IMAGE_JPEG = "image/jpeg"
    """Return image in jpeg format."""


class ResponseFormat(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Desired format of the response. Value can be either *json* or *xml*."""

    JSON = "json"
    """`The JavaScript Object Notation Data Interchange Format
    <https://tools.ietf.org/html/rfc8259>`_."""
    XML = "xml"
    """`The Extensible Markup Language <https://www.w3.org/TR/xml/>`_."""


class Tileset(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """A tileset is a collection of raster or vector data broken up into a uniform grid of square
    tiles at preset zoom levels. Every tileset has a **tilesetId** to use when making requests. The
    ready-to-use tilesets supplied by Azure Maps are listed below. For example, microsoft.base.
    """

    MICROSOFT_BASE_ROAD = "microsoft.base.road"
    """microsoft.base.road."""
    MICROSOFT_BASE_DARKGREY = "microsoft.base.darkgrey"
    """microsoft.base.darkgrey."""
    MICROSOFT_IMAGERY = "microsoft.imagery"
    """microsoft.imagery."""


class TilesetID(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """A tileset is a collection of raster or vector data broken up into a uniform grid of square
    tiles at preset zoom levels. Every tileset has a **tilesetId** to use when making requests. The
    ready-to-use tilesets supplied by Azure Maps are listed below. For example, microsoft.base.
    """

    MICROSOFT_BASE = "microsoft.base"
    """A base map is a standard map that displays roads, natural and artificial
    features along with the labels for those features in a vector tile.<br>
    
    Supports zoom levels 0 through 22. Format: vector (pbf)."""
    MICROSOFT_BASE_LABELS = "microsoft.base.labels"
    """Displays labels for roads, natural and artificial features in a vector
    tile.<br>
    
    Supports zoom levels 0 through 22. Format: vector (pbf)."""
    MICROSOFT_BASE_HYBRID = "microsoft.base.hybrid"
    """Displays road, boundary and label data in a vector tile.<br>
    
    Supports zoom levels 0 through 22. Format: vector (pbf)."""
    MICROSOFT_TERRA_MAIN = "microsoft.terra.main"
    """Shaded relief and terra layers.<br>
    
    Supports zoom levels 0 through 6. Format: raster (png)."""
    MICROSOFT_BASE_ROAD = "microsoft.base.road"
    """All layers with our main style.<br>
    
    Supports zoom levels 0 through 22. Format: raster (png)."""
    MICROSOFT_BASE_DARKGREY = "microsoft.base.darkgrey"
    """All layers with our dark grey style.<br>
    
    Supports zoom levels 0 through 22. Format: raster (png)."""
    MICROSOFT_BASE_LABELS_ROAD = "microsoft.base.labels.road"
    """Label data in our main style.<br>
    
    Supports zoom levels 0 through 22. Format: raster (png)."""
    MICROSOFT_BASE_LABELS_DARKGREY = "microsoft.base.labels.darkgrey"
    """Label data in our dark grey style.<br>
    
    Supports zoom levels 0 through 22. Format: raster (png)."""
    MICROSOFT_BASE_HYBRID_ROAD = "microsoft.base.hybrid.road"
    """Road, boundary and label data in our main style.<br>
    
    Supports zoom levels 0 through 22. Format: raster (png)."""
    MICROSOFT_BASE_HYBRID_DARKGREY = "microsoft.base.hybrid.darkgrey"
    """Road, boundary and label data in our dark grey style.<br>
    
    Supports zoom levels 0 through 22. Format: raster (png)."""
    MICROSOFT_IMAGERY = "microsoft.imagery"
    """A combination of satellite or aerial imagery. Only available in S1 and G2
    pricing SKU.<br>
    
    Supports zoom levels 1 through 19. Format: raster (png)."""
    MICROSOFT_WEATHER_RADAR_MAIN = "microsoft.weather.radar.main"
    """Weather radar tiles. Latest weather radar images including areas of rain, snow,
    ice and mixed conditions. For more information on the Azure Maps Weather
    service coverage, see `Azure Maps weather services
    coverage </azure/azure-maps/weather-coverage>`_.  For more information on Radar
    data, see `Weather services in Azure
    Maps </azure/azure-maps/weather-services-concepts#radar-images>`_.
    
    Supports zoom levels 0 through 15. Format: raster (png)."""
    MICROSOFT_WEATHER_INFRARED_MAIN = "microsoft.weather.infrared.main"
    """Weather infrared tiles. Latest Infrared Satellite images shows clouds by their
    temperature.  For more information, see `Azure Maps weather services
    coverage </azure/azure-maps/weather-coverage>`_. For more information about the
    satellite data returned, see `Weather services in Azure
    Maps
    <https://learn.microsoft.com/azure/azure-maps/weather-services-concepts#satellite-images>`_.
    
    Supports zoom levels 0 through 15. Format: raster (png)."""
    MICROSOFT_TRAFFIC_ABSOLUTE = "microsoft.traffic.absolute"
    """absolute traffic tiles in vector."""
    MICROSOFT_TRAFFIC_ABSOLUTE_MAIN = "microsoft.traffic.absolute.main"
    """absolute traffic tiles in raster in our main style."""
    MICROSOFT_TRAFFIC_RELATIVE = "microsoft.traffic.relative"
    """relative traffic tiles in vector."""
    MICROSOFT_TRAFFIC_RELATIVE_MAIN = "microsoft.traffic.relative.main"
    """relative traffic tiles in raster in our main style."""
    MICROSOFT_TRAFFIC_RELATIVE_DARK = "microsoft.traffic.relative.dark"
    """relative traffic tiles in raster in our dark style."""
    MICROSOFT_TRAFFIC_DELAY = "microsoft.traffic.delay"
    """traffic tiles in vector."""
    MICROSOFT_TRAFFIC_DELAY_MAIN = "microsoft.traffic.delay.main"
    """traffic tiles in raster in our main style."""
    MICROSOFT_TRAFFIC_REDUCED_MAIN = "microsoft.traffic.reduced.main"
    """reduced traffic tiles in raster in our main style."""
    MICROSOFT_TRAFFIC_INCIDENT = "microsoft.traffic.incident"
    """incident tiles in vector."""


class TrafficTilesetId(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Value indicating no traffic flow overlaid on the image result."""

    MICROSOFT_TRAFFIC_RELATIVE_MAIN = "microsoft.traffic.relative.main"
    """Supported traffic related tilesetId."""
    NONE = "none"
    """Default value, no traffic flow overlay."""
