# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
# pylint: disable=useless-super-delegation

from typing import Any, Mapping, Optional, TYPE_CHECKING, overload

from .._utils.model_base import Model as _Model, rest_field

if TYPE_CHECKING:
    from .. import models as _models


class Copyright(_Model):
    """This object is returned from a successful copyright request.

    :ivar format_version: Format Version property.
    :vartype format_version: str
    :ivar general_copyrights: General Copyrights array.
    :vartype general_copyrights: list[str]
    :ivar regions: Regions array.
    :vartype regions: list[~azure.maps.render.models.RegionCopyrights]
    """

    format_version: Optional[str] = rest_field(name="formatVersion", visibility=["read"])
    """Format Version property."""
    general_copyrights: Optional[list[str]] = rest_field(name="generalCopyrights", visibility=["read"])
    """General Copyrights array."""
    regions: Optional[list["_models.RegionCopyrights"]] = rest_field(visibility=["read"])
    """Regions array."""


class CopyrightCaption(_Model):
    """This object is returned from a successful copyright call.

    :ivar format_version: Format Version property.
    :vartype format_version: str
    :ivar copyrights_caption: Copyrights Caption property.
    :vartype copyrights_caption: str
    """

    format_version: Optional[str] = rest_field(name="formatVersion", visibility=["read"])
    """Format Version property."""
    copyrights_caption: Optional[str] = rest_field(name="copyrightsCaption", visibility=["read"])
    """Copyrights Caption property."""


class ErrorAdditionalInfo(_Model):
    """The resource management error additional info.

    :ivar type: The additional info type.
    :vartype type: str
    :ivar info: The additional info.
    :vartype info: dict[str, any]
    """

    type: Optional[str] = rest_field(visibility=["read"])
    """The additional info type."""
    info: Optional[dict[str, Any]] = rest_field(visibility=["read"])
    """The additional info."""


class ErrorDetail(_Model):
    """The error detail.

    :ivar code: The error code.
    :vartype code: str
    :ivar message: The error message.
    :vartype message: str
    :ivar target: The error target.
    :vartype target: str
    :ivar details: The error details.
    :vartype details: list[~azure.maps.render.models.ErrorDetail]
    :ivar additional_info: The error additional info.
    :vartype additional_info: list[~azure.maps.render.models.ErrorAdditionalInfo]
    """

    code: Optional[str] = rest_field(visibility=["read"])
    """The error code."""
    message: Optional[str] = rest_field(visibility=["read"])
    """The error message."""
    target: Optional[str] = rest_field(visibility=["read"])
    """The error target."""
    details: Optional[list["_models.ErrorDetail"]] = rest_field(visibility=["read"])
    """The error details."""
    additional_info: Optional[list["_models.ErrorAdditionalInfo"]] = rest_field(
        name="additionalInfo", visibility=["read"]
    )
    """The error additional info."""


class ErrorResponse(_Model):
    """Common error response for all Azure Resource Manager APIs to return error details for failed
    operations. (This also follows the OData error response format.).

    :ivar error: The error object.
    :vartype error: ~azure.maps.render.models.ErrorDetail
    """

    error: Optional["_models.ErrorDetail"] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """The error object."""

    @overload
    def __init__(
        self,
        *,
        error: Optional["_models.ErrorDetail"] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class MapAttribution(_Model):
    """Copyright attribution for the requested section of a tileset.

    :ivar copyrights: A list of copyright strings.
    :vartype copyrights: list[str]
    """

    copyrights: Optional[list[str]] = rest_field(visibility=["read"])
    """A list of copyright strings."""


class MapTileset(_Model):
    """Metadata for a tileset in the TileJSON format.

    :ivar tilejson: Describes the version of the TileJSON spec that is implemented by this JSON
     object.
    :vartype tilejson: str
    :ivar name: A name describing the tileset. The name can contain any legal character.
     Implementations SHOULD NOT interpret the name as HTML.
    :vartype name: str
    :ivar description: Text description of the tileset. The description can contain any legal
     character. Implementations SHOULD NOT interpret the description as HTML.
    :vartype description: str
    :ivar version: A semver.org style version number for the tiles contained within the tileset.
     When changes across tiles are introduced, the minor version MUST change.
    :vartype version: str
    :ivar attribution: Copyright attribution to be displayed on the map. Implementations MAY decide
     to treat this as HTML or literal text. For security reasons, make absolutely sure that this
     field can't be abused as a vector for XSS or beacon tracking.
    :vartype attribution: str
    :ivar template: A mustache template to be used to format data from grids for interaction.
    :vartype template: str
    :ivar legend: A legend to be displayed with the map. Implementations MAY decide to treat this
     as HTML or literal text. For security reasons, make absolutely sure that this field can't be
     abused as a vector for XSS or beacon tracking.
    :vartype legend: str
    :ivar scheme: Default: "xyz". Either "xyz" or "tms". Influences the y direction of the tile
     coordinates. The global-mercator (aka Spherical Mercator) profile is assumed.
    :vartype scheme: str
    :ivar tiles: An array of tile endpoints. If multiple endpoints are specified, clients may use
     any combination of endpoints. All endpoints MUST return the same content for the same URL. The
     array MUST contain at least one endpoint.
    :vartype tiles: list[str]
    :ivar grids: An array of interactivity endpoints.
    :vartype grids: list[str]
    :ivar data: An array of data files in GeoJSON format.
    :vartype data: list[str]
    :ivar min_zoom: The minimum zoom level.
    :vartype min_zoom: int
    :ivar max_zoom: The maximum zoom level.
    :vartype max_zoom: int
    :ivar bounds: The maximum extent of available map tiles. Bounds MUST define an area covered by
     all zoom levels. The bounds are represented in WGS:84 latitude and longitude values, in the
     order left, bottom, right, top. Values may be integers or floating point numbers.
    :vartype bounds: list[float]
    :ivar center: The default location of the tileset in the form [longitude, latitude, zoom]. The
     zoom level MUST be between minzoom and maxzoom. Implementations can use this value to set the
     default location.
    :vartype center: list[float]
    """

    tilejson: Optional[str] = rest_field(visibility=["read"])
    """Describes the version of the TileJSON spec that is implemented by this JSON object."""
    name: Optional[str] = rest_field(visibility=["read"])
    """A name describing the tileset. The name can contain any legal character. Implementations SHOULD
     NOT interpret the name as HTML."""
    description: Optional[str] = rest_field(visibility=["read"])
    """Text description of the tileset. The description can contain any legal character.
     Implementations SHOULD NOT interpret the description as HTML."""
    version: Optional[str] = rest_field(visibility=["read"])
    """A semver.org style version number for the tiles contained within the tileset. When changes
     across tiles are introduced, the minor version MUST change."""
    attribution: Optional[str] = rest_field(visibility=["read"])
    """Copyright attribution to be displayed on the map. Implementations MAY decide to treat this as
     HTML or literal text. For security reasons, make absolutely sure that this field can't be
     abused as a vector for XSS or beacon tracking."""
    template: Optional[str] = rest_field(visibility=["read"])
    """A mustache template to be used to format data from grids for interaction."""
    legend: Optional[str] = rest_field(visibility=["read"])
    """A legend to be displayed with the map. Implementations MAY decide to treat this as HTML or
     literal text. For security reasons, make absolutely sure that this field can't be abused as a
     vector for XSS or beacon tracking."""
    scheme: Optional[str] = rest_field(visibility=["read"])
    """Default: \"xyz\". Either \"xyz\" or \"tms\". Influences the y direction of the tile
     coordinates. The global-mercator (aka Spherical Mercator) profile is assumed."""
    tiles: Optional[list[str]] = rest_field(visibility=["read"])
    """An array of tile endpoints. If multiple endpoints are specified, clients may use any
     combination of endpoints. All endpoints MUST return the same content for the same URL. The
     array MUST contain at least one endpoint."""
    grids: Optional[list[str]] = rest_field(visibility=["read"])
    """An array of interactivity endpoints."""
    data: Optional[list[str]] = rest_field(visibility=["read"])
    """An array of data files in GeoJSON format."""
    min_zoom: Optional[int] = rest_field(name="minzoom", visibility=["read"])
    """The minimum zoom level."""
    max_zoom: Optional[int] = rest_field(name="maxzoom", visibility=["read"])
    """The maximum zoom level."""
    bounds: Optional[list[float]] = rest_field(visibility=["read"])
    """The maximum extent of available map tiles. Bounds MUST define an area covered by all zoom
     levels. The bounds are represented in WGS:84 latitude and longitude values, in the order left,
     bottom, right, top. Values may be integers or floating point numbers."""
    center: Optional[list[float]] = rest_field(visibility=["read"])
    """The default location of the tileset in the form [longitude, latitude, zoom]. The zoom level
     MUST be between minzoom and maxzoom. Implementations can use this value to set the default
     location."""


class RegionCopyrights(_Model):
    """Region copyrights.

    :ivar copyrights: Copyrights array.
    :vartype copyrights: list[str]
    :ivar country: Country property.
    :vartype country: ~azure.maps.render.models.RegionCopyrightsCountry
    """

    copyrights: Optional[list[str]] = rest_field(visibility=["read"])
    """Copyrights array."""
    country: Optional["_models.RegionCopyrightsCountry"] = rest_field(visibility=["read"])
    """Country property."""


class RegionCopyrightsCountry(_Model):
    """Country property.

    :ivar iso3: ISO3 property.
    :vartype iso3: str
    :ivar label: Label property.
    :vartype label: str
    """

    iso3: Optional[str] = rest_field(name="ISO3", visibility=["read"])
    """ISO3 property."""
    label: Optional[str] = rest_field(visibility=["read"])
    """Label property."""
