# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class AutocompleteResultType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Type of suggestion."""

    ADDRESS = "Address"
    """Address."""
    ADMIN_DIVISION1 = "AdminDivision1"
    """AdminDivision1."""
    ADMIN_DIVISION2 = "AdminDivision2"
    """AdminDivision2."""
    ADMIN_DIVISION3 = "AdminDivision3"
    """AdminDivision3."""
    ADMINISTRATIVE_BUILDING = "AdministrativeBuilding"
    """AdministrativeBuilding."""
    AIRPORT = "Airport"
    """Airport."""
    AIRPORT_TERMINAL = "AirportTerminal"
    """AirportTerminal."""
    AMUSEMENT_PARK = "AmusementPark"
    """AmusementPark."""
    ANCIENT_SITE = "AncientSite"
    """AncientSite."""
    AQUARIUM = "Aquarium"
    """Aquarium."""
    ARCHIPELAGO = "Archipelago"
    """Archipelago."""
    BASIN = "Basin"
    """Basin."""
    BATTLEFIELD = "Battlefield"
    """Battlefield."""
    BAY = "Bay"
    """Bay."""
    BEACH = "Beach"
    """Beach."""
    BRIDGE = "Bridge"
    """Bridge."""
    BUSINESS_STRUCTURE = "BusinessStructure"
    """BusinessStructure."""
    CAMP = "Camp"
    """Camp."""
    CANAL = "Canal"
    """Canal."""
    CASINO = "Casino"
    """Casino."""
    CASTLE = "Castle"
    """Castle."""
    CAVE = "Cave"
    """Cave."""
    CEMETERY = "Cemetery"
    """Cemetery."""
    CHANNEL = "Channel"
    """Channel."""
    CHURCH = "Church"
    """Church."""
    CLIFF = "Cliff"
    """Cliff."""
    COAST = "Coast"
    """Coast."""
    COMMUNITY_CENTER = "CommunityCenter"
    """CommunityCenter."""
    CONTINENT = "Continent"
    """Continent."""
    COUNTRY_REGION = "CountryRegion"
    """CountryRegion."""
    CRATER = "Crater"
    """Crater."""
    CULTURAL_REGION = "CulturalRegion"
    """CulturalRegion."""
    DAM = "Dam"
    """Dam."""
    DELTA = "Delta"
    """Delta."""
    DESERT = "Desert"
    """Desert."""
    DRAINAGE_BASIN = "DrainageBasin"
    """DrainageBasin."""
    DUNE = "Dune"
    """Dune."""
    FACILITY_STRUCTURE = "FacilityStructure"
    """FacilityStructure."""
    FERRY_TERMINAL = "FerryTerminal"
    """FerryTerminal."""
    FINANCIAL_STRUCTURE = "FinancialStructure"
    """FinancialStructure."""
    FIRE_STATION = "FireStation"
    """FireStation."""
    FOREST = "Forest"
    """Forest."""
    FORT = "Fort"
    """Fort."""
    GARDEN = "Garden"
    """Garden."""
    GEYSER = "Geyser"
    """Geyser."""
    GLACIER = "Glacier"
    """Glacier."""
    GOLF_COURSE = "GolfCourse"
    """GolfCourse."""
    GREATER_POPULATED_PLACE = "GreaterPopulatedPlace"
    """GreaterPopulatedPlace."""
    HIGHER_EDUCATION_FACILITY = "HigherEducationFacility"
    """HigherEducationFacility."""
    HISTORICAL_SITE = "HistoricalSite"
    """HistoricalSite."""
    HOSPITAL = "Hospital"
    """Hospital."""
    HOT_SPRING = "HotSpring"
    """HotSpring."""
    ICE = "Ice"
    """Ice."""
    INDIGENOUS_PEOPLES_RESERVE = "IndigenousPeoplesReserve"
    """IndigenousPeoplesReserve."""
    INDUSTRIAL_STRUCTURE = "IndustrialStructure"
    """IndustrialStructure."""
    ISLAND = "Island"
    """Island."""
    ISTHMUS = "Isthmus"
    """Isthmus."""
    LAKE = "Lake"
    """Lake."""
    LAND_AREA = "LandArea"
    """LandArea."""
    LANDFORM = "Landform"
    """Landform."""
    LANDMARK_BUILDING = "LandmarkBuilding"
    """LandmarkBuilding."""
    LIBRARY = "Library"
    """Library."""
    LIGHTHOUSE = "Lighthouse"
    """Lighthouse."""
    MARINA = "Marina"
    """Marina."""
    MARKET = "Market"
    """Market."""
    MEDICAL_STRUCTURE = "MedicalStructure"
    """MedicalStructure."""
    METRO_STATION = "MetroStation"
    """MetroStation."""
    MILITARY_BASE = "MilitaryBase"
    """MilitaryBase."""
    MISSION = "Mission"
    """Mission."""
    MONUMENT = "Monument"
    """Monument."""
    MOSQUE = "Mosque"
    """Mosque."""
    MOUNTAIN = "Mountain"
    """Mountain."""
    MOUNTAIN_RANGE = "MountainRange"
    """MountainRange."""
    MULTI_MODAL_STATION = "MultiModalStation"
    """MultiModalStation."""
    MUSEUM = "Museum"
    """Museum."""
    NAUTICAL_STRUCTURE = "NauticalStructure"
    """NauticalStructure."""
    NEIGHBORHOOD = "Neighborhood"
    """Neighborhood."""
    OASIS = "Oasis"
    """Oasis."""
    OBSERVATION_POINT = "ObservationPoint"
    """ObservationPoint."""
    OCEAN = "Ocean"
    """Ocean."""
    OFFICE_BUILDING = "OfficeBuilding"
    """OfficeBuilding."""
    OTHER = "Other"
    """Other."""
    PARK = "Park"
    """Park."""
    PARKING_STRUCTURE = "ParkingStructure"
    """ParkingStructure."""
    PASSEnum = "Pass"
    """Pass."""
    PENINSULA = "Peninsula"
    """Peninsula."""
    PLAIN = "Plain"
    """Plain."""
    PLANET = "Planet"
    """Planet."""
    PLATEAU = "Plateau"
    """Plateau."""
    PLAYGROUND = "Playground"
    """Playground."""
    PLAYING_FIELD = "PlayingField"
    """PlayingField."""
    POLE = "Pole"
    """Pole."""
    POLITICAL_UNIT = "PoliticalUnit"
    """PoliticalUnit."""
    POPULATED_PLACE = "PopulatedPlace"
    """PopulatedPlace."""
    PORT = "Port"
    """Port."""
    POSTCODE1 = "Postcode1"
    """Postcode1."""
    PROMONTORY = "Promontory"
    """Promontory."""
    RACE_TRACK = "RaceTrack"
    """RaceTrack."""
    RAILWAY_STATION = "RailwayStation"
    """RailwayStation."""
    REEF = "Reef"
    """Reef."""
    RELIGIOUS_STRUCTURE = "ReligiousStructure"
    """ReligiousStructure."""
    RESERVE = "Reserve"
    """Reserve."""
    RESIDENTIAL_STRUCTURE = "ResidentialStructure"
    """ResidentialStructure."""
    RIVER = "River"
    """River."""
    ROAD_BLOCK = "RoadBlock"
    """RoadBlock."""
    RUIN = "Ruin"
    """Ruin."""
    SCIENTIFIC_RESEARCH_BASE = "ScientificResearchBase"
    """ScientificResearchBase."""
    SEA = "Sea"
    """Sea."""
    SEAPLANE_LANDING_AREA = "SeaplaneLandingArea"
    """SeaplaneLandingArea."""
    SHRINE = "Shrine"
    """Shrine."""
    SKI_AREA = "SkiArea"
    """SkiArea."""
    SPRING = "Spring"
    """Spring."""
    STADIUM = "Stadium"
    """Stadium."""
    STATISTICAL_DISTRICT = "StatisticalDistrict"
    """StatisticalDistrict."""
    TEMPLE = "Temple"
    """Temple."""
    THEATER = "Theater"
    """Theater."""
    TOURIST_RAILWAY = "TouristRailway"
    """TouristRailway."""
    TOURIST_STRUCTURE = "TouristStructure"
    """TouristStructure."""
    TRAILHEAD = "Trailhead"
    """Trailhead."""
    TRANSPORTATION_STRUCTURE = "TransportationStructure"
    """TransportationStructure."""
    TUNNEL = "Tunnel"
    """Tunnel."""
    VALLEY = "Valley"
    """Valley."""
    VOLCANO = "Volcano"
    """Volcano."""
    WALKWAY = "Walkway"
    """Walkway."""
    WALL = "Wall"
    """Wall."""
    WATERFALL = "Waterfall"
    """Waterfall."""
    WATER_FEATURE = "WaterFeature"
    """WaterFeature."""
    WETLAND = "Wetland"
    """Wetland."""
    WINERY = "Winery"
    """Winery."""
    ZOO = "Zoo"
    """Zoo."""


class AutocompleteResultTypeGroups(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Address or Place."""

    ADDRESS = "Address"
    """A specific address location. Supported types are:
    
    
    
    * Address
    * RoadBlock."""
    PLACE = "Place"
    """All other types belong to the Place type group. These may include entities such as
    AdminDivision1, Neighborhood, PopulatedPlace, and more."""


class BoundaryResultType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Type of BoundaryResultType."""

    COUNTRY_REGION = "countryRegion"
    """Country or region."""
    ADMIN_DISTRICT = "adminDistrict"
    """First administrative level within the country/region level, such as a state or a province."""
    ADMIN_DISTRICT2 = "adminDistrict2"
    """Second administrative level within the country/region level, such as a county."""
    POSTAL_CODE = "postalCode"
    """The smallest post code category, such as a zip code."""
    POSTAL_CODE2 = "postalCode2"
    """The next largest post code category after postalCode that is created by aggregating postalCode
    areas."""
    POSTAL_CODE3 = "postalCode3"
    """The next largest post code category after postalCode2 that is created by aggregating
    postalCode2 areas."""
    POSTAL_CODE4 = "postalCode4"
    """The next largest post code category after postalCode3 that is created by aggregating
    postalCode3 areas."""
    NEIGHBORHOOD = "neighborhood"
    """A section of a populated place that is typically well-known, but often with indistinct
    boundaries."""
    LOCALITY = "locality"
    """A concentrated area of human settlement, such as a city, town or village."""


class CalculationMethod(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The method that was used to compute the geocode point."""

    INTERPOLATION = "Interpolation"
    """The geocode point was matched to a point on a road using interpolation."""
    INTERPOLATION_OFFSET = "InterpolationOffset"
    """The geocode point was matched to a point on a road using interpolation with an additional
    offset to shift the point to the side of the street."""
    PARCEL = "Parcel"
    """The geocode point was matched to the center of a parcel."""
    ROOFTOP = "Rooftop"
    """The geocode point was matched to the rooftop of a building."""


class Confidence(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The level of confidence that the geocoded location result is a match. Use this
    value with the match code to determine for more complete information about the
    match.

    The confidence of a geocoded location is based on many factors including the
    relative importance of the geocoded location and the user’s location, if
    specified.
    """

    HIGH = "High"
    """If the confidence is set to ``High``, one or more strong matches were found.
    Multiple ``High`` confidence matches are sorted in ranked order by importance
    when applicable. For example, landmarks have importance but addresses do not.
    
    If a request includes a location or a view, then the ranking may change
    appropriately. For example, a location query for "Paris" returns "Paris,
    France" and "Paris, TX" both with ``High`` confidence. "Paris, France" is always
    ranked first due to importance unless a user location indicates that the user
    is in or very close to Paris, TX or the map view indicates that the user is
    searching in that area."""
    MEDIUM = "Medium"
    """In some situations, the returned match may not be at the same level as the
    information provided in the request. For example, a request may specify address
    information and the geocode service may only be able to match a postal code. In
    this case, if the geocode service has a confidence that the postal code matches
    the data, the confidence is set to ``Medium`` and the match code is set to
    ``UpHierarchy`` to specify that it could not match all of the information and had
    to search up-hierarchy.
    
    If the location information in the query is ambiguous, and there is no
    additional information to rank the locations (such as user location or the
    relative importance of the location), the confidence is set to ``Medium``. For
    example, a location query for "148th Ave, Bellevue" may return "148th Ave SE"
    and "148th Ave NE" both with ``Medium`` confidence.
    
    If the location information in the query does not provide enough information to
    geocode a specific location, a less precise location value may be returned and
    the confidence is set to ``Medium``. For example, if an address is provided, but
    a match is not found for the house number, the geocode result with a Roadblock
    entity type may be returned."""
    LOW = "Low"
    """Low."""


class FeatureCollection(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies the ``GeoJSON`` type. The only supported object type is ``FeatureCollection``. For
    more information, see `RFC 7946 <https://www.rfc-editor.org/rfc/rfc7946>`_.
    """

    FEATURE_COLLECTION = "FeatureCollection"
    """Specifies the ``GeoJSON`` ``FeatureCollection`` object type."""


class FeatureType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The type of a feature must be Feature."""

    FEATURE = "Feature"
    """Specifies the ``GeoJSON`` Feature object type."""


class GeoJsonObjectType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies the ``GeoJSON`` type. Must be one of the nine valid GeoJSON object types - Point,
    MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection, Feature and
    FeatureCollection.
    """

    GEO_JSON_POINT = "Point"
    """``GeoJSON Point`` geometry."""
    GEO_JSON_MULTI_POINT = "MultiPoint"
    """``GeoJSON MultiPoint`` geometry."""
    GEO_JSON_LINE_STRING = "LineString"
    """``GeoJSON LineString`` geometry."""
    GEO_JSON_MULTI_LINE_STRING = "MultiLineString"
    """``GeoJSON MultiLineString`` geometry."""
    GEO_JSON_POLYGON = "Polygon"
    """``GeoJSON Polygon`` geometry."""
    GEO_JSON_MULTI_POLYGON = "MultiPolygon"
    """``GeoJSON MultiPolygon`` geometry."""
    GEO_JSON_GEOMETRY_COLLECTION = "GeometryCollection"
    """``GeoJSON GeometryCollection`` geometry."""
    GEO_JSON_FEATURE = "Feature"
    """``GeoJSON Feature`` object."""
    GEO_JSON_FEATURE_COLLECTION = "FeatureCollection"
    """``GeoJSON FeatureCollection`` object."""


class MatchCodes(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Type of MatchCodes."""

    GOOD = "Good"
    """Good."""
    AMBIGUOUS = "Ambiguous"
    """Ambiguous."""
    UP_HIERARCHY = "UpHierarchy"
    """UpHierarchy."""


class Resolution(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Type of Resolution."""

    SMALL = "small"
    """Return the boundary geometry with the least amount of points."""
    MEDIUM = "medium"
    """Return the boundary geometry with more or the same amount of points as small."""
    LARGE = "large"
    """Return the boundary geometry with more or the same amount of points as medium."""
    HUGE = "huge"
    """Return the boundary geometry with more or the same amount of points as large."""


class ResultType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Type of ResultType."""

    ADDRESS = "Address"
    """Address."""
    NEIGHBORHOOD = "Neighborhood"
    """Neighborhood."""
    POPULATED_PLACE = "PopulatedPlace"
    """PopulatedPlace."""
    POSTCODE1 = "Postcode1"
    """Postcode1."""
    ADMIN_DIVISION1 = "AdminDivision1"
    """AdminDivision1."""
    ADMIN_DIVISION2 = "AdminDivision2"
    """AdminDivision2."""
    COUNTRY_REGION = "CountryRegion"
    """CountryRegion."""


class ReverseGeocodingResultType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Type of ReverseGeocodingResultType."""

    ADDRESS = "Address"
    """Address."""
    NEIGHBORHOOD = "Neighborhood"
    """Neighborhood."""
    POPULATED_PLACE = "PopulatedPlace"
    """PopulatedPlace."""
    POSTCODE1 = "Postcode1"
    """Postcode1."""
    ADMIN_DIVISION1 = "AdminDivision1"
    """AdminDivision1."""
    ADMIN_DIVISION2 = "AdminDivision2"
    """AdminDivision2."""
    COUNTRY_REGION = "CountryRegion"
    """CountryRegion."""


class UsageType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Type of UsageType."""

    DISPLAY = "Display"
    """Display."""
    ROUTE = "Route"
    """Route."""
