# pylint: disable=line-too-long,useless-suppression,too-many-lines
# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
# pylint: disable=useless-super-delegation

from typing import Any, Literal, Mapping, Optional, TYPE_CHECKING, Union, overload

from .._utils.model_base import Model as _Model, rest_discriminator, rest_field
from ._enums import GeoJsonObjectType

if TYPE_CHECKING:
    from .. import models as _models


class Address(_Model):
    """The address of the result.

    :ivar address_line: AddressLine that includes street name and number.
    :vartype address_line: str
    :ivar locality: Locality property.
    :vartype locality: str
    :ivar neighborhood: Neighborhood property.
    :vartype neighborhood: str
    :ivar admin_districts: The subdivision name in the country or region for an address. This
     element is typically treated as the first order administrative subdivision, but in some cases
     it also contains the second, third, or fourth order subdivision in a country, dependency, or
     region.
    :vartype admin_districts: list[~azure.maps.search.models.AddressAdminDistrictsItem]
    :ivar postal_code: Postal code property.
    :vartype postal_code: str
    :ivar country_region: Country or region with its name and ISO code.
    :vartype country_region: ~azure.maps.search.models.AddressCountryRegion
    :ivar formatted_address: Formatted address property.
    :vartype formatted_address: str
    :ivar street_name: The name of the street from formattedAddress.
    :vartype street_name: str
    :ivar street_number: The number in the street, if available, from formattedAddress.
    :vartype street_number: str
    :ivar intersection: The address of the result.
    :vartype intersection: ~azure.maps.search.models.Intersection
    """

    address_line: Optional[str] = rest_field(
        name="addressLine", visibility=["read", "create", "update", "delete", "query"]
    )
    """AddressLine that includes street name and number."""
    locality: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Locality property."""
    neighborhood: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Neighborhood property."""
    admin_districts: Optional[list["_models.AddressAdminDistrictsItem"]] = rest_field(
        name="adminDistricts", visibility=["read", "create", "update", "delete", "query"]
    )
    """The subdivision name in the country or region for an address. This element is typically treated
     as the first order administrative subdivision, but in some cases it also contains the second,
     third, or fourth order subdivision in a country, dependency, or region."""
    postal_code: Optional[str] = rest_field(
        name="postalCode", visibility=["read", "create", "update", "delete", "query"]
    )
    """Postal code property."""
    country_region: Optional["_models.AddressCountryRegion"] = rest_field(
        name="countryRegion", visibility=["read", "create", "update", "delete", "query"]
    )
    """Country or region with its name and ISO code."""
    formatted_address: Optional[str] = rest_field(
        name="formattedAddress", visibility=["read", "create", "update", "delete", "query"]
    )
    """Formatted address property."""
    street_name: Optional[str] = rest_field(
        name="streetName", visibility=["read", "create", "update", "delete", "query"]
    )
    """The name of the street from formattedAddress."""
    street_number: Optional[str] = rest_field(
        name="streetNumber", visibility=["read", "create", "update", "delete", "query"]
    )
    """The number in the street, if available, from formattedAddress."""
    intersection: Optional["_models.Intersection"] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """The address of the result."""

    @overload
    def __init__(
        self,
        *,
        address_line: Optional[str] = None,
        locality: Optional[str] = None,
        neighborhood: Optional[str] = None,
        admin_districts: Optional[list["_models.AddressAdminDistrictsItem"]] = None,
        postal_code: Optional[str] = None,
        country_region: Optional["_models.AddressCountryRegion"] = None,
        formatted_address: Optional[str] = None,
        street_name: Optional[str] = None,
        street_number: Optional[str] = None,
        intersection: Optional["_models.Intersection"] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class AddressAdminDistrictsItem(_Model):
    """AddressAdminDistrictsItem.

    :ivar name: The name for the corresponding adminDistrict field, For adminDistrict[0], this
     could be full name of state such as Washington, For adminDistrict[1], this could be the full
     name of the county.
    :vartype name: str
    :ivar short_name: The short name for the corresponding adminDistrict field, For
     adminDistrict[0], this could be short name of state such as WA, For adminDistrict[1], this
     could be the short name of the county.
    :vartype short_name: str
    """

    name: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """The name for the corresponding adminDistrict field, For adminDistrict[0], this could be full
     name of state such as Washington, For adminDistrict[1], this could be the full name of the
     county."""
    short_name: Optional[str] = rest_field(name="shortName", visibility=["read", "create", "update", "delete", "query"])
    """The short name for the corresponding adminDistrict field, For adminDistrict[0], this could be
     short name of state such as WA, For adminDistrict[1], this could be the short name of the
     county."""

    @overload
    def __init__(
        self,
        *,
        name: Optional[str] = None,
        short_name: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class AddressCountryRegion(_Model):
    """Country or region with its name and ISO code.

    :ivar iso: ISO of country/region.
    :vartype iso: str
    :ivar name: name of country/region.
    :vartype name: str
    """

    iso: Optional[str] = rest_field(name="ISO", visibility=["read", "create", "update", "delete", "query"])
    """ISO of country/region."""
    name: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """name of country/region."""

    @overload
    def __init__(
        self,
        *,
        iso: Optional[str] = None,
        name: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class AutocompleteFeature(_Model):
    """Features of Autocomplete Result.

    :ivar type: Specifies the ``GeoJSON`` type. The only supported object type is Feature. For more
     information, see `RFC 7946 <https://www.rfc-editor.org/rfc/rfc7946>`_. Required. "Feature"
    :vartype type: str or ~azure.maps.search.models.FeatureTypeEnum
    :ivar geometry: A valid ``GeoJSON Point`` geometry type. Please refer to `RFC 7946
     <https://tools.ietf.org/html/rfc7946#section-3.1.2>`_ for details.
    :vartype geometry: ~azure.maps.search.models.GeoJsonPoint
    :ivar properties: Properties of Autocomplete Result. Required.
    :vartype properties: ~azure.maps.search.models.AutocompleteProperties
    """

    type: Union[str, "_models.FeatureTypeEnum"] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Specifies the ``GeoJSON`` type. The only supported object type is Feature. For more
     information, see `RFC 7946 <https://www.rfc-editor.org/rfc/rfc7946>`_. Required. \"Feature\""""
    geometry: Optional["_models.GeoJsonPoint"] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """A valid ``GeoJSON Point`` geometry type. Please refer to `RFC 7946
     <https://tools.ietf.org/html/rfc7946#section-3.1.2>`_ for details."""
    properties: "_models.AutocompleteProperties" = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """Properties of Autocomplete Result. Required."""

    @overload
    def __init__(
        self,
        *,
        type: Union[str, "_models.FeatureTypeEnum"],
        properties: "_models.AutocompleteProperties",
        geometry: Optional["_models.GeoJsonPoint"] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class AutocompleteProperties(_Model):
    """Properties of Autocomplete Result.

    :ivar type_group: Address or Place. Known values are: "Address" and "Place".
    :vartype type_group: str or ~azure.maps.search.models.AutocompleteResultTypeGroupsEnum
    :ivar type: Type of suggestion. Known values are: "Address", "AdminDivision1",
     "AdminDivision2", "AdminDivision3", "AdministrativeBuilding", "Airport", "AirportTerminal",
     "AmusementPark", "AncientSite", "Aquarium", "Archipelago", "Basin", "Battlefield", "Bay",
     "Beach", "Bridge", "BusinessStructure", "Camp", "Canal", "Casino", "Castle", "Cave",
     "Cemetery", "Channel", "Church", "Cliff", "Coast", "CommunityCenter", "Continent",
     "CountryRegion", "Crater", "CulturalRegion", "Dam", "Delta", "Desert", "DrainageBasin", "Dune",
     "FacilityStructure", "FerryTerminal", "FinancialStructure", "FireStation", "Forest", "Fort",
     "Garden", "Geyser", "Glacier", "GolfCourse", "GreaterPopulatedPlace",
     "HigherEducationFacility", "HistoricalSite", "Hospital", "HotSpring", "Ice",
     "IndigenousPeoplesReserve", "IndustrialStructure", "Island", "Isthmus", "Lake", "LandArea",
     "Landform", "LandmarkBuilding", "Library", "Lighthouse", "Marina", "Market",
     "MedicalStructure", "MetroStation", "MilitaryBase", "Mission", "Monument", "Mosque",
     "Mountain", "MountainRange", "MultiModalStation", "Museum", "NauticalStructure",
     "Neighborhood", "Oasis", "ObservationPoint", "Ocean", "OfficeBuilding", "Other", "Park",
     "ParkingStructure", "Pass", "Peninsula", "Plain", "Planet", "Plateau", "Playground",
     "PlayingField", "Pole", "PoliticalUnit", "PopulatedPlace", "Port", "Postcode1", "Promontory",
     "RaceTrack", "RailwayStation", "Reef", "ReligiousStructure", "Reserve", "ResidentialStructure",
     "River", "RoadBlock", "Ruin", "ScientificResearchBase", "Sea", "SeaplaneLandingArea", "Shrine",
     "SkiArea", "Spring", "Stadium", "StatisticalDistrict", "Temple", "Theater", "TouristRailway",
     "TouristStructure", "Trailhead", "TransportationStructure", "Tunnel", "Valley", "Volcano",
     "Walkway", "Wall", "Waterfall", "WaterFeature", "Wetland", "Winery", and "Zoo".
    :vartype type: str or ~azure.maps.search.models.AutocompleteResultTypeEnum
    :ivar address: The address of the result.
    :vartype address: ~azure.maps.search.models.Address
    :ivar name: The name of the place. This field will not appear if the returned type is Address.
    :vartype name: str
    """

    type_group: Optional[Union[str, "_models.AutocompleteResultTypeGroupsEnum"]] = rest_field(
        name="typeGroup", visibility=["read", "create", "update", "delete", "query"]
    )
    """Address or Place. Known values are: \"Address\" and \"Place\"."""
    type: Optional[Union[str, "_models.AutocompleteResultTypeEnum"]] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """Type of suggestion. Known values are: \"Address\", \"AdminDivision1\", \"AdminDivision2\",
     \"AdminDivision3\", \"AdministrativeBuilding\", \"Airport\", \"AirportTerminal\",
     \"AmusementPark\", \"AncientSite\", \"Aquarium\", \"Archipelago\", \"Basin\", \"Battlefield\",
     \"Bay\", \"Beach\", \"Bridge\", \"BusinessStructure\", \"Camp\", \"Canal\", \"Casino\",
     \"Castle\", \"Cave\", \"Cemetery\", \"Channel\", \"Church\", \"Cliff\", \"Coast\",
     \"CommunityCenter\", \"Continent\", \"CountryRegion\", \"Crater\", \"CulturalRegion\", \"Dam\",
     \"Delta\", \"Desert\", \"DrainageBasin\", \"Dune\", \"FacilityStructure\", \"FerryTerminal\",
     \"FinancialStructure\", \"FireStation\", \"Forest\", \"Fort\", \"Garden\", \"Geyser\",
     \"Glacier\", \"GolfCourse\", \"GreaterPopulatedPlace\", \"HigherEducationFacility\",
     \"HistoricalSite\", \"Hospital\", \"HotSpring\", \"Ice\", \"IndigenousPeoplesReserve\",
     \"IndustrialStructure\", \"Island\", \"Isthmus\", \"Lake\", \"LandArea\", \"Landform\",
     \"LandmarkBuilding\", \"Library\", \"Lighthouse\", \"Marina\", \"Market\",
     \"MedicalStructure\", \"MetroStation\", \"MilitaryBase\", \"Mission\", \"Monument\",
     \"Mosque\", \"Mountain\", \"MountainRange\", \"MultiModalStation\", \"Museum\",
     \"NauticalStructure\", \"Neighborhood\", \"Oasis\", \"ObservationPoint\", \"Ocean\",
     \"OfficeBuilding\", \"Other\", \"Park\", \"ParkingStructure\", \"Pass\", \"Peninsula\",
     \"Plain\", \"Planet\", \"Plateau\", \"Playground\", \"PlayingField\", \"Pole\",
     \"PoliticalUnit\", \"PopulatedPlace\", \"Port\", \"Postcode1\", \"Promontory\", \"RaceTrack\",
     \"RailwayStation\", \"Reef\", \"ReligiousStructure\", \"Reserve\", \"ResidentialStructure\",
     \"River\", \"RoadBlock\", \"Ruin\", \"ScientificResearchBase\", \"Sea\",
     \"SeaplaneLandingArea\", \"Shrine\", \"SkiArea\", \"Spring\", \"Stadium\",
     \"StatisticalDistrict\", \"Temple\", \"Theater\", \"TouristRailway\", \"TouristStructure\",
     \"Trailhead\", \"TransportationStructure\", \"Tunnel\", \"Valley\", \"Volcano\", \"Walkway\",
     \"Wall\", \"Waterfall\", \"WaterFeature\", \"Wetland\", \"Winery\", and \"Zoo\"."""
    address: Optional["_models.Address"] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """The address of the result."""
    name: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """The name of the place. This field will not appear if the returned type is Address."""

    @overload
    def __init__(
        self,
        *,
        type_group: Optional[Union[str, "_models.AutocompleteResultTypeGroupsEnum"]] = None,
        type: Optional[Union[str, "_models.AutocompleteResultTypeEnum"]] = None,
        address: Optional["_models.Address"] = None,
        name: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class AutocompleteResponse(_Model):
    """This object is returned from a successful autocomplete call.

    :ivar type: Specifies the ``GeoJSON`` type. The only supported object type is
     ``FeatureCollection``. For more information, see `RFC 7946
     <https://www.rfc-editor.org/rfc/rfc7946>`_. "FeatureCollection"
    :vartype type: str or ~azure.maps.search.models.FeatureCollectionEnum
    :ivar features: Features of the autocomplete result.
    :vartype features: list[~azure.maps.search.models.AutocompleteFeature]
    :ivar next_link: The is the link to the next page of the features returned. If it's the last
     page, no this field.
    :vartype next_link: str
    """

    type: Optional[Union[str, "_models.FeatureCollectionEnum"]] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """Specifies the ``GeoJSON`` type. The only supported object type is ``FeatureCollection``. For
     more information, see `RFC 7946 <https://www.rfc-editor.org/rfc/rfc7946>`_.
     \"FeatureCollection\""""
    features: Optional[list["_models.AutocompleteFeature"]] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """Features of the autocomplete result."""
    next_link: Optional[str] = rest_field(name="nextLink", visibility=["read", "create", "update", "delete", "query"])
    """The is the link to the next page of the features returned. If it's the last page, no this
     field."""

    @overload
    def __init__(
        self,
        *,
        type: Optional[Union[str, "_models.FeatureCollectionEnum"]] = None,
        features: Optional[list["_models.AutocompleteFeature"]] = None,
        next_link: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class Boundary(_Model):
    """``GeoJSON GeocodingFeature`` object that describe the boundaries of a
    geographical area. Geometry of the feature is described with
    ``GeoJSON GeometryCollection``.

    Please note, the service typically returns a GeometryCollection with Polygon or
    MultiPolygon sub-types.

    :ivar type: The type of a feature must be Feature. "Feature"
    :vartype type: str or ~azure.maps.search.models.FeatureTypeEnum
    :ivar geometry: A valid ``GeoJSON GeometryCollection`` object type. Please refer to `RFC 7946
     <https://tools.ietf.org/html/rfc7946#section-3.1.8>`_ for details. Required.
    :vartype geometry: ~azure.maps.search.models.GeoJsonGeometryCollection
    :ivar properties: Properties of a Boundary object.
    :vartype properties: ~azure.maps.search.models.BoundaryProperties
    """

    type: Optional[Union[str, "_models.FeatureTypeEnum"]] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """The type of a feature must be Feature. \"Feature\""""
    geometry: "_models.GeoJsonGeometryCollection" = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """A valid ``GeoJSON GeometryCollection`` object type. Please refer to `RFC 7946
     <https://tools.ietf.org/html/rfc7946#section-3.1.8>`_ for details. Required."""
    properties: Optional["_models.BoundaryProperties"] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """Properties of a Boundary object."""

    @overload
    def __init__(
        self,
        *,
        geometry: "_models.GeoJsonGeometryCollection",
        type: Optional[Union[str, "_models.FeatureTypeEnum"]] = None,
        properties: Optional["_models.BoundaryProperties"] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class BoundaryProperties(_Model):
    """Properties of a Boundary object.

    :ivar name: The name associated with the geographical area.
    :vartype name: str
    :ivar copyright: The copyright string.
    :vartype copyright: str
    :ivar copyright_url: A URL that lists many of the data providers for Azure Maps and their
     related copyright information.
    :vartype copyright_url: str
    :ivar geometries_copyright: A collection of copyright information for each geometry of the
     Boundary object in the same order they appear.
    :vartype geometries_copyright: list[~azure.maps.search.models.GeometryCopyright]
    """

    name: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """The name associated with the geographical area."""
    copyright: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """The copyright string."""
    copyright_url: Optional[str] = rest_field(
        name="copyrightURL", visibility=["read", "create", "update", "delete", "query"]
    )
    """A URL that lists many of the data providers for Azure Maps and their related copyright
     information."""
    geometries_copyright: Optional[list["_models.GeometryCopyright"]] = rest_field(
        name="geometriesCopyright", visibility=["read", "create", "update", "delete", "query"]
    )
    """A collection of copyright information for each geometry of the Boundary object in the same
     order they appear."""

    @overload
    def __init__(
        self,
        *,
        name: Optional[str] = None,
        copyright: Optional[str] = None,
        copyright_url: Optional[str] = None,
        geometries_copyright: Optional[list["_models.GeometryCopyright"]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class ErrorAdditionalInfo(_Model):
    """The resource management error additional info.

    :ivar type: The additional info type.
    :vartype type: str
    :ivar info: The additional info.
    :vartype info: dict[str, any]
    """

    type: Optional[str] = rest_field(visibility=["read"])
    """The additional info type."""
    info: Optional[dict[str, Any]] = rest_field(visibility=["read"])
    """The additional info."""


class ErrorDetail(_Model):
    """The error detail.

    :ivar code: The error code.
    :vartype code: str
    :ivar message: The error message.
    :vartype message: str
    :ivar target: The error target.
    :vartype target: str
    :ivar details: The error details.
    :vartype details: list[~azure.maps.search.models.ErrorDetail]
    :ivar additional_info: The error additional info.
    :vartype additional_info: list[~azure.maps.search.models.ErrorAdditionalInfo]
    """

    code: Optional[str] = rest_field(visibility=["read"])
    """The error code."""
    message: Optional[str] = rest_field(visibility=["read"])
    """The error message."""
    target: Optional[str] = rest_field(visibility=["read"])
    """The error target."""
    details: Optional[list["_models.ErrorDetail"]] = rest_field(visibility=["read"])
    """The error details."""
    additional_info: Optional[list["_models.ErrorAdditionalInfo"]] = rest_field(
        name="additionalInfo", visibility=["read"]
    )
    """The error additional info."""


class FeaturesItem(_Model):
    """FeaturesItem.

    :ivar type: The type of a feature must be Feature. "Feature"
    :vartype type: str or ~azure.maps.search.models.FeatureTypeEnum
    :ivar id: ID for feature returned.
    :vartype id: str
    :ivar properties:
    :vartype properties: ~azure.maps.search.models.FeaturesItemProperties
    :ivar geometry: A valid ``GeoJSON Point`` geometry type. Please refer to `RFC 7946
     <https://tools.ietf.org/html/rfc7946#section-3.1.2>`_ for details. Required.
    :vartype geometry: ~azure.maps.search.models.GeoJsonPoint
    :ivar bbox: Bounding box. Projection used - EPSG:3857. Please refer to `RFC 7946
     <https://datatracker.ietf.org/doc/html/rfc7946#section-5>`_ for details.
    :vartype bbox: list[float]
    """

    type: Optional[Union[str, "_models.FeatureTypeEnum"]] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """The type of a feature must be Feature. \"Feature\""""
    id: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """ID for feature returned."""
    properties: Optional["_models.FeaturesItemProperties"] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    geometry: "_models.GeoJsonPoint" = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """A valid ``GeoJSON Point`` geometry type. Please refer to `RFC 7946
     <https://tools.ietf.org/html/rfc7946#section-3.1.2>`_ for details. Required."""
    bbox: Optional[list[float]] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Bounding box. Projection used - EPSG:3857. Please refer to `RFC 7946
     <https://datatracker.ietf.org/doc/html/rfc7946#section-5>`_ for details."""

    @overload
    def __init__(
        self,
        *,
        geometry: "_models.GeoJsonPoint",
        type: Optional[Union[str, "_models.FeatureTypeEnum"]] = None,
        id: Optional[str] = None,  # pylint: disable=redefined-builtin
        properties: Optional["_models.FeaturesItemProperties"] = None,
        bbox: Optional[list[float]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class FeaturesItemProperties(_Model):
    """FeaturesItemProperties.

    :ivar type: One of:

     * Address
     * RoadBlock
     * RoadIntersection
     * Neighborhood
     * PopulatedPlace
     * Postcode1
     * AdminDivision1
     * AdminDivision2
     * CountryRegion.
    :vartype type: str
    :ivar confidence: The level of confidence that the geocoded location result is a match. Use
     this
     value with the match code to determine for more complete information about the
     match.

     The confidence of a geocoded location is based on many factors including the
     relative importance of the geocoded location and the user’s location, if
     specified. Known values are: "High", "Medium", and "Low".
    :vartype confidence: str or ~azure.maps.search.models.ConfidenceEnum
    :ivar match_codes: One or more match code values that represent the geocoding level for each
     location in the response.

     For example, a geocoded location with match codes of ``Good`` and ``Ambiguous``
     means that more than one geocode location was found for the location
     information and that the geocode service did not have search up-hierarchy to
     find a match.

     Similarly, a geocoded location with match codes of ``Ambiguous`` and
     ``UpHierarchy`` implies that a geocode location could not be found that matched
     all the provided location information, so the geocode service had to search
     up-hierarchy and found multiple matches at that level. An example of up an
     ``Ambiguous`` and ``UpHierarchy`` result is when you provide complete address
     information, but the geocode service cannot locate a match for the street
     address and instead returns information for more than one RoadBlock value.

     The possible values are:

     ``Good``: The location has only one match or all returned matches are considered
     strong matches. For example, a query for New York returns several Good matches.

     ``Ambiguous``: The location is one of a set of possible matches. For example,
     when you query for the street address 128 Main St., the response may return two
     locations for 128 North Main St. and 128 South Main St. because there is not
     enough information to determine which option to choose.

     ``UpHierarchy``: The location represents a move up the geographic hierarchy. This
     occurs when a match for the location request was not found, so a less precise
     result is returned. For example, if a match for the requested address cannot be
     found, then a match code of ``UpHierarchy`` with a RoadBlock entity type may be
     returned.
    :vartype match_codes: list[str or ~azure.maps.search.models.MatchCodesEnum]
    :ivar address: The address of the result.
    :vartype address: ~azure.maps.search.models.Address
    :ivar geocode_points: A collection of geocode points that differ in how they were calculated
     and their suggested use.
    :vartype geocode_points: list[~azure.maps.search.models.GeocodePointsItem]
    """

    type: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """One of:
 
      * Address
      * RoadBlock
      * RoadIntersection
      * Neighborhood
      * PopulatedPlace
      * Postcode1
      * AdminDivision1
      * AdminDivision2
      * CountryRegion."""
    confidence: Optional[Union[str, "_models.ConfidenceEnum"]] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """The level of confidence that the geocoded location result is a match. Use this
     value with the match code to determine for more complete information about the
     match.
     
     The confidence of a geocoded location is based on many factors including the
     relative importance of the geocoded location and the user’s location, if
     specified. Known values are: \"High\", \"Medium\", and \"Low\"."""
    match_codes: Optional[list[Union[str, "_models.MatchCodesEnum"]]] = rest_field(
        name="matchCodes", visibility=["read", "create", "update", "delete", "query"]
    )
    """One or more match code values that represent the geocoding level for each
     location in the response.
     
     For example, a geocoded location with match codes of ``Good`` and ``Ambiguous``
     means that more than one geocode location was found for the location
     information and that the geocode service did not have search up-hierarchy to
     find a match.
     
     Similarly, a geocoded location with match codes of ``Ambiguous`` and
     ``UpHierarchy`` implies that a geocode location could not be found that matched
     all the provided location information, so the geocode service had to search
     up-hierarchy and found multiple matches at that level. An example of up an
     ``Ambiguous`` and ``UpHierarchy`` result is when you provide complete address
     information, but the geocode service cannot locate a match for the street
     address and instead returns information for more than one RoadBlock value.
     
     The possible values are:
     
     ``Good``: The location has only one match or all returned matches are considered
     strong matches. For example, a query for New York returns several Good matches.
     
     ``Ambiguous``: The location is one of a set of possible matches. For example,
     when you query for the street address 128 Main St., the response may return two
     locations for 128 North Main St. and 128 South Main St. because there is not
     enough information to determine which option to choose.
     
     ``UpHierarchy``: The location represents a move up the geographic hierarchy. This
     occurs when a match for the location request was not found, so a less precise
     result is returned. For example, if a match for the requested address cannot be
     found, then a match code of ``UpHierarchy`` with a RoadBlock entity type may be
     returned."""
    address: Optional["_models.Address"] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """The address of the result."""
    geocode_points: Optional[list["_models.GeocodePointsItem"]] = rest_field(
        name="geocodePoints", visibility=["read", "create", "update", "delete", "query"]
    )
    """A collection of geocode points that differ in how they were calculated and their suggested use."""

    @overload
    def __init__(
        self,
        *,
        type: Optional[str] = None,
        confidence: Optional[Union[str, "_models.ConfidenceEnum"]] = None,
        match_codes: Optional[list[Union[str, "_models.MatchCodesEnum"]]] = None,
        address: Optional["_models.Address"] = None,
        geocode_points: Optional[list["_models.GeocodePointsItem"]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class GeocodePointsItem(_Model):
    """GeocodePointsItem.

    :ivar geometry: A valid ``GeoJSON Point`` geometry type. Please refer to `RFC 7946
     <https://tools.ietf.org/html/rfc7946#section-3.1.2>`_ for details.
    :vartype geometry: ~azure.maps.search.models.GeoJsonPoint
    :ivar calculation_method: The method that was used to compute the geocode point. Known values
     are: "Interpolation", "InterpolationOffset", "Parcel", and "Rooftop".
    :vartype calculation_method: str or ~azure.maps.search.models.CalculationMethodEnum
    :ivar usage_types: The best use for the geocode point. Each geocode point is defined as a
     ``Route`` point, a ``Display`` point or both. Use ``Route`` points if you are creating a route
     to the location. Use ``Display`` points if you are showing the location on a map. For example,
     if the location is a park, a ``Route`` point may specify an entrance to the park where you can
     enter with a car, and a ``Display`` point may be a point that specifies the center of the park.
    :vartype usage_types: list[str or ~azure.maps.search.models.UsageTypeEnum]
    """

    geometry: Optional["_models.GeoJsonPoint"] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """A valid ``GeoJSON Point`` geometry type. Please refer to `RFC 7946
     <https://tools.ietf.org/html/rfc7946#section-3.1.2>`_ for details."""
    calculation_method: Optional[Union[str, "_models.CalculationMethodEnum"]] = rest_field(
        name="calculationMethod", visibility=["read", "create", "update", "delete", "query"]
    )
    """The method that was used to compute the geocode point. Known values are: \"Interpolation\",
     \"InterpolationOffset\", \"Parcel\", and \"Rooftop\"."""
    usage_types: Optional[list[Union[str, "_models.UsageTypeEnum"]]] = rest_field(
        name="usageTypes", visibility=["read", "create", "update", "delete", "query"]
    )
    """The best use for the geocode point. Each geocode point is defined as a ``Route`` point, a
     ``Display`` point or both. Use ``Route`` points if you are creating a route to the location.
     Use ``Display`` points if you are showing the location on a map. For example, if the location
     is a park, a ``Route`` point may specify an entrance to the park where you can enter with a
     car, and a ``Display`` point may be a point that specifies the center of the park."""

    @overload
    def __init__(
        self,
        *,
        geometry: Optional["_models.GeoJsonPoint"] = None,
        calculation_method: Optional[Union[str, "_models.CalculationMethodEnum"]] = None,
        usage_types: Optional[list[Union[str, "_models.UsageTypeEnum"]]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class GeocodingBatchRequestBody(_Model):
    """The list of address geocoding queries/requests to process. The list can contain a max of 100
    queries and must contain at least 1 query.

    :ivar batch_items: The list of queries to process.
    :vartype batch_items: list[~azure.maps.search.models.GeocodingBatchRequestItem]
    """

    batch_items: Optional[list["_models.GeocodingBatchRequestItem"]] = rest_field(
        name="batchItems", visibility=["read", "create", "update", "delete", "query"]
    )
    """The list of queries to process."""

    @overload
    def __init__(
        self,
        *,
        batch_items: Optional[list["_models.GeocodingBatchRequestItem"]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class GeocodingBatchRequestItem(_Model):
    """Batch Query object.

    :ivar optional_id: id of the request which would show in corresponding batchItem.
    :vartype optional_id: str
    :ivar top: Maximum number of responses that will be returned. Default: 5, minimum: 1 and
     maximum: 20.
    :vartype top: int
    :ivar query: A string that contains information about a location, such as an address or
     landmark name.
    :vartype query: str
    :ivar address_line: The official street line of an address relative to the area, as specified
     by
     the locality, or postalCode, properties. Typical use of this element would be
     to provide a street address or any official address.

     This parameter should not be used when the ``query`` parameter is included in the
     request.
    :vartype address_line: str
    :ivar country_region: Signal for the geocoding result to an `ISO 3166-1 Alpha-2 region/country
     code <https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2>`_ that is specified e.g.
     FR.

     This parameter should not be used when the ``query`` parameter is included in the
     request.
    :vartype country_region: str
    :ivar bbox: A rectangular area on the earth defined as a bounding box object. The sides of
     the rectangles are defined by longitude and latitude values. For more
     information, see Location and Area Types. When you specify this parameter, the
     geographical area is taken into account when computing the results of a
     location query.

     Example: [lon1, lat1, lon2, lat2].
    :vartype bbox: list[float]
    :ivar view: A string that specifies an `ISO 3166-1 Alpha-2 region/country code
     <https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2>`_. This will alter Geopolitical disputed
     borders and labels to align with the specified user region.
    :vartype view: str
    :ivar coordinates: A point on the earth specified as a longitude and latitude. When you specify
     this parameter, the user’s location is taken into account and the results returned may be more
     relevant to the user. Example: [lon, lat].
    :vartype coordinates: list[float]
    :ivar admin_district: The country subdivision portion of an address, such as WA.

     This parameter should not be used when the ``query`` parameter is included in the
     request.
    :vartype admin_district: str
    :ivar admin_district2: The county for the structured address, such as King.

     This parameter should not be used when the ``query`` parameter is included in the
     request.
    :vartype admin_district2: str
    :ivar admin_district3: The named area for the structured address.

     This parameter should not be used when the ``query`` parameter is included in the
     request.
    :vartype admin_district3: str
    :ivar locality: The locality portion of an address, such as Seattle.

     This parameter should not be used when the ``query`` parameter is included in the
     request.
    :vartype locality: str
    :ivar postal_code: The postal code portion of an address.

     This parameter should not be used when the ``query`` parameter is included in the
     request.
    :vartype postal_code: str
    """

    optional_id: Optional[str] = rest_field(
        name="optionalId", visibility=["read", "create", "update", "delete", "query"]
    )
    """id of the request which would show in corresponding batchItem."""
    top: Optional[int] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Maximum number of responses that will be returned. Default: 5, minimum: 1 and maximum: 20."""
    query: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """A string that contains information about a location, such as an address or landmark name."""
    address_line: Optional[str] = rest_field(
        name="addressLine", visibility=["read", "create", "update", "delete", "query"]
    )
    """The official street line of an address relative to the area, as specified by
     the locality, or postalCode, properties. Typical use of this element would be
     to provide a street address or any official address.
     
     This parameter should not be used when the ``query`` parameter is included in the
     request."""
    country_region: Optional[str] = rest_field(
        name="countryRegion", visibility=["read", "create", "update", "delete", "query"]
    )
    """Signal for the geocoding result to an `ISO 3166-1 Alpha-2 region/country
     code <https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2>`_ that is specified e.g.
     FR.
     
     This parameter should not be used when the ``query`` parameter is included in the
     request."""
    bbox: Optional[list[float]] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """A rectangular area on the earth defined as a bounding box object. The sides of
     the rectangles are defined by longitude and latitude values. For more
     information, see Location and Area Types. When you specify this parameter, the
     geographical area is taken into account when computing the results of a
     location query.
     
     Example: [lon1, lat1, lon2, lat2]."""
    view: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """A string that specifies an `ISO 3166-1 Alpha-2 region/country code
     <https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2>`_. This will alter Geopolitical disputed
     borders and labels to align with the specified user region."""
    coordinates: Optional[list[float]] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """A point on the earth specified as a longitude and latitude. When you specify this parameter,
     the user’s location is taken into account and the results returned may be more relevant to the
     user. Example: [lon, lat]."""
    admin_district: Optional[str] = rest_field(
        name="adminDistrict", visibility=["read", "create", "update", "delete", "query"]
    )
    """The country subdivision portion of an address, such as WA.
     
     This parameter should not be used when the ``query`` parameter is included in the
     request."""
    admin_district2: Optional[str] = rest_field(
        name="adminDistrict2", visibility=["read", "create", "update", "delete", "query"]
    )
    """The county for the structured address, such as King.
     
     This parameter should not be used when the ``query`` parameter is included in the
     request."""
    admin_district3: Optional[str] = rest_field(
        name="adminDistrict3", visibility=["read", "create", "update", "delete", "query"]
    )
    """The named area for the structured address.
     
     This parameter should not be used when the ``query`` parameter is included in the
     request."""
    locality: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """The locality portion of an address, such as Seattle.
     
     This parameter should not be used when the ``query`` parameter is included in the
     request."""
    postal_code: Optional[str] = rest_field(
        name="postalCode", visibility=["read", "create", "update", "delete", "query"]
    )
    """The postal code portion of an address.
     
     This parameter should not be used when the ``query`` parameter is included in the
     request."""

    @overload
    def __init__(
        self,
        *,
        optional_id: Optional[str] = None,
        top: Optional[int] = None,
        query: Optional[str] = None,
        address_line: Optional[str] = None,
        country_region: Optional[str] = None,
        bbox: Optional[list[float]] = None,
        view: Optional[str] = None,
        coordinates: Optional[list[float]] = None,
        admin_district: Optional[str] = None,
        admin_district2: Optional[str] = None,
        admin_district3: Optional[str] = None,
        locality: Optional[str] = None,
        postal_code: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class GeocodingBatchResponse(_Model):
    """This object is returned from a successful Geocoding Batch service call.

    :ivar summary: Summary for the batch request.
    :vartype summary: ~azure.maps.search.models.GeocodingBatchResponseSummary
    :ivar batch_items: Array containing the batch results.
    :vartype batch_items: list[~azure.maps.search.models.GeocodingBatchResponseItem]
    :ivar next_link: The is the link to the next page of the features returned. If it's the last
     page, no this field.
    :vartype next_link: str
    """

    summary: Optional["_models.GeocodingBatchResponseSummary"] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """Summary for the batch request."""
    batch_items: Optional[list["_models.GeocodingBatchResponseItem"]] = rest_field(
        name="batchItems", visibility=["read", "create", "update", "delete", "query"]
    )
    """Array containing the batch results."""
    next_link: Optional[str] = rest_field(name="nextLink", visibility=["read", "create", "update", "delete", "query"])
    """The is the link to the next page of the features returned. If it's the last page, no this
     field."""

    @overload
    def __init__(
        self,
        *,
        summary: Optional["_models.GeocodingBatchResponseSummary"] = None,
        batch_items: Optional[list["_models.GeocodingBatchResponseItem"]] = None,
        next_link: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class GeocodingBatchResponseItem(_Model):
    """GeocodingBatchResponseItem.

    :ivar optional_id: id of the batchItem which would be the same as the id in the request.
    :vartype optional_id: str
    :ivar type: Specifies the ``GeoJSON`` type. The only supported object type is
     ``FeatureCollection``. For more information, see `RFC 7946
     <https://www.rfc-editor.org/rfc/rfc7946>`_. "FeatureCollection"
    :vartype type: str or ~azure.maps.search.models.FeatureCollectionEnum
    :ivar features:
    :vartype features: list[~azure.maps.search.models.FeaturesItem]
    :ivar next_link: The is the link to the next page of the features returned. If it's the last
     page, no this field.
    :vartype next_link: str
    :ivar error: The error detail.
    :vartype error: ~azure.maps.search.models.ErrorDetail
    """

    optional_id: Optional[str] = rest_field(
        name="optionalId", visibility=["read", "create", "update", "delete", "query"]
    )
    """id of the batchItem which would be the same as the id in the request."""
    type: Optional[Union[str, "_models.FeatureCollectionEnum"]] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """Specifies the ``GeoJSON`` type. The only supported object type is ``FeatureCollection``. For
     more information, see `RFC 7946 <https://www.rfc-editor.org/rfc/rfc7946>`_.
     \"FeatureCollection\""""
    features: Optional[list["_models.FeaturesItem"]] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    next_link: Optional[str] = rest_field(name="nextLink", visibility=["read", "create", "update", "delete", "query"])
    """The is the link to the next page of the features returned. If it's the last page, no this
     field."""
    error: Optional["_models.ErrorDetail"] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """The error detail."""

    @overload
    def __init__(
        self,
        *,
        optional_id: Optional[str] = None,
        type: Optional[Union[str, "_models.FeatureCollectionEnum"]] = None,
        features: Optional[list["_models.FeaturesItem"]] = None,
        next_link: Optional[str] = None,
        error: Optional["_models.ErrorDetail"] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class GeocodingBatchResponseSummary(_Model):
    """Summary for the batch request.

    :ivar successful_requests: Number of successful requests in the batch.
    :vartype successful_requests: int
    :ivar total_requests: Total number of requests in the batch.
    :vartype total_requests: int
    """

    successful_requests: Optional[int] = rest_field(
        name="successfulRequests", visibility=["read", "create", "update", "delete", "query"]
    )
    """Number of successful requests in the batch."""
    total_requests: Optional[int] = rest_field(
        name="totalRequests", visibility=["read", "create", "update", "delete", "query"]
    )
    """Total number of requests in the batch."""

    @overload
    def __init__(
        self,
        *,
        successful_requests: Optional[int] = None,
        total_requests: Optional[int] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class GeocodingResponse(_Model):
    """This object is returned from a successful Geocoding call.

    :ivar type: Specifies the ``GeoJSON`` type. The only supported object type is
     ``FeatureCollection``. For more information, see `RFC 7946
     <https://www.rfc-editor.org/rfc/rfc7946>`_. "FeatureCollection"
    :vartype type: str or ~azure.maps.search.models.FeatureCollectionEnum
    :ivar features:
    :vartype features: list[~azure.maps.search.models.FeaturesItem]
    :ivar next_link: The is the link to the next page of the features returned. If it's the last
     page, no this field.
    :vartype next_link: str
    """

    type: Optional[Union[str, "_models.FeatureCollectionEnum"]] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """Specifies the ``GeoJSON`` type. The only supported object type is ``FeatureCollection``. For
     more information, see `RFC 7946 <https://www.rfc-editor.org/rfc/rfc7946>`_.
     \"FeatureCollection\""""
    features: Optional[list["_models.FeaturesItem"]] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    next_link: Optional[str] = rest_field(name="nextLink", visibility=["read", "create", "update", "delete", "query"])
    """The is the link to the next page of the features returned. If it's the last page, no this
     field."""

    @overload
    def __init__(
        self,
        *,
        type: Optional[Union[str, "_models.FeatureCollectionEnum"]] = None,
        features: Optional[list["_models.FeaturesItem"]] = None,
        next_link: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class GeoJsonGeometry(_Model):
    """A valid ``GeoJSON`` geometry object. The type must be one of the seven valid GeoJSON geometry
    types - Point, MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon and
    GeometryCollection. Please refer to `RFC 7946
    <https://tools.ietf.org/html/rfc7946#section-3.1>`_ for details.

    You probably want to use the sub-classes and not this class directly. Known sub-classes are:
    GeoJsonGeometryCollection, GeoJsonLineString, GeoJsonMultiLineString, GeoJsonMultiPoint,
    GeoJsonMultiPolygon, GeoJsonPoint, GeoJsonPolygon

    :ivar type: Specifies the ``GeoJSON`` type. Must be one of the nine valid GeoJSON object types
     - Point, MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection,
     Feature and FeatureCollection. Required. Known values are: "Point", "MultiPoint", "LineString",
     "MultiLineString", "Polygon", "MultiPolygon", "GeometryCollection", "Feature", and
     "FeatureCollection".
    :vartype type: str or ~azure.maps.search.models.GeoJsonObjectType
    :ivar bbox: Bounding box. Projection used - EPSG:3857. Please refer to `RFC 7946
     <https://datatracker.ietf.org/doc/html/rfc7946#section-5>`_ for details.
    :vartype bbox: list[float]
    """

    __mapping__: dict[str, _Model] = {}
    type: str = rest_discriminator(name="type", visibility=["read", "create", "update", "delete", "query"])
    """Specifies the ``GeoJSON`` type. Must be one of the nine valid GeoJSON object types - Point,
     MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection, Feature and
     FeatureCollection. Required. Known values are: \"Point\", \"MultiPoint\", \"LineString\",
     \"MultiLineString\", \"Polygon\", \"MultiPolygon\", \"GeometryCollection\", \"Feature\", and
     \"FeatureCollection\"."""
    bbox: Optional[list[float]] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Bounding box. Projection used - EPSG:3857. Please refer to `RFC 7946
     <https://datatracker.ietf.org/doc/html/rfc7946#section-5>`_ for details."""

    @overload
    def __init__(
        self,
        *,
        type: str,
        bbox: Optional[list[float]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class GeoJsonGeometryCollection(GeoJsonGeometry, discriminator="GeometryCollection"):
    """A valid ``GeoJSON GeometryCollection`` object type. Please refer to `RFC 7946
    <https://tools.ietf.org/html/rfc7946#section-3.1.8>`_ for details.

    :ivar bbox: Bounding box. Projection used - EPSG:3857. Please refer to `RFC 7946
     <https://datatracker.ietf.org/doc/html/rfc7946#section-5>`_ for details.
    :vartype bbox: list[float]
    :ivar geometries: Contains a list of valid ``GeoJSON`` geometry objects. **Note** that
     coordinates in GeoJSON are in x, y order (longitude, latitude). Required.
    :vartype geometries: list[~azure.maps.search.models.GeoJsonGeometry]
    :ivar type: Specifies the ``GeoJSON`` type. Must be one of the nine valid GeoJSON object types
     - Point, MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection,
     Feature and FeatureCollection. Required. ``GeoJSON GeometryCollection`` geometry.
    :vartype type: str or ~azure.maps.search.models.GEO_JSON_GEOMETRY_COLLECTION
    """

    geometries: list["_models.GeoJsonGeometry"] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Contains a list of valid ``GeoJSON`` geometry objects. **Note** that coordinates in GeoJSON are
     in x, y order (longitude, latitude). Required."""
    type: Literal[GeoJsonObjectType.GEO_JSON_GEOMETRY_COLLECTION] = rest_discriminator(name="type", visibility=["read", "create", "update", "delete", "query"])  # type: ignore
    """Specifies the ``GeoJSON`` type. Must be one of the nine valid GeoJSON object types - Point,
     MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection, Feature and
     FeatureCollection. Required. ``GeoJSON GeometryCollection`` geometry."""

    @overload
    def __init__(
        self,
        *,
        geometries: list["_models.GeoJsonGeometry"],
        bbox: Optional[list[float]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.type = GeoJsonObjectType.GEO_JSON_GEOMETRY_COLLECTION  # type: ignore


class GeoJsonLineString(GeoJsonGeometry, discriminator="LineString"):
    """A valid ``GeoJSON LineString`` geometry type. Please refer to `RFC 7946
    <https://tools.ietf.org/html/rfc7946#section-3.1.4>`_ for details.

    :ivar bbox: Bounding box. Projection used - EPSG:3857. Please refer to `RFC 7946
     <https://datatracker.ietf.org/doc/html/rfc7946#section-5>`_ for details.
    :vartype bbox: list[float]
    :ivar coordinates: Coordinates for the ``GeoJson LineString`` geometry. Required.
    :vartype coordinates: list[list[float]]
    :ivar type: Specifies the ``GeoJSON`` type. Must be one of the nine valid GeoJSON object types
     - Point, MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection,
     Feature and FeatureCollection. Required. ``GeoJSON LineString`` geometry.
    :vartype type: str or ~azure.maps.search.models.GEO_JSON_LINE_STRING
    """

    coordinates: list[list[float]] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Coordinates for the ``GeoJson LineString`` geometry. Required."""
    type: Literal[GeoJsonObjectType.GEO_JSON_LINE_STRING] = rest_discriminator(name="type", visibility=["read", "create", "update", "delete", "query"])  # type: ignore
    """Specifies the ``GeoJSON`` type. Must be one of the nine valid GeoJSON object types - Point,
     MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection, Feature and
     FeatureCollection. Required. ``GeoJSON LineString`` geometry."""

    @overload
    def __init__(
        self,
        *,
        coordinates: list[list[float]],
        bbox: Optional[list[float]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.type = GeoJsonObjectType.GEO_JSON_LINE_STRING  # type: ignore


class GeoJsonMultiLineString(GeoJsonGeometry, discriminator="MultiLineString"):
    """A valid ``GeoJSON MultiLineString`` geometry type. Please refer to `RFC 7946
    <https://tools.ietf.org/html/rfc7946#section-3.1.5>`_ for details.

    :ivar bbox: Bounding box. Projection used - EPSG:3857. Please refer to `RFC 7946
     <https://datatracker.ietf.org/doc/html/rfc7946#section-5>`_ for details.
    :vartype bbox: list[float]
    :ivar coordinates: Coordinates for the ``GeoJson MultiLineString`` geometry. Required.
    :vartype coordinates: list[list[list[float]]]
    :ivar type: Specifies the ``GeoJSON`` type. Must be one of the nine valid GeoJSON object types
     - Point, MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection,
     Feature and FeatureCollection. Required. ``GeoJSON MultiLineString`` geometry.
    :vartype type: str or ~azure.maps.search.models.GEO_JSON_MULTI_LINE_STRING
    """

    coordinates: list[list[list[float]]] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Coordinates for the ``GeoJson MultiLineString`` geometry. Required."""
    type: Literal[GeoJsonObjectType.GEO_JSON_MULTI_LINE_STRING] = rest_discriminator(name="type", visibility=["read", "create", "update", "delete", "query"])  # type: ignore
    """Specifies the ``GeoJSON`` type. Must be one of the nine valid GeoJSON object types - Point,
     MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection, Feature and
     FeatureCollection. Required. ``GeoJSON MultiLineString`` geometry."""

    @overload
    def __init__(
        self,
        *,
        coordinates: list[list[list[float]]],
        bbox: Optional[list[float]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.type = GeoJsonObjectType.GEO_JSON_MULTI_LINE_STRING  # type: ignore


class GeoJsonMultiPoint(GeoJsonGeometry, discriminator="MultiPoint"):
    """A valid ``GeoJSON MultiPoint`` geometry type. Please refer to `RFC 7946
    <https://tools.ietf.org/html/rfc7946#section-3.1.3>`_ for details.

    :ivar bbox: Bounding box. Projection used - EPSG:3857. Please refer to `RFC 7946
     <https://datatracker.ietf.org/doc/html/rfc7946#section-5>`_ for details.
    :vartype bbox: list[float]
    :ivar coordinates: Coordinates for the ``GeoJson MultiPoint`` geometry. Required.
    :vartype coordinates: list[list[float]]
    :ivar type: Specifies the ``GeoJSON`` type. Must be one of the nine valid GeoJSON object types
     - Point, MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection,
     Feature and FeatureCollection. Required. ``GeoJSON MultiPoint`` geometry.
    :vartype type: str or ~azure.maps.search.models.GEO_JSON_MULTI_POINT
    """

    coordinates: list[list[float]] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Coordinates for the ``GeoJson MultiPoint`` geometry. Required."""
    type: Literal[GeoJsonObjectType.GEO_JSON_MULTI_POINT] = rest_discriminator(name="type", visibility=["read", "create", "update", "delete", "query"])  # type: ignore
    """Specifies the ``GeoJSON`` type. Must be one of the nine valid GeoJSON object types - Point,
     MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection, Feature and
     FeatureCollection. Required. ``GeoJSON MultiPoint`` geometry."""

    @overload
    def __init__(
        self,
        *,
        coordinates: list[list[float]],
        bbox: Optional[list[float]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.type = GeoJsonObjectType.GEO_JSON_MULTI_POINT  # type: ignore


class GeoJsonMultiPolygon(GeoJsonGeometry, discriminator="MultiPolygon"):
    """A valid ``GeoJSON MultiPolygon`` object type. Please refer to `RFC 7946
    <https://tools.ietf.org/html/rfc7946#section-3.1.7>`_ for details.

    :ivar bbox: Bounding box. Projection used - EPSG:3857. Please refer to `RFC 7946
     <https://datatracker.ietf.org/doc/html/rfc7946#section-5>`_ for details.
    :vartype bbox: list[float]
    :ivar coordinates: Contains a list of valid ``GeoJSON Polygon`` objects. **Note** that
     coordinates in GeoJSON are in x, y order (longitude, latitude). Required.
    :vartype coordinates: list[list[list[list[float]]]]
    :ivar type: Specifies the ``GeoJSON`` type. Must be one of the nine valid GeoJSON object types
     - Point, MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection,
     Feature and FeatureCollection. Required. ``GeoJSON MultiPolygon`` geometry.
    :vartype type: str or ~azure.maps.search.models.GEO_JSON_MULTI_POLYGON
    """

    coordinates: list[list[list[list[float]]]] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Contains a list of valid ``GeoJSON Polygon`` objects. **Note** that coordinates in GeoJSON are
     in x, y order (longitude, latitude). Required."""
    type: Literal[GeoJsonObjectType.GEO_JSON_MULTI_POLYGON] = rest_discriminator(name="type", visibility=["read", "create", "update", "delete", "query"])  # type: ignore
    """Specifies the ``GeoJSON`` type. Must be one of the nine valid GeoJSON object types - Point,
     MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection, Feature and
     FeatureCollection. Required. ``GeoJSON MultiPolygon`` geometry."""

    @overload
    def __init__(
        self,
        *,
        coordinates: list[list[list[list[float]]]],
        bbox: Optional[list[float]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.type = GeoJsonObjectType.GEO_JSON_MULTI_POLYGON  # type: ignore


class GeoJsonPoint(GeoJsonGeometry, discriminator="Point"):
    """A valid ``GeoJSON Point`` geometry type. Please refer to `RFC 7946
    <https://tools.ietf.org/html/rfc7946#section-3.1.2>`_ for details.

    :ivar bbox: Bounding box. Projection used - EPSG:3857. Please refer to `RFC 7946
     <https://datatracker.ietf.org/doc/html/rfc7946#section-5>`_ for details.
    :vartype bbox: list[float]
    :ivar coordinates: A ``Position`` is an array of numbers with two or more elements. The first
     two elements are *longitude* and *latitude*, precisely in that order. *Altitude/Elevation* is
     an optional third element. Please refer to `RFC 7946
     <https://tools.ietf.org/html/rfc7946#section-3.1.1>`_ for details. Required.
    :vartype coordinates: list[float]
    :ivar type: Specifies the ``GeoJSON`` type. Must be one of the nine valid GeoJSON object types
     - Point, MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection,
     Feature and FeatureCollection. Required. ``GeoJSON Point`` geometry.
    :vartype type: str or ~azure.maps.search.models.GEO_JSON_POINT
    """

    coordinates: list[float] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """A ``Position`` is an array of numbers with two or more elements. The first two elements are
     *longitude* and *latitude*, precisely in that order. *Altitude/Elevation* is an optional third
     element. Please refer to `RFC 7946 <https://tools.ietf.org/html/rfc7946#section-3.1.1>`_ for
     details. Required."""
    type: Literal[GeoJsonObjectType.GEO_JSON_POINT] = rest_discriminator(name="type", visibility=["read", "create", "update", "delete", "query"])  # type: ignore
    """Specifies the ``GeoJSON`` type. Must be one of the nine valid GeoJSON object types - Point,
     MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection, Feature and
     FeatureCollection. Required. ``GeoJSON Point`` geometry."""

    @overload
    def __init__(
        self,
        *,
        coordinates: list[float],
        bbox: Optional[list[float]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.type = GeoJsonObjectType.GEO_JSON_POINT  # type: ignore


class GeoJsonPolygon(GeoJsonGeometry, discriminator="Polygon"):
    """A valid ``GeoJSON Polygon`` geometry type. Please refer to `RFC 7946
    <https://tools.ietf.org/html/rfc7946#section-3.1.6>`_ for details.

    :ivar bbox: Bounding box. Projection used - EPSG:3857. Please refer to `RFC 7946
     <https://datatracker.ietf.org/doc/html/rfc7946#section-5>`_ for details.
    :vartype bbox: list[float]
    :ivar coordinates: Coordinates for the ``GeoJson Polygon`` geometry type. Required.
    :vartype coordinates: list[list[list[float]]]
    :ivar type: Specifies the ``GeoJSON`` type. Must be one of the nine valid GeoJSON object types
     - Point, MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection,
     Feature and FeatureCollection. Required. ``GeoJSON Polygon`` geometry.
    :vartype type: str or ~azure.maps.search.models.GEO_JSON_POLYGON
    """

    coordinates: list[list[list[float]]] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Coordinates for the ``GeoJson Polygon`` geometry type. Required."""
    type: Literal[GeoJsonObjectType.GEO_JSON_POLYGON] = rest_discriminator(name="type", visibility=["read", "create", "update", "delete", "query"])  # type: ignore
    """Specifies the ``GeoJSON`` type. Must be one of the nine valid GeoJSON object types - Point,
     MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection, Feature and
     FeatureCollection. Required. ``GeoJSON Polygon`` geometry."""

    @overload
    def __init__(
        self,
        *,
        coordinates: list[list[list[float]]],
        bbox: Optional[list[float]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.type = GeoJsonObjectType.GEO_JSON_POLYGON  # type: ignore


class GeometryCopyright(_Model):
    """Copyright information of a geometry of a Boundary object.

    :ivar source_name: The name of the data provider.
    :vartype source_name: str
    :ivar copyright: The copyright string for the data provider.
    :vartype copyright: str
    """

    source_name: Optional[str] = rest_field(
        name="sourceName", visibility=["read", "create", "update", "delete", "query"]
    )
    """The name of the data provider."""
    copyright: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """The copyright string for the data provider."""

    @overload
    def __init__(
        self,
        *,
        source_name: Optional[str] = None,
        copyright: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class Intersection(_Model):
    """The address of the result.

    :ivar base_street: Primary street for the location.
    :vartype base_street: str
    :ivar secondary_street1: The first intersecting street.
    :vartype secondary_street1: str
    :ivar secondary_street2: If any, the second intersecting street.
    :vartype secondary_street2: str
    :ivar intersection_type: Type of intersection.
    :vartype intersection_type: str
    :ivar display_name: Complete name of the intersection.
    :vartype display_name: str
    """

    base_street: Optional[str] = rest_field(
        name="baseStreet", visibility=["read", "create", "update", "delete", "query"]
    )
    """Primary street for the location."""
    secondary_street1: Optional[str] = rest_field(
        name="secondaryStreet1", visibility=["read", "create", "update", "delete", "query"]
    )
    """The first intersecting street."""
    secondary_street2: Optional[str] = rest_field(
        name="secondaryStreet2", visibility=["read", "create", "update", "delete", "query"]
    )
    """If any, the second intersecting street."""
    intersection_type: Optional[str] = rest_field(
        name="intersectionType", visibility=["read", "create", "update", "delete", "query"]
    )
    """Type of intersection."""
    display_name: Optional[str] = rest_field(
        name="displayName", visibility=["read", "create", "update", "delete", "query"]
    )
    """Complete name of the intersection."""

    @overload
    def __init__(
        self,
        *,
        base_street: Optional[str] = None,
        secondary_street1: Optional[str] = None,
        secondary_street2: Optional[str] = None,
        intersection_type: Optional[str] = None,
        display_name: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class ReverseGeocodingBatchRequestBody(_Model):
    """The list of reverse geocoding queries/requests to process. The list can contain a max of 100
    queries and must contain at least 1 query.

    :ivar batch_items: The list of queries to process.
    :vartype batch_items: list[~azure.maps.search.models.ReverseGeocodingBatchRequestItem]
    """

    batch_items: Optional[list["_models.ReverseGeocodingBatchRequestItem"]] = rest_field(
        name="batchItems", visibility=["read", "create", "update", "delete", "query"]
    )
    """The list of queries to process."""

    @overload
    def __init__(
        self,
        *,
        batch_items: Optional[list["_models.ReverseGeocodingBatchRequestItem"]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class ReverseGeocodingBatchRequestItem(_Model):
    """Batch Query object.

    :ivar optional_id: id of the request which would show in corresponding batchItem.
    :vartype optional_id: str
    :ivar coordinates: The coordinates of the location that you want to reverse geocode. Example:
     [lon,lat].
    :vartype coordinates: list[float]
    :ivar result_types: Specify entity types that you want in the response. Only the types you
     specify will be returned. If the point cannot be mapped to the entity types you specify, no
     location information is returned in the response. Default value is all possible entities. A
     comma separated list of entity types selected from the following options.

     * Address
     * Neighborhood
     * PopulatedPlace
     * Postcode1
     * AdminDivision1
     * AdminDivision2
     * CountryRegion

     These entity types are ordered from the most specific entity to the least
     specific entity. When entities of more than one entity type are found, only the
     most specific entity is returned. For example, if you specify Address and
     AdminDistrict1 as entity types and entities were found for both types, only the
     Address entity information is returned in the response.
    :vartype result_types: list[str or ~azure.maps.search.models.ResultTypeEnum]
    :ivar view: A string that specifies an `ISO 3166-1 Alpha-2 region/country code
     <https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2>`_. This will alter Geopolitical disputed
     borders and labels to align with the specified user region.
    :vartype view: str
    """

    optional_id: Optional[str] = rest_field(
        name="optionalId", visibility=["read", "create", "update", "delete", "query"]
    )
    """id of the request which would show in corresponding batchItem."""
    coordinates: Optional[list[float]] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """The coordinates of the location that you want to reverse geocode. Example: [lon,lat]."""
    result_types: Optional[list[Union[str, "_models.ResultTypeEnum"]]] = rest_field(
        name="resultTypes", visibility=["read", "create", "update", "delete", "query"]
    )
    """Specify entity types that you want in the response. Only the types you specify will be
      returned. If the point cannot be mapped to the entity types you specify, no location
      information is returned in the response. Default value is all possible entities. A comma
      separated list of entity types selected from the following options.
 
      * Address
      * Neighborhood
      * PopulatedPlace
      * Postcode1
      * AdminDivision1
      * AdminDivision2
      * CountryRegion
 
      These entity types are ordered from the most specific entity to the least
      specific entity. When entities of more than one entity type are found, only the
      most specific entity is returned. For example, if you specify Address and
      AdminDistrict1 as entity types and entities were found for both types, only the
      Address entity information is returned in the response."""
    view: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """A string that specifies an `ISO 3166-1 Alpha-2 region/country code
     <https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2>`_. This will alter Geopolitical disputed
     borders and labels to align with the specified user region."""

    @overload
    def __init__(
        self,
        *,
        optional_id: Optional[str] = None,
        coordinates: Optional[list[float]] = None,
        result_types: Optional[list[Union[str, "_models.ResultTypeEnum"]]] = None,
        view: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
